### PR TITLE
Fix watches on moves and removes

### LINKED ISSUE #3312: `error: file not found (searched at <file path>)` after 6999be
### Description

After commit 6999be9ab0d851d0b3b34bd311712c27887721f1, running `typst watch <file.typ> <file.pdf>` shows the error `error: file not found (searched at <file.typ>)` whenever the file is saved (with or without modificiations) and doesn't write/save the generated pdf file.

This error occurs on 426445edfc8d32d9ff8fcb79cda5b7765209f567 as well (the only commit after the one that introduced the bug) and does not appear before 6999be9ab0d851d0b3b34bd311712c27887721f1, as far as I can tell.

I tried to look at the changes introduced in 6999be9ab0d851d0b3b34bd311712c27887721f1, but couldn't figure out what exactly might've caused this issue as I'm not familiar with the codebase.

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by frozolotl**
Supersedes #3364 and fixes #3312, as well as #2714.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Could you explain why this would fix #2714? It doesn't in my testing, which makes sense to me. The problem there is that we cannot watch a non-existent file and would need to watch the parent directory instead, which this change doesn't do.

Also, is the idea that this "just" fixes #3312 in presence of alternate screen or does it fix an issue that is also somehow present in 0.10? I do not yet understand why the new `missing` set is needed. Shouldn't `watched.remove` already have the effect of `missing.insert`?

I understand that the `recv_timeout` in the for loop now polls every 100ms to ensure that we can regularly check `terminal::out().is_active()` so that Ctrl + C continues working. (Which isn't ideal from a battery life perspective, but probably not that big of a deal.) This is only necessary to be able to properly leave the alternate screen at the end of `fn main()` from my understanding. What I'm wondering now is: Can't we just leave the alternate screen in the Ctrl + C handler instead and go back to the original `loop`?

**Comment by frozolotl** [comment]
> Could you explain why this would fix #2714? It doesn't in my testing, which makes sense to me. The problem there is that we cannot watch a non-existent file and would need to watch the parent directory instead, which this change doesn't do.

> I do not yet understand why the new `missing` set is needed. Shouldn't `watched.remove` already have the effect of `missing.insert`?

Oh, right, it only fixes: remove, wait for at least 100ms, then create again. Which is definitely more limited than #2714. That's also what the `missing` is for.
I think the code here should be very easy to adjust to support watches on files that don't even exist on startup, however. I'll do that later today, I think.

> Also, is the idea that this "just" fixes #3312 in presence of alternate screen or does it fix an issue that is also somehow present in 0.10?

It fixes #3312 and also a small and not that important bug, where as long as a file was modified in sub-100ms intervals, no recompilation would ever occur.

> I understand that the `recv_timeout` in the for loop now polls every 100ms to ensure that we can regularly check `terminal::out().is_active()` so that Ctrl + C continues working. (Which isn't ideal from a battery life perspective, but probably not that big of a deal.)

That is correct. Though the polling is also done to support deleted files being watched.

> This is only necessary to be able to properly leave the alternate screen at the end of `fn main()` from my understanding. What I'm wondering now is: Can't we just leave the alternate screen in the Ctrl + C handler instead and go back to the original `loop`?

The exit handler already leaves the alternate screen, so that is not a problem. However, the forcible termination (and alternate screen exit) only happens 750 ms after the signal was received. That delay does in no way feel instant.
I implemented that to make sure that, if possible, files are read and any destructors are run.
We could reduce that delay at the (small) risk of file corruption.

PS: Polling definitely is not as clean a way of doing watches as `inotify` is, but I think it has nicer performance characteristics overall and is easier to implement.
If we used the "watch parent folder" approach, depending on how many parent folders are deleted and how many files the deepest parent folder contains, there could be a lot of notify signals to filter through.
The "poll missing files" approach needs to check the existence of only the missing files, which are explicitly declared by the user.
"watch parent folder" likely performs better on average, but "poll missing files" has predictable worst-case performance and isn't that bad on average either. It's also easier to implement I think.

**Comment by laurmaedje** [comment]
Okay, I understand `missing` now. But that also means that if `missing` is empty, we could wait for the next event instead of polling the empty set. At least if Ctrl + C exited immediately and we wouldn't need to yield to the watch loop because of that.

**Comment by frozolotl** [comment]
> At least if Ctrl + C exited immediately and we wouldn't need to yield to the watch loop because of that.

But in that case there would be the thing about the drop handlers and the writing of files. We could immediately exit on ctrl-c and simply not worry about any files being correct. That would be the users' responsibility, similar to not holding down the power button to shut down during an update.

**Comment by laurmaedje** [comment]
But wasn't that the case before your PR, too? I was just surprised that this change was unrelated to the alternate screen.

I'm also wondering which writing of files specifically. Okay, if you hit Ctrl + C _exactly_ while it is writing the PDF, you get half a PDF, but that's on you then. And I'm not aware of other important drop handlers.

**Comment by frozolotl** [comment]
> I'm also wondering which writing of files specifically. Okay, if you hit Ctrl + C _exactly_ while it is writing the PDF, you get half a PDF, but that's on you then. And I'm not aware of other important drop handlers.

I'll remove the delay then.

**Comment by laurmaedje** [comment]
The fix for #2714 doesn't seem to work on my system (macOS). The `missing` set is always empty. Looking at the code, the `missing` set only seems to be inserted into during the watch loop when there are particular fs events. But considering the case of missing files in the initial compilation, it will just be empty and nothing will be polled.

It seems to me that the right place to update the `missing` set would be in `watch_dependencies`, just adding any files that don't exist (i.e. removing the `.filter(|path| path.exists())` code and adding code to handle that case).

**Comment by frozolotl** [comment]
I have now changed it so that if world creation fails, which can happen if the `main.typ` does not exist yet, `typst watch` will not shut down.

**Pull request merged**
