### PR TITLE
Improve test-helper: prevent spawning multiple processes of `cargo test`

### PR DESCRIPTION
**Pull request by Leedehai**
We need to debounce clicks on the "Run Test" button. That is, when a testing is running, that button should be deactivated in the UI.

Before this fix, multiple clicks on this button (e.g. when the developer gets impatient during the idle waiting) will spawn multiple child processes. Though `cargo build` invocations in the same Rust project are serialized thanks to the file lock, spawning multiple processes is still undesired, and most likely unintended. Moreover, spawning multiple processes--either on the same *.typ file or different files--will mess up the running status indicator in the status bar, since it is semantically a cross-file global state.

This patch also adds a tooltip to the running status indicator to remind developers that the long wait time may be a result of rebuilding.

Unrelated but as a nice-to-have, this patch replaces `cargo test`'s argument `--all` with `--workspace`, because the former is a deprecated alias of the latter. See:
```
$ cargo test --help | grep -e "--workspace "
      --workspace         Test all packages in the workspace
      --all               Alias for --workspace (deprecated)
```

### CODE REVIEW

**Comment by Leedehai** [comment]
I also considered showing a small notification box in the lower right corner if the running status indicator is clicked upon, and have that box display a real-time view of the most recent line printed by `cargo test`. This is doable with VSCode's extension API, but I think you may find this an overkill :)

**Comment by Leedehai** [comment]
I also considered showing a [small box](https://github.com/microsoft/vscode-extension-samples/blob/main/progress-sample/README.md) in the lower right corner if the running status indicator is clicked upon, and have that box display a real-time view of the most recent line printed by `cargo`. This is doable with VSCode's API and `child_process` and helps with relieve developer's doubt during the waiting, but I think you may find this box an overkill so didn't do it :)

**Comment by laurmaedje** [comment]
> I also considered showing a [small box](https://github.com/microsoft/vscode-extension-samples/blob/main/progress-sample/README.md) in the lower right corner if the running status indicator is clicked upon, and have that box display a real-time view of the most recent line printed by cargo. This is doable with VSCode's API and child_process and helps with relieve developer's doubt during the waiting, but I think you may find this box an overkill so didn't do it :)

That sounds awesome! I'd love this.

**Comment by Leedehai** [comment]
>> I also considered showing a [small box](https://github.com/microsoft/vscode-extension-samples/blob/main/progress-sample/README.md) in the lower right corner...

> That sounds awesome! I'd love this.

Done 🎉 

https://github.com/typst/typst/assets/18319900/a81e84e5-f48e-4373-a3f8-2241c91102ef

**Comment by laurmaedje** [comment]
Thank you!

**Pull request merged**
