### PR TITLE
Compare rasterized svg image with reference png

### PR DESCRIPTION
**Pull request by Enter-tainer**
Currently the lowest similarity score is 0.88 for `text/chinese.typ`. However, I have to say that these two files look identical to me and I am Chinese. Perhaps we should adjust the threshold or use a better comparison algorithm. 
```
text/chinese.typ ❌
  Svg image difference: 0.8893894203011192
```
image

### CODE REVIEW

**Comment by Enter-tainer** [comment]
Unfortunately, even if I add `123123` to the end of `coma.typ`, the similarity score is still above 0.95. Perhaps SSIM is not a good metric here.

**Comment by istudyatuni** [comment]
Why not compare SVG files directly? Sorry, maybe I missed some discussion

**Comment by Enter-tainer** [comment]
> Why not compare SVG files directly? Sorry, maybe I missed some discussion 

you can take a look at my previous (closed) pr. it is doing extactly what you want. But i guess it would be better if we have a single groundtruth as reference.

**Comment by Enter-tainer** [comment]
> Or we should conduct a deep dive to understand why these invisible differences occur.

difference happens only when there are texts in doc. i guess this should somehow related to glyph rendering. will have a close look hopefully in weekend

**Comment by andrewragy** [comment]
I think the problem is (and I might be mistaken) the pixel-by-pixel comparison. I think some kind of AI model should be used to compare shapes rather than pixels but that might introduce unnecessary overhead.

**Comment by Enter-tainer** [comment]
which ai model do you recommend? i will have a try

**Comment by LaurenzV** [comment]
Maybe you can try library: https://github.com/kornelski/dssim

I only tested it very briefly, but at least in my test I seem to get a score of 0.00509714 for the Chinese one (0 being identical), so maybe we could give it a shot.

**Comment by Enter-tainer** [comment]
dssim looks good to me :+1:. I found that it generally looks good to me. There are some images with large diff score. Note that the range of score is [0, +oo), 0 means no difference.
1. `tests/svg/visualize/svg-text.svg.png`: 0.086303 the rasterized svg doesn't have text in it. Perhaps because we disable a lot of feature for resvg.
image

2.  `tests/svg/layout/pagebreak.svg.png`: 0.041441 There is a white bar on the top of black rect. I cannot repo this on chrome because ... chrome has a white background. Not sure if this is a svg bug of resvg misuse.
image

3. `layout/grid-auto-shrink.typ`: 0.026074 No visible difference.
image

4. `compute/data.typ` 0.023330 No visible difference. Perhaps svg render the grid incorrectly?
image

**Comment by Enter-tainer** [comment]
dssim also don't help with very small differences. I change coma.typ
image

and the score is `0.005269`

**Comment by Enter-tainer** [comment]
I think we can use sssim and set the threshold to 0.2 or so. This should be a good option.

**Comment by LaurenzV** [comment]
I just realized `dssim` is AGPL-licensed, but I guess this isn't an issue for us since it's only a dev dependency, right?

**Comment by andrewragy** [comment]
> which ai model do you recommend? i will have a try

Unfortunately, I am not sure but I think it would work with some kind of neural network that takes the two images and spits out a similarity factor.

**Comment by Enivex** [comment]
I don't think a machine learning solution is a good idea. It would be a slow black box. There are plenty of metrics that are easy to compute and interpret.

**Comment by Enter-tainer** [comment]
@Enivex can you recommend some good metrics for this use case?

**Comment by Enter-tainer** [comment]
I'm starting to understand why the tables has high differences scores. It appears that anti-aliasing is applied on the y axis of the table.
image

**Comment by Enter-tainer** [comment]
i just mis-close this. will reopen soon..

**Pull request closed without merging**
