### PR TITLE
Add hints for invalid identifier errors

### PR DESCRIPTION
**Pull request by tingerrr**
## Invalid identifiers
```typst
#let none = none
```

Will add a hint why this specific node is not expected here:
```
error: expected identifier, found `none`
  ┌─ test/test.typ:1:5
  │
1 │ #let none = none
  │      ^^^^
  │
  = hint: `none` is not allowed as an identifier; try `_none` instead
```

This previously hinted within the error message itself:
```typst
#let a = 1
#{a = a-1}
```

Now uses a hint to suggest adding spaces around the minus if the var is unknown:
```
error: unknown variable: a-1
  ┌─ test/test.typ:2:6
  │
2 │ #{a = a-1}
  │       ^^^
  │
  = hint: if you meant to use subtraction, try adding spaces around the minus sign
```

## Unknown variable in math mode
```typst
#let bbox(stroke: 0pt) = box(stroke: stroke)[$b o x$]
$ bbox(stroke: none) $
```

Will now for some literals hint that a has must be used:
```
error: unknown variable: none
  ┌─ test/test.typ:2:15
  │
2 │ $ bbox(stroke: none) $
  │                ^^^^
  │
  = hint: if you meant to use a literal, add a hash before it
```

Because `bbox(stroke: 12pt)` will create 2 tokens, `[12, pt]` the node would only get `pt` which is a valid identifier, so not all cases are easily caught with this.

I opted to keep it simple (only triggers on `false`, `true`, `none` and `auto`) to avoid false positives.

### CODE REVIEW

**Comment by MDLC01** [comment]
For the first hint, I'm not sure `_none` is a good suggestion, because Typst generally uses kebab-case, and most other languages would prefer `none_` (preceding an identifier with an underscore tends to imply it is private).

**Comment by tingerrr** [comment]
> For the first hint, I'm not sure `_none` is a good suggestion, because Typst generally uses kebab-case, and most other languages would prefer `none_` (preceding an identifier with an underscore tends to imply it is private).

That's true. I didn't want to make any particular decision on that, it was more or less copied from rustc which of course has different conventions.

**Comment by PgBiel** [comment]
IMHO `none` (and `auto`, and other relevant keywords) should just work :tm: in math mode. It could be worth it to assess whether or not that could be potentially confusing for users first, however.

**Comment by tingerrr** [comment]
> IMHO `none` (and `auto`, and other relevant keywords) should just work ™️ in math mode. It could be worth it to assess whether or not that could be potentially confusing for users first, however.

I think it would be, it brings in a dichotomy between literals that work and those that don't, user would be reasonably confused why only some of those work:
```typst
$ func(none) $  // should work?
$ func(12pt) $  // doesn't work
$ func(#12pt) $ // works
$ #func(12pt) $ // works
```

> **EDIT:** A somewhat reasonable argument against this could be futureproofing against symbol names... but if you can't even override them, as they would have keywords' names, then maybe those wouldn't be good names anyway.

Yeah, they currently can't and likely won't, so I wouldn't say that's an issue.

> Alternatively, the error should just say that you're trying to use a keyword instead of saying "unknown variable".

Perhaps, but I don't think that fits 100%, after all it's more so that users want to use literals in math and don't know why they're parsed as identifiers. And it would be great to extend this to non-keyword literals too, I just wasn't sure how without reparsing part of the arg list.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
