### PR TITLE
Fix widow pad frames

### LINKED ISSUE #4234: Element with no content followed by `pad` can force breakable block to create an empty frame
### Description

This bug has a similar effect as #2297, which was fixed by #2517. Sadly, the fix does not work in the specific case where the element with no content is directly followed by a `pad` element (which happens somewhat often given that `block` used `pad` under the hood to make `inset` work).

### Example

```typ
#set page(height: 3cm, margin: 0.5cm)

Not enough space remaining on this page to fit the whole block.

#block(stroke: 1pt)[
  #counter("dummy").update(1)
  #pad(left: 1cm, top: 1cm, rect(height: 1cm, fill: gray))
]
```

An empty frame is created for the counter update.

Typst produces the same output without an explicit `pad`:

```typ
#set page(height: 3cm, margin: 0.5cm)

Not enough space remaining on this page to fit the whole block.

#block(stroke: 1pt)[
  #counter("dummy").update(1)
  #block(inset: (left: 1cm, top: 1cm), rect(height: 1cm, fill: gray))
]
```

Note that removing the counter update removes the undesired rectangle.

### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by MDLC01**
Fixes #4234.

It turns out the empty frames created by `pad` have a non-zero size (they had padding applied to them). This made #2517 not work with those frames.

This PR solves the issue by applying the following transformation: each of the empty frames generated by `pad` that come before any content become zero-sized.[^1] In case of a `pad` element that generates only empty frames, the last one is always kept in order to make sure the element never "disappears".

[^1]: It is actually a tiny bit more complicated than that, due to some frames having negative dimensions (see [this Discord message](https://discord.com/channels/1054443721975922748/1088371867913572452/1242205845102657586)).

### CODE REVIEW

**Comment by MDLC01** [comment]
Turns out this is harder than I thought. I'm marking this as a draft for now.

**Comment by MDLC01** [comment]
Actually, I just forgot to add a test ref! So this PR is now ready for review.

**Comment by laurmaedje** [comment]
Is there an associated issue for this?

The whole approach of skipping zero-sized frames in the flow is a bit of hack in my opinion. Adding to this with more complexity in padding seems like a potential maintainance burden to me. It is already very hard to change this in the flow already due to the various ad-hoc bug fixes in it.

**Comment by MDLC01** [comment]
> Is there an associated issue for this?

There is not. I can create one.

Another idea I had after making this PR, which may feel less hacky, was to allow fragments to contain "fillers" instead of frames, which act as zero-sized frames, and are used instead of an empty frame that would have been created to fill a region when nothing fits into it. I don't know how this related this would be to #4212 (if at all).

**Comment by MDLC01** [comment]
I created #4234.

**Comment by laurmaedje** [comment]
Let's wait with this until after the layout refactor (if I don't fix it myself during it). Every extra somewhat ad-hoc fix makes incremental refactoring harder.

**Comment by MDLC01** [comment]
Ok. I'm closing this PR, then.

**Pull request closed without merging**
