### PR TITLE
Add U-shaped arrows

### PR DESCRIPTION
**Pull request by MDLC01**
This small PR adds the four U-shaped arrows:
- U+2B8E ⮎ ANTICLOCKWISE TRIANGLE-HEADED LEFT U-SHAPED ARROW as `arrow.r.u`;
- U+2B8C ⮌ ANTICLOCKWISE TRIANGLE-HEADED RIGHT U-SHAPED ARROW as `arrow.l.u`;
- U+2B8D ⮍ ANTICLOCKWISE TRIANGLE-HEADED BOTTOM U-SHAPED ARROW as `arrow.t.u`;
- U+2B8F ⮏ ANTICLOCKWISE TRIANGLE-HEADED TOP U-SHAPED ARROW as `arrow.b.u`.

### CODE REVIEW

**Comment by Enivex** [comment]
I'm not sure I'm a fan of using a single letter (u) here

**Comment by MDLC01** [comment]
What about `turn` or `uturn`? I agree that using a single lettre for such a niche variant is weird, but I'm not sure what else to use.

**Comment by Enivex** [comment]
I think `turn` is decent

**Comment by MDLC01** [comment]
Looking at [this list of Unicode arrow symbols](https://unicode-explorer.com/list/arrows), that's hard to say, because some arrows could qualify as "turn", but I think most would be better suited as variants of `arrow.cw` and `arrow.ccw`.

**Comment by MDLC01** [comment]
Updated to `turn` because other Unicode arrow codepoints that could qualify as "turn" seem to be better suited as variants of `cw` and `ccw`.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
