### PR TITLE
Fix `math.lr` size argument not being applied to enclosed `math.mid`

### LINKED ISSUE #3186: `lr()`'s size argument can't consistently be applied to enclosed `mid()`
### Description

```typ
$
  lr({ A mid(|) integral }) quad
  lr(size: #1em, { A mid(|) integral }) quad
  lr(size: #(1em+20%), { A mid(|) integral }) "wrong" \

  lr(] A mid(|) integral ]) quad
  lr(size: #1em, ] A mid(|) integral ]) quad
  lr(size: #(1em+20%), ] A mid(|) integral ]) "ok" \

  lr(( A mid(|) integral ]) quad
  lr(size: #1em, ( A mid(|) integral ]) quad
  lr(size: #(1em+20%), ( A mid(|) integral ]) "wrong"
$
```
Screenshot 2024-01-12 at 20 28 44

### Typst version

- [x] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by mkorje**
Closes #3186.

I also made it so that the contents of an `EquationElem` are extracted.

See the tests for examples.

### CODE REVIEW

**Comment by mkorje** [comment]
It appears this has also fixed all but one of the cases in #2979 as well. Case D given in that issue is a parsing problem, somewhat similar to #896 (in that delimiters wrapping attachments and fractions are stuffed).

**Comment by laurmaedje** [comment]
Does it also fix the problem when there is a comma present in the body?

**Comment by mkorje** [comment]
> Does it also fix the problem when there is a comma present in the body?

Yep. Including the comma hasn't been changed at all.

**Comment by laurmaedje** [comment]
Because the body `#[parse]` code would still produce a sequence in that case. I'm a bit confused what the exact idea behind the change of that parsing code is.

**Comment by mkorje** [comment]
For a single element as the body, for example the automatic `LrElem` created as the body, it would previously be parsed as a sequence with one element. This makes it so that a single element isn't parsed as a sequence.

**Comment by mkorje** [comment]
It was never an issue with a comma, I believe, since it can't have been made into a LrElem implicitly then.

**Comment by laurmaedje** [comment]
Ah!

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
