### PR TITLE
Add a bezier primitive

### PR DESCRIPTION
**Pull request by SekoiaTree**
Related to #260. Adds a Bezier primitive, documented and tested with some basic tests.

Like `line` there's a start and an end. Although the `line` docs say `end` is an offset relative to the start, from my testing they're not, so I did the same for `bezier`.

Beziers also have a `start-control-point` and `end-control-point` which are relative to their respective end point. Finally, just like `line`, the `stroke` is configurable.

### CODE REVIEW

**Comment by LaurenzV** [comment]
I'm thinking, would it make sense to rename the method to `curve` instead of `bezier`? I think the term `curve` would be more easily understandable for most people.

And is there something speaking against actually just combining this with `line` (i.e. add `start-control-point` and `end-control-point` as additional parameters to `line`?

**Comment by SekoiaTree** [comment]
`line` has the `length` and `angle` parameters, which make much less sense for a curve.

As for renaming, no problem, but Bezier is more explicit? And it'll pop up if you search for "curve" in the docs.

**Comment by laurmaedje** [comment]
I think it would make sense if a single curve/bezier call could produce a curve with multiple segments. Otherwise, filling won't work properly. A single stroked curve would just be a special case of that.

**Comment by SekoiaTree** [comment]
> I think it would make sense if a single curve/bezier call could produce a curve with multiple segments. Otherwise, filling won't work properly. A single stroked curve would just be a special case of that.

Sure, but at that point I'd rather call it "path" (and probably open a different PR). Here's a quick syntax proposal:
- "closed" boolean parameter which determines if we close it off at the end with a straight line
- stroke parameter
- fill parameter
- a list of vertices, each written as either a single 2 element array, or an array of 2 points (1 mirrored point) or an array of 3 points (1 vertex + 2 control points)

Type-wise, I almost feel we should create a "Point" type that can be coerced from a 2 element array, for ease of writing.

Opinions?

**Comment by SekoiaTree** [comment]
> Can I suggest using the Hobby algorithm? Here's a tex implementation:
> 
> https://ctan.org/pkg/hobby?lang=en
> 
> It's very aesthetically pleasing.

Seems like that would fit under "one mirrored control point", correct?

**Comment by laurmaedje** [comment]
> Opinions?
Seems sensible. The problem with the `Point` type is that it already exists, but only allows absolute units. I had a similar problem with `Length` and `Abs` as well as `Stroke` and `PartialStroke`. Naming is hard.

**Comment by Enivex** [comment]
> 



> > Can I suggest using the Hobby algorithm? Here's a tex implementation:
> > https://ctan.org/pkg/hobby?lang=en
> > It's very aesthetically pleasing.
> 
> Seems like that would fit under "one mirrored control point", correct?

I don't think so. The goal of Hobby's algorithm is to create nice looking interpolating splines through a list of points, with some degree of freedom. I'm not intimately familiar with the actual algorithm, but I think it's somewhat more complicated than that. It was originally published in this paper https://link.springer.com/article/10.1007/BF02187690

**Comment by SekoiaTree** [comment]
> 

You're right, it's not the same. However it can be described using Beziers, so this would probably be an extension rather than a core thing.

**Comment by SekoiaTree** [comment]
> > Opinions?
> 
> Seems sensible. The problem with the `Point` type is that it already exists, but only allows absolute units. I had a similar problem with `Length` and `Abs` as well as `Stroke` and `PartialStroke`. Naming is hard.
> 
> Path also makes sense although one could confuse it for a file path.

I'll look into it then. In the meantime I'll leave this open, but I'll probably open another PR once that's done.

**Comment by SekoiaTree** [comment]
Superseded by #536

**Pull request closed without merging**
