### PR TITLE
[WIP] Make ref use supplment of target element automatically

### PR DESCRIPTION
**Pull request by 7sDream**
> Image and words here just reflects the original idea, and the design is slightly different now, please read the subsequent discussion to learn about the latest developments.

图片

As thee screenshot shows, this PR adds two features:
1. When the ref function refers to a element, if the element has a custom supplement, it will be used automatically
2. Added a supplement parameter to the figure function, as a example implementation of feature 1

But in terms of implementation details, in order to make it easier to add similar functions to other elements (such as tables, equations, etc.), I added a `RefSupplement` trait. If the element referenced by ref supports this capability, use the content returned by this trait as a supplement. 

Because I haven't read typst's code carefully, I'm not sure whether such a design/naming is reasonable, so I mark this PR WIP. But I believe the functional part is done and readly for test and discuss.

### CODE REVIEW

**Comment by 7sDream** [comment]
图片

Equation example.

And I found the logic is almost the same for most element, so I move it to trait function's default impl.

**Comment by teenjuna** [comment]
Hey! How does it differ from #198?

**Comment by teenjuna** [comment]
I see, your implementation is more generic. That's good. Do you have an idea RE how to differentiate counting between figures with different supplements?

**Comment by 7sDream** [comment]
> How does it differ from #198?

I do not realize we have #198 when try impl this, I'll say the goals that these two jobs want to achieve are indeed quite similar, but, as you mentiond, the implementation details are slightly different.

>  Do you have an idea RE how to differentiate counting between figures with different supplements?

I think this parameter is only used to modify the text and should not affect numbring.

If we need to support multiple numbrings, maybe add a new "category" parameter? Or allow users to pass in a custom counter?

There are also some developers discussing similar issues on Discord, but we do not have a clear approach for now.

**Comment by laurmaedje** [comment]
I've posted some thoughts on this in Discord: https://discord.com/channels/1054443721975922748/1088371867913572452/1089080843374428230

**Comment by teenjuna** [comment]
If your intention is to implement supplement (the name should be indeed change 😅) for different elements, I'm happy to close my PR  since yours is more generic. When it gets merged, I'll just add the option to change separator.

RE Discord discussion, I’ve read it. The proposal with callback is nice. However, it might be too verbose. I tried to add a counter option when worked on my PR, but it turned out to be a bit more difficult, since elements are counted by the element type itself. Perhaps I just haven't figure it out

**Comment by teenjuna** [comment]
Copying some ideas of @laurmaedje from Discord. This PR will be bigger :)

> An alternative would be a new caption element that can be shown in various ways, also depending on whether it is in a figure or somewhere else. The caption argument on the figure would take either such a caption or wrap content that isn't a caption element yet into it. The caption argument could have properties for the prefix/supplement/whatever or you could customize it completely with a show rule.
Would also make it easy to place the caption above the body in a figure show rule without constructing it from the scratch.

>  <...> it would rather look like this:
```
#figure(
  table(..),
  caption: [..],
)
```
> And you could completely customize the caption like this:
```
#figure(
  ..,
  caption: caption(supplement: ..)[..],
)
```
> If you set the caption argument to content that is not a caption, it would automatically be wrapped in a caption of the appropriate type based on the content. So that the first example could use separate numbering for tables.

> I think the layout should be defined in the figure's show rule:
```
#show figure: it => stack(
  dir: ltr,
  it.caption,
  it.body,
)
```

RE custom counters:

> <...> this could be provided by a counter argument on the caption. Both supplement (or whatever it is called) and counter could also be functions that get the figure's element to decide based on the content which supplement/counter to take. And the default style would use that to make table numbering separate.

**Comment by teenjuna** [comment]
@7sDream I think you can mark the PR as a draft to further indicate WIP

**Comment by 7sDream** [comment]
Not sure why test failed on numbering, havn't change anything about it.

**Comment by 7sDream** [comment]
You can try this: 

```typst
#set page(width: 120mm, height: auto)
#show heading: set block(below: 1.5em)

== Figure

#let picCaption = caption.with(
  supplement: [Picture],
  counter: counter("pic"),
  sep: [ -- ]
)

#figure(
  image("avatar.png", width: 20%),
  caption: [with Default label]
) <fig1>

#figure(
  image("avatar.png", width: 20%),
  caption: picCaption[With lable "Picture" and independent counter]
) <pic1>

#figure(
  image("avatar.png", width: 20%),
  caption: picCaption[Second Picture],
) <pic2>

#figure(
  image("avatar.png", width: 20%),
  caption: [Back to default label]
) <fig2>

@pic1, @pic2, this use supplement set by caption automatically.
@fig1, @fig2, default works too.

== Equation

#let equation = math.equation.with(
  block: true, numbering: "(1)", 
)

#let formula = math.equation.with(
  block: true, numbering: "(I)", 
  supplement: [Formula], counter: counter("formula")
)

#equation[$ 1 + 1 = 2 $] <one>
#equation[$ 2 + 2 = 4 $] <two>
#formula[$ E = m c^2 $] <mass-energy>
#equation[$ 3 + 3 = 6 $] <three>

@one, @two[equation], @three[equation] are using default equation counter.

And @mass-energy is Einstein's mass-energy formula, with custom counter.
```

<details>
<summary>And the result is:</summary>


</details>

**Comment by 7sDream** [comment]
@teenjuna @laurmaedje 

I think most of what we discussed is implemented.

But with one exception, the caption itself can't be converted into content directlly. Because the numbering style and default supplement for it is not avaliable. so the example above:

```typst
#show figure: it => stack(
  dir: ltr,
  it.caption,
  it.body,
)
```

is not possible, or can't be that easy for now.

But you can use `it.caption.at("content")` if you just want the caption content, without supplement, number and sep.

That's why I changed the `tests/typ/meta/query.typ` test file.

**Comment by teenjuna** [comment]
Fast progress! Thanks, @7sDream. RE the issue: seems like the time for Laurenz's help has come :)

**Comment by 7sDream** [comment]
About this update: 

## Description

I notice that supplement can be a function and I decide add a second parameter to it.

The second parameter will be the origin/standard/default supplement, so user can change supplement based on referenced element and if they do not want change it, they can just return standard supplement.

## Code

A example:

```typst
#set page(width: 120mm)
#set heading(numbering: "A.")

#set ref(supplement: (elem, orig) => {
    if elem.func() == heading {
        [Appendix]
    } else {
        orig
    }
})

= Good <good>

#figure(caption: caption(supplement: [Table])[balala])[
    #table(columns: 3, ..range(6).map(str))
] <fig>

@good is when you reference to section.

@fig is using the default/original supplement.
```

## Rendered

图片

**Comment by teenjuna** [comment]
Looks good!

Btw, I was thinking, with this PR counting logic gets split. Sometimes it's done by `impl Count`, sometimes by `impl ReferenceInfo`. Right? Maybe we can make it more clean by changing the behaviour of `trait Count` itself? So that there's a way to provide a custom counter to it.

**Comment by 7sDream** [comment]
I want to do this too, but I can't make it work last time when I try to make it, I can't remember why clearly.

Maybe try it again tomorrow!

**Comment by teenjuna** [comment]
I wanted to try this myself, but unfortunately have almost no time for the next couple of days :(

**Comment by Dherse** [comment]
Are there any plans to also allow this to support different numbering based on the supplement? i.e `Table`, `Figure` and `Code` all have different indices starting at 1 for each category?

**Comment by teenjuna** [comment]
@Dherse see this https://github.com/typst/typst/pull/283#issuecomment-1483762063

**Comment by 7sDream** [comment]
> If you set the caption argument to content that is not a caption, it would automatically be wrapped in a caption of the appropriate type based on the content. So that the first example could use separate numbering for tables.

Oh, this is not implemented for now too.

Basiclly because:

- Table do not have a internal counter currently. Maybe it is designed to be placed in a figure, and let the figure to do the counting and reference related thing for it.
-  The body of figure can just be any content, e.g., a `stack(dir: ltr, table(...), table(...))` to put two table in one figure. In this case should the counter be `counter("table")`? or fallback to figure's internal counter? How about a `stack(table(...), math.equation(...))` then?

So now I choose to make this API simpler, if it is not set, use figure's counter.

and if one needs to use the independant counter for table in figure: 

```typst
#set page(width: 100mm, height: 100mm)

#let tableCaption = caption.with(supplement: [Table], counter: counter("table"))
#let tableFig = (content, caption: "") => figure(content, caption: tableCaption(caption))

#figure(caption: "a normal figure")[some words] <fig>

#tableFig(caption: "a table")[#table(columns: 3, ..range(6).map(str))] <table>

@fig, @table.
```

image

Like many examples in previous comments.

**Comment by 7sDream** [comment]
BTW, just read jgm/pandoc#8713, I think `prefix`, `suffix` maybe good alternative names for `supplement` and `sep` in figure catpion.

But other countable thing, like `math.equation`, which has no caption content, `prefix` seem not make sense through.

**Comment by teenjuna** [comment]
I think falling back to the generic figure counter is right. We probably only want to opt out of this for specific things, like images, tables, listings. And if a someone wants to put two images in one row, he will use grid with figures, not figure of grid (that is, if he wants different captions for images).

RE prefix/suffix: my first thought is against of it, but I actually think that when most of the features in this PR are implemented, we should create a list of different naming variants and do a vote

**Comment by ararunaufc** [comment]
> BTW, I just read [jgm/pandoc#8713](https://github.com/jgm/pandoc/issues/8713), and think `prefix`, `suffix` maybe good alternative names for `supplement` and `sep` in figure catpion.

Maybe `suffix` could mislead users to think it will appear _after_ the caption's content...?

Why not rename `sep` to `glue` or `gutter`[^gutter]?

---
[^gutter]: I propose this one because I intend to later suggest to change all existing gutters to be any content instead of just spacing. That could allow us to, for instance, customize column dividers or table lines. If that lands, this case would become an instance of the same situation.

**Comment by teenjuna** [comment]
My opinion: I think sep is way more clear for now. If your future proposal will be accepted, we can return to it.

**Comment by laurmaedje** [comment]
I'm gonna close this as #491 has been merged.

**Pull request closed without merging**
