### PR TITLE
Let let-binding raise error on unexpected keywords

### LINKED ISSUE #4027: Confusing error `expected pattern, found...` in let-bindings
### Description

Since release 0.11, `context` is a new reserved keyword, but if an unwitting user wants to define a variable named `context`, the error message is confusing:
```typst
#let context = 1 + 2
// actual error: 1:6-1:13 expected pattern, found `context` expression
// I suggest:    1:6-1:13 expected identifier name, found keyword `context`
```

---

Similar but different, because the error highlighted the entire `let = 1 + 2` part, not just the second `let` word:
```typst
#let let = 1 + 2
// actual error: 1:6-1:17 expected pattern, found `let` expression
// I suggest:    1:6-1:9 expected identifier name, found keyword `let`
```
Note the highlighted span (1:6-1:17) `let = 1 + 2` is actually not a valid "`let` expression" either -- it's missing the identifier.

---

Okay-ish because it says `as` is a keyword and there's an hint, but the word "pattern" here is still confusing to users. Note it does not refer to Typst's [`pattern` type](https://typst.app/docs/reference/visualize/pattern/).
```typst
#let as = 1 + 2
// actual output:
// Error: 1:6-1:8 expected pattern, found keyword `as`
// Hint: 1:6-1:8 keyword `as` is not allowed as an identifier; try `as_` instead
```
---

Typst thrives on clear error messages (much clearer than LaTeX :) ), so I think it's worth improvement in these cases.

### Reproduction URL

_No response_

### Operating system

Web app, Windows, Linux, macOS

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by Leedehai**
Fixes #4027.

### CODE REVIEW

**Comment by Leedehai** [comment]
The current patch is an improvement over the status quo. Though it's even better to replace `pattern` with `identifier` in the error messages, I suggest doing it in a later patch because it involves different changes.

**Comment by wrzian** [comment]
I like that 'pattern' is more general, bit we should care for legibility in the common case and users who don't know what pattern syntax is. I'd argue for changing to "expected pattern *or* identifier".

**Comment by PgBiel** [comment]
> I'd argue for changing to "expected pattern _or_ identifier".

SGTM.

**Comment by Leedehai** [comment]
As discussed in Discord, let's do the rewording (or not) of `pattern` in a later PR.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
