### PR TITLE
Use/allow U+2212 MINUS SIGN instead of U+002D HYPHEN MINUS everywhere

### LINKED ISSUE #1762: Minus sign rendered differently when using numbers from variables in math mode
### Description

When rendering a negative number in math mode using Typst 0.6.0

```
$-2.5$
```
**Output:**
direct

the minus sign looks different to the same code when using a variable:
```
#let x = -2.5
$#x$
```
**Output:**
varibale

### Reproduction URL

_No response_

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by MDLC01**
This PR is the second take of  #1822.

Fixes #1762.

A U+2212 MINUS SIGN is now used:
- when displayed any numeric value,
- in the [`repr`] of any numeric value,
- to replace a U+002D HYPHEN MINUS in text mode, when before a digit,[^1] but not right after a digit.

In code, a U+2212 MINUS SIGN is now allowed in place of a minus sign as the unary negation or binary subtraction operator, and in `-=`. Using a U+002D HYPHEN MINUS in those places is still possible, of course.

It is also possible to use a U+2212 MINUS SIGN as the negative sign in the string argument of an `int` or `float` constructor (e.g., `int("−123")`).

[^1]: According to [`char::is_numeric`].

[`repr`]: https://typst.app/docs/reference/foundations/repr/
[`char::is_numeric`]: https://doc.rust-lang.org/std/primitive.char.html#method.is_numeric

### CODE REVIEW

**Comment by MDLC01** [comment]
Note that the `int` and `float` constructors currently do not handle U+2212 MINUS SIGN properly when passed a `str`.

**Comment by alerque** [comment]
> * to replace a U+002D HYPHEN MINUS in text mode

What about the case of ranges such as "5-6 bananas"? Typographically this should probably be a FIGURE DASH, but replacing the multi-purpose HYPHEN MINUS with the much more specific MINUS SIGN makes it objectively farther from ideal, not closer.

[Dash Punctuation](https://www.compart.com/en/unicode/category/Pd)

**Comment by MDLC01** [comment]
In text mode, if a U+002D HYPHEN MINUS comes right after a digit, it is not converted to a U+2212 MINUS SIGN.[^1]

If you want an en dash here,[^2] you can still use the `--` shorthand:
```typst
2022--2023
```

[^1]: [See this comment for more information.](https://github.com/typst/typst/pull/1822#issuecomment-1660906266)
[^2]: According to [the Wikipedia Dash article](https://en.wikipedia.org/wiki/Dash), an en dash should be used for ranges of numbers, not a figure dash.

**Comment by MDLC01** [comment]
`int` and `float` constructors now allow the use of a U+2212 MINUS SIGN as the negative sign when passed a `str`.

However, this is currently only possible for the initial negative sign. So the exponent of a `float` must use a U+002D HYPHEN MINUS. I am not sure how to fix this issue without memory allocation, or reimplementing float parsing entierly…

**Comment by laurmaedje** [comment]
> I am not sure how to fix this issue without memory allocation, or reimplementing float parsing entierly…

I think consistency might be more important here than performance, also since we can always improve the implementation later. If you do something with `EcoString`, likely there will be no allocation anyway because it's inline if <= 15 bytes.

**Comment by MDLC01** [comment]
I think this is now safe to merge.

**Comment by laurmaedje** [comment]
Thanks for your work and endurance with this! In the end, this change still feels slightly dangerous (we're really living in an ASCII-dominated world ...), but I think it's the right call.

**Pull request merged**
