### PR TITLE
Add symbols for arrows with tilde

### PR DESCRIPTION
**Pull request by jaroeichler**
Implements #3433

### CODE REVIEW

**Comment by laurmaedje** [comment]
There are at least four codepoints with the tilde above (mirrored and not mirrored):

- ⥲ (U+2972)
- ⭇ (U+2B47)
- ⭉ (U+2B49)
- ⭁ (U+2B41)

And then there are also some with tilde below. Naming those is somewhat tricky.

Do you have any sources that this symbol is used for isomorphisms and how common it is?

**Comment by xkevio** [comment]
I think one source is this Wikipedia list, which mentions U+2972: https://en.wikipedia.org/wiki/List_of_mathematical_symbols_by_subject#Morphisms

**Comment by jaroeichler** [comment]
I've looked over several standard texts in algebraic geometry and algebraic number theory. Some variation of an arrow with a tilde is commonly used to denote an isomorphism. I can give you references with pages if you want.

In LaTeX, the typical method is to use `\xrightarrow{\sim}` rather than the Unicode character, likely due to limited adoption of fontspec/unicode-math and awareness of the character ⥲.

I think we only need ⥲ (U+2972) and ⭉ (U+2B49). I haven't encountered an arrow with a tilde below, and reversing the tilde wouldn't align with handwriting.

**Comment by laurmaedje** [comment]
Okay, thanks for the details. I was a bit confused by the fact that they look different/unmatching by default, but that's probably just unfortunate font fallback. In New Computer Modern Math they look matching. Thanks!

**Pull request merged**
