### PR TITLE
Custom heading display funcs

### PR DESCRIPTION
**Pull request by Humandoodlebug**
Makes it possible to customise the display logic of headings.

I was struggling to make some simple customisations of how headings are displayed, both in the document and in the outline. For example, I wanted to add additional separation between the numbering and title of headings. I initially tried adding spaces to the `numbering` parameter, but that causes spaces to be added to the end of references as well, which is not desired. After a few more not-quite-right attempts, I eventually settled on this monstrosity of a show rule:

```typst
#show heading: content => {
    show text: c => {
        // Insert more space between heading numbering and name
        if repr(c).contains(regex("^\[[A-Z\d]+(\.\d+)*\]+$")) {
            box(inset: (right: 2mm, rest: 0mm), c)
        } else {
            c
        }
    }
    content
}
```

...but that feels icky.

Instead, this PR would allow you to override the default display logic with a set rule like this:
```typst
#set heading(
    numbering: "1.1",
    display: (numbering, title) => text(style: "italic", numbering) + h(1em, weak: true) + title,
)
```

...which in this example would give you italic numbering and a full em space before the title.

Additionally, you can customise the appearance of the associated outline entries:
```typst
#set heading(
    outline: (numbering, title) => numbering + h(0.75em, weak: true) + text(style: "italic", title),
)
```

...which in this example would give you plain numbering followed by a 3/4 em space and an italic heading title.

Suggestions and edits welcome - or if there's a better way, I'd love to know! :)

### CODE REVIEW

**Comment by Enivex** [comment]
You can already do something like
```
#set heading(numbering: "1.1")
#show heading: it => [
    #emph(counter(heading).display(it.numbering))
    #h(1em, weak:true)
    #it.body
    #linebreak()
]```

to achieve the same effect.

(Though I think customizing the outline is harder)

**Comment by Humandoodlebug** [comment]
Thank you @Enivex, that does half of what I need. I still feel there needs to be a way of customising the outline entries though. Perhaps not exactly as I've done it here, but right now it feels too rigid.

**Comment by laurmaedje** [comment]
There is an open PR for outline customization: #1423.

**Comment by PgBiel** [comment]
> There is an open PR for outline customization: #1423.

Yep, although I guess the discussion regarding on changing the outlined text for specific headings is valid. This could be used to omit certain symbols or styling from that specific heading's outline, as it could be quite annoying to use show rules with outline entries for that (for comparison, it could also make sense to customize the bookmark text of a heading in a similar way). Might need more bikeshedding still, however.

Despite that, the other option added by this PR - `display:` - should certainly be dropped in favor of `show` rules (as that is their purpose). A separate proposal, however, could be to make it easier to get a heading's displayed numbering (some alias for `numbering(h.numbering, ..counter(heading).at(h.location())`, maybe), but that's a very separate thing.

**Comment by laurmaedje** [comment]
Some sort of short title as LaTeX allows might be useful (especially for figure captions, but maybe for headings, too). That wouldn't be a function you set, but rather an argument you pass when creating the heading though. Regarding the `display` function here: As said before, this is exactly what `show` is made for. :) I would thus close this PR.

**Comment by laurmaedje** [comment]
Relevant other issue: https://github.com/typst/typst/issues/1295

**Pull request closed without merging**
