### PR TITLE
docs: add reference for list of latex math symbols and typst equivalents

### PR DESCRIPTION
**Pull request by tobiasdiez**
I stumbled upon http://mirrors.ctan.org/info/typstfun/typstfun.pdf which I found pretty helpful in migrating from Latex to typst. Hence, I've added it to the docs.
Upstream repo: https://github.com/lvjr/typstfun

### CODE REVIEW

**Comment by Enivex** [comment]
In my opinion it makes more sense to have this information in the symbol list instead https://typst.app/docs/reference/symbols/sym/

**Comment by tobiasdiez** [comment]
I agree, this would be better - but also way more work that I currently cannot invest.

**Comment by Coekjan** [comment]
Not sure if the upstream repo (typstfun) will be actively maintained.

Typst is still young, and currently the symbol names are not very stable (you can see the breaking changes on symbol names since 0.11 in https://github.com/mitex-rs/mitex/issues/165). In the future, if that repo is not synchronized with typst, the document here could be misleading. And I would suggest to maintain the symbol-equivalents document officially by typst team, if it is possible.

**Comment by laurmaedje** [comment]
What's the best list for Unicode <-> LaTeX mapping? Given that, I can add it to the symbol docs page.

**Comment by Enivex** [comment]
> What's the best list for Unicode <-> LaTeX mapping? Given that, I can add it to the symbol docs page.

https://github.com/wspr/unicode-math/blob/master/unicode-math-table.tex

Same list I used for the spreadsheet I created

**Comment by laurmaedje** [comment]
I added the LaTeX names to the symbol list and to the search index.

**Comment by tobiasdiez** [comment]
> I added the LaTeX names to the symbol list and to the search index.

I used it a couple of times last week, and it works really well! Thanks a lot 🚀

**Pull request closed without merging**
