### PR TITLE
Add `sys.target` export targets

### PR DESCRIPTION
**Pull request by tingerrr**
This PR adds a `sys.target`, a string variable containing `pdf`, `svg` or `raster` depending on the export target.

It should be noted that, with this PR in its current stage, compilation is run 3 times per average test on `--extended`. It may be more sensible, but less intuitive to contributors, if we assume a default target of `raster` and then only override the target for those test which have an appropriate annotation.

### TODO
- [ ] allow custom export targets?
- [x] finalize design for CLI interface
- [x] write documentation
- [ ] allow contextual override

Related to #4174, partially resolves it.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Relevant prior art: https://github.com/typst/typst/pull/1904

**Comment by tingerrr** [comment]
I have renamed `--format` on `query` to `--output-format` to avoid the clash with `--format` while maintaining a consistent CLI.

**Comment by tingerrr** [comment]
I've changed the test runner to have three options, one for each export target, running only those that are selected. By default, `--raster` is implied, but when another export target is requested `--raster` no longer is. `--extended` was changed to `--all` to reflect this change in behavior.

The README contains a note explaining that only render tests are compared.

**Comment by laurmaedje** [comment]
As discussed on Discord, we probably need a bit more fine-grained approach (see [here](https://github.com/typst/typst/issues/4174#issuecomment-2165246219)), so I'll close this for the time being.

**Pull request closed without merging**
