### PR TITLE
Fixed text replacements with special letters not working in show rules (via merging in parser)

### PR DESCRIPTION
**Pull request by sitandr**
Fixes the issue that symbols with special meaning for parsing break text blocks, so show rules can't see them as whole (couldn't find issue on Github, but that was discussed several times on Discord).

That PR unites them into one text block with inner text-like nodes, so the output behaves like one node, so both simple rules and `regex` will work for it. It will ignore comments. convert escaped and shorthand symbols into unicode, so they work well to. Spaces go in between text nodes, otherwise they stay intact.

To decide whether to put space-like symbols into text node or outside of it I have to do some simple `parser.nodes` manipulation. That shouldn't bring any problems, though.

Reparsing and incrementality _are touched_ a bit since when editing text all the adjacent text nodes should be reparsed (as it could trigger replacement).

The main limitation of current replacement rules is that they _will not_ notice new lines and higher-level structures, but for plain inline text they should work well now.

### CODE REVIEW

**Comment by laurmaedje** [comment]
I think a better way to fix this issue would be to adapt the matching instead of the parsing code such that it can deal with multiple successive text nodes. Then it would also match in situations like this:
```
#show "a+b": "hi"
#let s = "+"
a#s;b
```

**Comment by sitandr** [comment]
Maybe. However, I'm not entirely sure.

 - It may be not obvious sometimes why did it suddenly changed. I guess the main use-case of using `regex` with special symbols is to "invent" custom syntax, otherwise scripting is a better choice. 

    Limiting regexps to work only in one "string scope" will make it much more predictable. Especially if they are greedy regexps or others that could suddenly change behaviour after something is added.

- The only obvious problem to me of "my way" is that I will not be able to use any scripting that returns text inside regexp. But again, that doesn't seem like a bad thing to me. One can start argue that if one can do 

```
#show regex("\{.*\}"): set text(blue)

{text #my-function() text}
```

    For text-only function, then they should be able to do it for `box`es, `block`s and so on.

    So I generally like the current idea `one text entry -> one place to replace regexps`, that means no matching between paragraphs, new lines or scripting.

- I think that could lead us to opening a Pandora box of `show` rules for combinations of content. It is basically that, but very limited, so I don't think it will be consistent with rest of Typst. When (and if) we get to things like `#show box(equation(...)) + block(...): ...`, it will be totally okay. But I'm not sure about now.

- I don't know how to do that efficiently and in a good way. I don't think summing every text node during every replacement is okay. Maybe it could be something like collapsing during layout, but it is either not clear to me.

- I don't think better parsing will hurt anyway. I decided to try doing that PR since splitting text into several blocks inside a syntax tree only because of few special symbols seemed a bit disgusting to me.

These points may be not very convincing or clear, so maybe it could still be a good idea to manage it _after_ the parsing. But I'm afraid I'm personally will not be able to do it it soon.

**Comment by laurmaedje** [comment]
> I think that could lead us to opening a Pandora box of show rules for combinations of content. It is basically that, but very limited, so I don't think it will be consistent with rest of Typst. When (and if) we get to things like #show box(equation(...)) + block(...): ..., it will be totally okay. But I'm not sure about now.

Perhaps it is indeed Panodra's box. But I wouldn't call it _inconsistent_ with Typst. That `show box(equation(...)) + block(...): ...` would be consistent, it just isn't implemented (it might or might not be in the future).

**Comment by laurmaedje** [comment]
I'm closing this and #2039 for now. I will try to implement [option 3](https://github.com/typst/typst/pull/2039#issuecomment-1699044421) alongside other styling fixes. If it turns out to be not feasible or problematic, we can reopen this or the other PR.

**Pull request closed without merging**
