### PR TITLE
Simpler example for a regex

### PR DESCRIPTION
**Pull request by KillTheMule**
I stumbled over this, glancing over the documentation as probably other people do, too. Maybe this saves a bit on future opened-and-then-closed issues :)

### CODE REVIEW

**Comment by laurmaedje** [comment]
The split example below feels fairly similar to me. Is the problem maybe more than it's down below and easy to miss?

**Comment by KillTheMule** [comment]
Not sure. For me personally the "problem" was that I assumed that the argument given to `trim` would directly be passed as a regex, but I wasn't sure how to highlight that it's not (other than the fact that it _is_ documented). But I did klick on the `regex` link and subsequently the syntax link, sooo... this might have prevented me opening the issue, is all I'm saying :)

But yeah, maybe the problem was that show rules are kinda complex to begin with, and I was distracted to fast after mentally discarding this example.

**Comment by laurmaedje** [comment]
Hmm okay yeah, that's just to keep it <= 38 chars so that it's a side-by-side example :/

**Comment by KillTheMule** [comment]
Well, using `#"a,b;c".split(regex("[,;]"))` works as well and is shorter than the first example. Should we maybe just change that, and make it the first example?

**Comment by laurmaedje** [comment]
Looks like you pushed something, but it's unchanged.

**Comment by KillTheMule** [comment]
Git is hard, sorry.

**Comment by laurmaedje** [comment]
No worries. Thanks!

**Pull request merged**
