### PR TITLE
Detect unknown vars and illegal assignments in closures early

### LINKED ISSUE #316: Early detection of mutability violation?
Currently the following code

```
#let b = 1

#let f() = (b = 2)

#f()
```

gives the error

```
error: variables from outside the function are read-only and cannot be modified
   ┌─ a.typ:11:12
   │
11 │ #let f() = (b = 2)
   │             ^
```

but the error is only raised when `#f()` is used (if it's not used the error will went undetected), while it makes more sense to raise the error immediately when `f()` is defined.

### PR DESCRIPTION
**Pull request by bluebear94**
Fixes #316.

### CODE REVIEW

**Comment by bluebear94** [comment]
Currently, this code isn’t rejected if `push_purple` isn’t called:

```typst
// Test that calls of mutating methods are counted as mutations.
#let colors = ("red", "green")
#colors.push("blue")

// Error: 22-28 variables from outside the function are read-only and cannot be modified
#let push_purple() = colors.push("purple")
```

Since `push` could be mutating or non-mutating depending on the type of the receiver, though, detecting this in the general case would require evaluating the receiver to find out what type it is. In any case, calling `push_purple` *will* result in an error.

**Comment by bluebear94** [comment]
I think it might be helpful to syntactically distinguish mutating methods from non-mutating ones. Currently, it’s impossible to know whether a method call is mutating until we encounter it and know the type of the receiver. Maybe mutating methods could get a `!` suffix (as inspired by Scheme’s convention of using the same character).

We could generalize this so that `a.foo!(b, c)` desugars to `a = a.foo(b, c)`. In this case, we would want to make non-mutating `push`, `pop`, and so on temporarily unavailable to ease migration.

**Comment by laurmaedje** [comment]
That said, right now the evaluation has the same problem: It doesn't know how to evaluate the receiver (mutable and immutable are different code paths). Therefore it looks at the _method name_ and if it's one of the few mutating ones (e.g. `push`) it enters a mutable context. This is an ugly hack, but hard to fix.

**Comment by laurmaedje** [comment]
How should we move forward here?

**Comment by bluebear94** [comment]
I want to figure out how we’re going to deal with mutating methods before we revisit this.

Personally, I don’t think syntactically distinguishing mutating methods would be too confusing for beginners, at least compared to the status quo. Right now, someone might wonder why `a.push(b)` or `a.pop()` act unlike almost every other method call, while `a.push!(b)` and `a.pop!()` suggest that there’s something special going on. And if someone types the former instead of the latter (or compiles an old file that uses the former syntax), then we can make the error explain that mutating methods need a `!` after the name.

Having a separate syntax for mutating methods also opens up the possibility of allowing users to define these methods (after custom types are implemented).[^1] For example, a package could implement a random number generator type that provides a mutating method that returns the “next” integer and advances the generator state.

The Typst language also already has some unusual concepts relative to popular programming languages, such as joining or introspection, as a result of being a purely functional language for typesetting. So I’m not sure how confusing the `!` suffix will be relative to other features in the language.

I’m an experienced programmer who’s dealt with a variety of languages, but I’m unfamiliar with programming language pedagogy. I’d like to hear opinions from other people in the community as well.

[^1]: As a future possibility, we could also support arbitrary mutable arguments, using a keyword such as `out` both at the declaration and uses. Then `a.push!(b)` where `a` is an array would be syntactic sugar for `array.push(out a, b)`. But if you get the method handle itself, then how would you be able to use it? That is, would you be able to do `let f = array.push; f(out a, b)`? And I’m not sure whether this is worth the conceptual and implementation complexity.

**Comment by laurmaedje** [comment]
> I want to figure out how we’re going to deal with mutating methods before we revisit this.

Sounds good.

> Right now, someone might wonder why a.push(b) or a.pop() act unlike almost every other method call.

I'm not sure people do really wonder that. I agree that separate syntax for this might not be the most complex thing in Typst, but it does add some complexity and I feel like most people don't give push or pop a second thought.

> As a future possibility, we could also support arbitrary mutable arguments, using a keyword such as out both at the declaration and uses.

I've actually proposed something like this on Discord before (with a `mut` keyword). It didn't get too much attention, but the response was mixed overall. I see the benefits, but am myself not sure whether we really need it.

**Comment by PgBiel** [comment]
Regarding the original idea of errors on unknown vars: while that's very useful, I wonder if this could also not hinder backwards compatibility, since we can now check for the typst compiler version in our code (thus, we might have to use code using variables from the standard library which were removed in a later version or something). Perhaps this could be turned into a (in the future, suppressible) warning?

**Comment by laurmaedje** [comment]
Closing this for now. We can reopen if we decide that it makes sense to pursue this further.

**Pull request closed without merging**
