### PR TITLE
Offsetfix

### LINKED ISSUE #1842: Datetime creation function today(offset) incorrect
### Description

The system world does save the datetime of today in a OnceCell once and reuses it. The offset provided to the function is only evaluated in the first run and ignored in all future runs.

### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [ ] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by Beiri22**
fixes #1842 by storing the local datetime object in OnceCell and applying the offset dynamically.

### CODE REVIEW

**Comment by PgBiel** [comment]
Please consider adding some tests :)

**Comment by Beiri22** [comment]
You aren't serious, right? The today()-function is not even implemented properly for the tests-world.

**Comment by PgBiel** [comment]
Well, you could just check if the dates are different when using different offsets.

**Comment by PgBiel** [comment]
Though, I admit such tests could make more sense in a future where the CLI World is better modularized, so it could make sense to leave it for a later PR.

**Comment by Beiri22** [comment]
Previously I had a version with now() and today() and did some manual tests. Including the time, a test was easyier to verify ;-)

**Comment by PgBiel** [comment]
Okay, that's fine. I think that should be enough for now; thanks for clearing it up (my mistake that I hadn't noticed the change only affected the World impl).

**Comment by Beiri22** [comment]
But don't forget: Your web-app may have it's own world - so you may need to fix this overthere, too;

**Comment by laurmaedje** [comment]
Yeah, I'll fix the web app, too. I haven't forgotten about your other PRs, I'll get to them Thursday at the latest! I want to get the web app fixes deployed and then I'll have a bit more time for PR reviews.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
