### PR TITLE
Fences no longer match through linebreaks

### LINKED ISSUE #306: Broken spacing when fences match incorrectly (e.g. through linebreaks)
```typ
#text(20pt)[$
  S &-> a T | b S \
  T &-> a T | b U \
  T &-> a T | b U epsilon 
$]
```
Result: 
image

### PR DESCRIPTION
**Pull request by damaxwell**
Closes #306 

Typst's automatic delimiter matching sometimes leads to surprises.  Consider:
```
$
a &| b\
c &| d
$
```
Currently the `|` fences are matched.  Hence the `|`'s are no longer binary relations, and size changes on one line (e.g. a large operator with limits) cause the delimiter on the other line to change size.  Because fences (and `|` in particular) are not very delimiter-y, and because `|` has overloaded (human) semantics, this category of surprise feels subtle and hard to diagnose.

This PR is a very small change to the parser that disallows fences to match through line breaks.

From the point of view of consistency, it might be better to have a policy "automatic delimiter matching never happens through line breaks".  It's not clear to me that that's the right choice, however. Regardless, this would be a much larger change to the parser.  The issue is that things like
```
$ sum_(a in NN\ a eq.not 17) $
```
should be allowed.  But in the parser implementation, the expression `(a in NN\ a eq.not 17)` starts off life as a delimited thing (so the line break has to be allowed provisionally in delimited things) and then gets stripped of that status later via `math_unparen`.  Similarly `(a\ b)/ C` needs to allow the linebreak temporarily and then either keep it upon discovering the `/` or undo it at a later time if it turned out to be illegal.  Finding the right spot/mechanism for the undoing seems tricky.  I have a couple of thoughts on how this could be achieved if it were desired, but I thought I'd offer this straightforward PR up first as a trial balloon.

## Before
image

## After
image

### CODE REVIEW

**Comment by sitandr** [comment]
I agree that `|` is more intuitive if not matched by default. But at the same time, I'm not sure the general rule "automatic matching isn't possible through linebreaks" is okay.

It is quite a common thing to write some part of expression on the next line, probably with lots of closing braces. Using `lr` for each makes it feel like latex with `\left` and `\right`.

I think it could be better idea to match only _obviously paired_ delimiters through linebreaks, like `[` + `]` and, of course, `(` + `)`.  Then probably there will not be any large changes to parser and it will be quite consistent. However, I'm not sure whether there are common usecases that will notably suffer from that kind of change.

**Comment by damaxwell** [comment]
Yeah, matching [ ] or () through a line break in the real world is definitely a thing for large expressions.  Given that's a desired use case, I'm not sure it would be worth it to do anything beyond what this PR provides -- I think that outlawing [ *** ) through a line break would still be a nontrivial thing to implement.  "Fences don't match through line breaks" has the merit of being a simple principle to explain (and implement!).

**Comment by laurmaedje** [comment]
Hmm. Maybe @sitandr is right and the best way forward is to not auto-match fences at all... I'm not at odds with the rule proposed in this PR, but the example `a | b \ c | d` could just as well have been `a | b, c | d` and then the rule doesn't help.

**Comment by laurmaedje** [comment]
Moreover, there's `abs`, `norm`, etc. which are good, semantic alternatives.

**Comment by damaxwell** [comment]
Not matching fences at all sounds good to me if you all are comfortable with that.  There are only a few unicode fences: single, double and triple bars, and then some colon/dot/zig-zag fences.  It looks like New Computer Modern Math has vertical extensions for single and double bars but not triple; go figure.

So, to-do:

a) Remove matching for fences. But leave the shorthand for `||` in place.
b) Add `abs`, which introduces a left-right group delimited by single bars.
c) Add `norm` which introduces a left-right group delimited by double bars.  This isn't universal notation; many authors use single bars for norms as well.  But it's a fine name, and a person can introduce their own function if they want.

Three-barred norms are rare but I've seen them in the wild.  To get them, you'd have to build them yourself.

Ok?

**Comment by laurmaedje** [comment]
abs and friends already exist! https://typst.app/docs/reference/math/lr/

**Comment by laurmaedje** [comment]
otherwise sounds good although we should get some more feedback from discord perhaps

**Comment by damaxwell** [comment]
> abs and friends already exist! https://typst.app/docs/reference/math/lr/

Well, isn't that handy.

**Comment by laurmaedje** [comment]
I think we're okay to proceed. @Enivex was in favor and no one expressed concern.

**Comment by laurmaedje** [comment]
I've implemented this now: https://github.com/typst/typst/commit/fe402759c03eb93cefc2879e751b8e732891bd3e

**Pull request closed without merging**
