### PR TITLE
Disable justification in `raw(block: true, ...)`

### PR DESCRIPTION
**Pull request by Dherse**
Fixes an issue that has been flagged in codly: https://github.com/Dherse/codly/issues/26

Currently only for block raw blocks, but it's trivial to make the change more generic.

### CODE REVIEW

**Comment by Dherse** [comment]
Actually, before just updating the test, I'll wait for feedback from @laurmaedje cause the test failing doesn't make much sense to me: I see that in the new version it actually includes a linebreak -- which to me seems correct -- but I could see the argument that the old one was better.  I don't really understand why justification allows it to go past the block size...

So @laurmaedje I trust your judgement on this.

image

**Comment by laurmaedje** [comment]
Minimal reproduction:

```rust
#set par(justify: true) // toggle this
#rect(width: 2.4cm)[
  #"    AAAAAAAA"
]
```

Seems like justification affects how leading spaces are handled.

**Comment by Dherse** [comment]
So this is actually a bug in Typst? 🤔

**Comment by laurmaedje** [comment]
I'd say yes.

**Comment by laurmaedje** [comment]
I opened https://github.com/typst/typst/issues/5348 for the bug. 

The new image is fine in principle, but it breaks the intent of the test. The test comes from https://github.com/typst/typst/pull/3796, which disables shrinking (justification where spaces go below their normal size instead of above) in raw blocks. But that's kinda pointless when justification is disabled anyway.

@elegaanz Do you think we should keep the non-shrink handling? I think it would only come into play when someone write `show raw.where(block: true): set par(justify: true)`, which is a very odd thing to write. I can't remember the motivation for disabling shrinking specifically instead of just disabling justification for raw blocks.

**Comment by laurmaedje** [comment]
I would lean towards removing the shrink thing then. Raw blocks do not really seem like the right solution to pseudo-code to me.

**Comment by laurmaedje** [comment]
Notably, this doesn't fix https://github.com/typst/typst/issues/3454 because that's about _inline_ raw blocks. I edited the original PR description to unlink the issue.

**Pull request merged**
