### PR TITLE
Initial `Content` rework

### PR DESCRIPTION
**Pull request by Dherse**
As discussed #712 and #765, `Content` needs some improvements, this initial improvement changes the functioning of `Attr` into a Dynamically Sized Type (DST) that starts with a header with common properties that the vast majority of elements share, followed by a dynamically sized array of addition "tail" items. These items are the fields of the element, the children (if it is a `SequenceElem`) and the style guard.

The modification does not change the size of `Content` since all of its attributes remain heap allocated. However, it has a positive improvement on performance of 6% on my machine (top of the line desktop PC) and 3% on @dccsillag's machine (fairly good laptop). It has been tested for memory leaks and memory issues using both Valgrind, Miri and sanitize modes. Therefore I am confident that the implementation is correct, although not proven.

I look forward to reading your comments,

Dherse

### CODE REVIEW

**Comment by dccsillag** [comment]
Can't say I'm fond of adding _even more_ unsafe code to Typst. With this PR we get **37** uses of `unsafe` just in the compiler (i.e., excluding `ecow` and `comemo`)!

And most worryingly -- all this use of `unsafe` has gone through very little verification work. Just trying out on a few test cases (even if in MIRI/valgrind) + writing a few unit tests **is not enough**.

It's also worth keeping in mind that the safety of stuff inside `unsafe` *can be broken by editing only code outside of `unsafe`*. So it's not encapsulated at all.

Furthermore, I would be somewhat willing to accept `unsafe` if we had data to back it up (e.g., coming from a benchmark suite), but we do not have that. Overall this just seems like a lot of premature of optimization.

**Comment by Dherse** [comment]
> Can't say I'm fond of adding _even more_ unsafe code to Typst. With this PR we get **37** uses of `unsafe` just in the compiler (i.e., excluding `ecow` and `comemo`)!

It was discussed with @laurmaedje that `Content`'s size should remain small so that `Value`'s size also stays small. I am not sure that this premise is required. As long as the struct stays small enough to not have negative impacts on performance then it should be okay. In my, albeit limited, benchmarking, adding data directly to `Content` and not through a `Arc`/`Vec` hybrid chimera worked about as well giving similar performance improvements while requiring no `unsafe` code.

**Comment by astrale-sharp** [comment]
If I understand correctly, this is not (only) about performance, but also about simplifying aspects of the code? Would you correct me or elaborate @Dherse ?

**Comment by Dherse** [comment]
> If I understand correctly, this is not (only) about performance, but also about simplifying aspects of the code? Would you correct me or elaborate @Dherse ?

The goal is indeed to simplify the way `Content` works and make it a bit clearer than the current system. And in the future, with fully realized styling it will get a slight rework where it becomes even simpler (the fields `location`, `styles` and `prepared` will be put into an `Option<ContentMetadata>` or something like that since they will be produced at the same time.

And I think it's important to mention that this simplification has already found a bug: if you look into the old code for `Content`, there is a function called `set_location`, all it does is append an `Attr::Location` to the list of attributes. But if you look at the getter for `location`, you will see that it takes the first `Attr::Location` that is found in the collection of attributes. This is sneakily ignoring all subsequent writes to `set_location`. And while in general, locations should not get overwritten, in practice, `CiteElem` produced by `RefElem`s do get their location overwritten due to strange interactions. This means that in my initial work, where I was just setting the location, bibliographies were broken.

This is a symptom of having complex data structures with undocumented side effects. While this new data structure has a lot of unsafe, which imo is not a very good design decision, it fits the bill of what is required: it simplifies `Content` in the way it works, but leaves its API unchanged keeping this PR small, it requires a single allocation for both the metadata and the dynamically sized properties, it keeps the size of `Content` small and finally, it makes it clearer and easier to understand the side effects of function calls which could lead to unexpected behaviour when "fixed".

**Comment by laurmaedje** [comment]
There will be some kind of content rework in the future, but it's not yet clear in which shape or form. As such, I'm going to close this.

**Pull request closed without merging**
