### PR TITLE
Add `keys` and `dict` methods to `content`

### LINKED ISSUE #310: Traversing through fields of an object?
As in the title. So it's possible to programmatically walk through the tree of content etc..

I think this is a natural extension of `.has(string)` and `.at(string)`.

Python has `vars()` for this purpose, for comparison.

------

Actually given `.func()` exist it is already possible to just do a huge switch-case.

### PR DESCRIPTION
**Pull request by MDLC01**
Fixes #310

Maybe `fields` would be a better name for `keys`.

Also, the formatter seems to reorder `use` statements. I don't know if this is intended or if it is an issue on my end.

*This is my first pull request, I hope everything is right.*

### CODE REVIEW

**Comment by PgBiel** [comment]
I think `fields` would be more coherent than `keys`. Just not sure about `dict` - seems appropriate, but also seems like it could be more descriptive.

**Comment by PgBiel** [comment]
Also, please add unit tests somewhere in `tests/typ`. (E.g. in `methods.typ`)

**Comment by PgBiel** [comment]
> Also, the formatter seems to reorder `use` statements. I don't know if this is intended or if it is an issue on my end.

It's intended, don't worry (they are usually kept in alphabetical order, or similar). :+1: 

Thanks for the PR!

**Comment by MDLC01** [comment]
`dict` is inspired from Python's `__dict__`.

> Also, please add unit tests somewhere in `tests/typ`. (E.g. in `methods.typ`)

I don't really know if I can write a unit test that won't break when the fields of a function are changed in the future, which is why I did not do it initially.

> And take a look at clippy ;)

Yeah I forgot to run clippy locally, I'm fixing that right now.

**Comment by PgBiel** [comment]
> `dict` is inspired from Python's `__dict__`.

I see. I guess it should be fine then, but Laurenz should have the final say here.

> I don't really know if I can write a unit test that won't break when the fields of a function are changed in the future, which is why I did not do it initially.

Don't worry about that; if that ever happens, the tests would simply be updated.
For a safe bet, you can go for more fundamental content types, such as `sequence`. That is, you might wish to test for the fields of something like `[a]`.

> Yeah I forgot to run clippy locally, I'm fixing that right now.

No problem! :+1:

**Comment by PgBiel** [comment]
So, it seems that the `use` reordering actually might be a mistake, are you running `cargo fmt`? It doesn't seem to be doing that over here, weirdly

**Comment by MDLC01** [comment]
Apparently I had a setting in my editor that reorders imports automatically. This change was not due to rustfmt.

**Comment by laurmaedje** [comment]
I think I would prefer to remove the `fields`/`keys` function from this PR and rename `dict` to `fields`. The removed method is just `element.fields().keys()` after all.

**Comment by MDLC01** [comment]
Done!

There is now a single new method on `content`: `fields`, which returns a dict of fields.

**Pull request merged**
