### PR TITLE
Add `wide` spacing for math

### LINKED ISSUE #2223: Add double quad spacing in math
### Description

qquad = quad quad

### Use Case

For math this is extremely common (one quad is often not enough spacing) and quad quad is quite verbose.

### PR DESCRIPTION
**Pull request by DVDTSB**
fix #2223

### CODE REVIEW

**Comment by DVDTSB** [comment]
im slowly descending into madness

**Comment by DVDTSB** [comment]
sadly this only works in math mode i think :(

**Comment by istudyatuni** [comment]
```typ
#sym.qquad
```

**Comment by DVDTSB** [comment]
> ```typ
> #sym.qquad
> ```

what is that supposed to mean @istudyatuni ?

**Comment by istudyatuni** [comment]
> but qquad is not a symbol currently

Ehy it's not a symbol if you added it?

**Comment by Enivex** [comment]
> > but qquad is not a symbol currently
> 
> Why it's not a symbol if you added it?

The other math spaces aren't symbols either

**Comment by laurmaedje** [comment]
I'm really not a fan of the name. Having double letters at the start to make something more or different is typical for LaTeX, but not really a thing in Typst.

> sadly this only works in math mode i think :(

`#math.qquad` would also work in normal code since it's functionality equivalent to `#h(2em)`

**Comment by DVDTSB** [comment]
> I'm really not a fan of the name. Having double letters at the start to make something more or different is typical for LaTeX, but not really a thing in Typst.

I somewhat agree, however I still like `qquad` because of its simplicity. Any other ideas?

**Comment by DVDTSB** [comment]
on the discord we decided to either use `gap`, `sep` or `wide`.
`wide` is the preffered one from what I have seen.

**Comment by Enivex** [comment]
> I'm really not a fan of the name. Having double letters at the start to make something more or different is typical for LaTeX, but not really a thing in Typst.

Double capital letters for blackboard bold? ;)

**Comment by laurmaedje** [comment]
That's different because it actually resembles the double-struck output.

I would be fine with `wide`.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
