### PR TITLE
Add `Repr` trait

### PR DESCRIPTION
**Pull request by MDLC01**
<i>The original version of this PR did not implement the right thing. See edit history for original description.</i>

---

This PR adds [the `Repr` trait that was mentionned in this comment](https://github.com/typst/typst/pull/1822#issuecomment-1689881897).

## Description

The `Repr` trait describes how a value is converted to a string using the [`repr`] function.

## Open questions & problems

- Should `Repr` use a `Display`-like mutable buffer instead of returning an `EcoString`?
  - Multiple types have a `repr` that involves calling nested `repr`s, which would be more efficient if done that way.
- ~Should old `Debug` implementations be replaced with `#[derive(Debug)]`, which makes more sense as `Debug` will now be used only to represent Rust values?~
- Some `repr`s always return `".."` instead of something useful that would at least be indicative of the type:
  - `CounterUpdate`,
  - `Location`,
  - `StateUpdate`,
  - `Styles`.
- Some `repr`s use `Debug` instead of a custom value (because `Debug` is derived, so there never was a proper representation):
  - `Decoration`,
  - `Destination`,
  - `Meta` (`Debug` is not derived here, but it was never meant to be shown to the user),
  - `PdfPageLabel`,
  - `Stroke`.

## Changes

There are some types whose `repr` changes with this PR.
- The `repr` for `Symbol` now returns the quotted symbol, whereas it used to return the symbol only.
  - Another option would be to return the symbol in brackets (or keep it the way it was before, although it did not make much sense in my opinion).
- Components for colors stored as OKLab no longer have 3 figures after the decimal point (e.i., trailing zeros are trimmed).

## Tests

I did not add any test, as I'm not really sure what to test. After all, the specific `repr` of a value does not matter, as long as it accurately represents it. I can, of course, add tests, if necessary.

[`repr`]: https://typst.app/docs/reference/foundations/repr/

### CODE REVIEW

**Comment by laurmaedje** [comment]
The idea was to have this function backed by the new `Repr` trait instead of `Debug`:

https://github.com/typst/typst/blob/0198429e63d288b992624b0fb615fc5af5aa6cb6/crates/typst/src/eval/value.rs#L190-L193

For that to work, `Value` would need to implement `Repr`, all of its variants would need to implement `Repr` and `Dynamic` would need to be bounded on `Repr` instead of (or in addition to) `Debug`. That's quite a bit of work, hence my comment that it might be too complicated for the other PR to incorporate.

Fundamentally, `Repr` should define the output of the `repr(..)` function in Typst. Right now, it's all shoe-horned into the `Debug` impls, which makes them strange from a Rust-facing perspective. Basically: `Value::display / Show` is the equivalent to `Display` and `Value::repr / Repr` is the equivalent to `Debug`.

This means that for `Str` it should render quotes and the escape sequences the Typst supports for strings, for arrays the adequate array literal, etc. In particular, this means that `Value::display` for `Value::Str` shouldn't use repr because it should not add quotes or add escape sequences.

PS: There are quite a few private `struct Repr` in the codebase as you have seen with Symbol. That's a bit of an unfortunate collision, but I would prefer for them to keep their name. The Repr impl can still be added with `impl crate::eval::Repr for ..`.

**Comment by MDLC01** [comment]
Oh, right. I indeed misunderstood what the purpose of this trait was.

After working on it, I can confirm that it makes perfect sense to have this in a separate PR.

I've modified the original comment to describe the new changes.

**Comment by laurmaedje** [comment]
Looks good overall! The main comment I have is that now that we have `Repr`, a lot of previous `Debug` impls could be turned into derives or some stuff like `Array` could use Rust's typical `f.debug_list()` thing. That way, `Repr` returns the Typst-like representation and `Debug` the Rust-like one and we have less duplication.

**Comment by MDLC01** [comment]
I have removed custom `Debug` implementations and replaced them with `#[derive(Debug)]` when appropriate.

**Comment by laurmaedje** [comment]
Thanks a lot for taking care of this!

**Pull request merged**
