### PR TITLE
Fix luma → cmyk conversion

### PR DESCRIPTION
**Pull request by frozolotl**
Previously, the luma → cmyk conversion produced incorrect results.
This new conversion matches the values gained from luma → rgba → cmyk.

This PR also fixes a bug where `repr(luma(0%))` printed `rgb(0%, 0%, 0%, 0%)`.

### CODE REVIEW

**Comment by Dherse** [comment]
I think @reknih should check this for sure.

**Comment by reknih** [comment]
Okay, I'm very sorry, I read the diff in reverse. We actually intentionally produce a mix of pigments for grays here such that full black becomes very rich black (sometimes called Photoshop black) instead of dark gray. Most likely, RGB to CMYK conversion should be fixed instead to align with this behavior. More on this here: https://www.bittbox.com/culture/photoshop-101-true-black-cmyk

We removed this commit from main. Sorry for the confusion.

**Comment by frozolotl** [comment]
Oh, that makes sense; I'll probably check later today on how this can be solved without introducing problems like these.

**Comment by Dherse** [comment]
> Okay, I'm very sorry, I read the diff in reverse. We actually intentionally produce a mix of pigments for grays here such that full black becomes very rich black (sometimes called Photoshop black) instead of dark gray. 

I knew this code predated #2171 and that there was a good reason for it but I couldn't remember it.

**Pull request merged**
