### PR TITLE
Add npm package manager distribution

### PR DESCRIPTION
**Pull request by jcbhmr**
#### why: make it so that prospective users can just `npx typst` instead of going through complicated install instructions.

while im sure javascript nodejs people are not your primary audience, there are _a lot_ of web-related and web-adjacent developers who may want to try typst and probably find it easier to use `npx typst` as opposed to other install/run methods like Docker or `cargo install`.

i also notice that there's already some other package managers listed in the readme. i think npm could be added to that list:
image

this pr would:
- add an `npm/` folder that has a `package.json` to run a `postinstall` script which will download the corresponding lockstep release (currently 0.10.0) from GitHub Releases
- add a `npm/main.js` file that will correspond to the `npx typst` package default binary. this will download the typst binary if not already (if postinstall script was skipped/disabled) and then run it.
- copy-paste the README.md and LICENSE (unsure if you want any readme changes. the `npm/README.md` file will be displayed at https://www.npmjs.com/package/typst
- add a npm-publish.yml workflow which (you guessed it) runs `npm publish` on **manual dispatch**. unsure if you want to add an automagic trigger or anything.

you can now run this in your terminal to use typst!
```sh
npx typst --help
```
<sup>yes this works! the typst package is published; just not officially.</sup>

this `npx` solution works very similar to other efforts by Deno https://www.npmjs.com/package/deno-bin and Bun https://www.npmjs.com/package/bun.

note: to make the npm-publish.yml workflow work you'll need to add an NPM_TOKEN secret to the repo.

<sub>sidenote: i'd very much like to transfer ownership of the `typst` npm package and `@typst` npm organization to actual @typst members instead of just me (some random guy)</sub>

### CODE REVIEW

**Comment by Enivex** [comment]
> complicated install instructions

Surely this is more complicated than the existing options? I don't understand why typst should be on a package manager for JavaScript

**Comment by alerque** [comment]
This makes it easy to use as a dependency for JS based projects, e.g. one could use it for generating documentation PDFs as part of the build system for a app or make server-side PDF generation an easy to add option for a Node based server package.

**Comment by laurmaedje** [comment]
From what I've read, this does not provide Typst bindings to JS though. Rather, it is a way to install the CLI via npm. Personally, I'm not sure how much sense that makes, but I see how some might find it useful if they don't use another package manager.

However, we don't maintain any of the package manager distributions (brew, etc.) ourselves. The only exceptions of things that live in this repo are the Nix flake and the Dockerfile and I already don't like that to be honest because I have no idea how they work. This is probably not the response you've been looking for, but unfortunately we don't have the bandwidth to maintain such things ourselves.

**Comment by jcbhmr** [comment]
typst npm package is now sourced from https://github.com/typst-community/typst.js for anyone who was interested or stumbles on this pr from google

**Pull request closed without merging**
