### PR TITLE
Move `perp` symbol into correct category

### PR DESCRIPTION
**Pull request by DVDTSB**
i added some symbol alliases.
`neq = eq.not`
`nequiv=equiv.not`
`mid = divides`
`mid.not = divides.not`
`nmid = divides.not`
The first 2 were added because they are already used as naming for other "sub-symbols" like `subset.neq`. The other's just for making things more LaTeX-friendly.

Also moved `perp` from the NT-category to the Geometry category.

Note: I will have to check if everything is consistent.

### CODE REVIEW

**Comment by DVDTSB** [comment]
Turns out it's not actually consistent. `subset.eq.not` and `subset.neq` are slightly different. Same for `supset.eq.not` and `subset.neq`. I didn't modify those two. For everything else I just added an allias.

**Comment by laurmaedje** [comment]
There was a lot of Discussion on [Discord](https://discord.com/channels/1054443721975922748/1104254749139800145/1127536768460263494) and in the recent [symbol PR](https://github.com/typst/typst/pull/1124). Symbol naming always leads to a lot of discussion due to differing personal preferences. Personally, I'm not a fan of the proposed symbol changes. The `.neq` modifier exists because _only_ the eq part of the symbol is cancelled and we do not have nested modifier. I would not want to add a `n..` variant for every symbol that has `.not`.

**Comment by DVDTSB** [comment]
I understand that  Would the moving  `perp` from NT to Geometry part of the pr be alright?

**Comment by laurmaedje** [comment]
That's of course alright. :)

**Comment by DVDTSB** [comment]
i have no idea why it fails formatting :(((((((((((

**Comment by laurmaedje** [comment]
I think it's complaining about the newline at the end of the file which you removed.

**Pull request merged**
