### PR TITLE
Avoid adding blank page with weak pagebreak when page is visually empty

### LINKED ISSUE #1346: weak pagebreak after page counter update always adds pagebreak
### Description

When adding a `pagebreak(weak: true)` after an update of the page counter the pagebreak will always be inserted even if the page is empty.

**To reproduce:**
```
#counter(page).update(1)

#pagebreak(weak: true)
= Page 1

#pagebreak(weak: true)
= Page 2
```

I would expect no pagebreak to be inserted as there is no visible content on the page before the pagebreak.

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by azerupi**
Attempt to fix #1346

This PR seems to fix the problem I have and still pass the tests. I'm absolutely not sure that this has no other side-effects though.

If this looks good and doesn't have side-effects, I should probably add a test for this so that this behavior does not disappear in a future refactoring.

### CODE REVIEW

**Comment by Dherse** [comment]
That's awesome, I had tried my hand at fixing it a couple of weeks ago, didn't think it would be so simple 🎉

**Comment by PgBiel** [comment]
> There are other ignorant items like `place`. This PR might create problem with weak pagebreaks in combination with them.

Perhaps we could have some separate behavior type for content which is not intended to be actually displayed, such as `counter(...).update(...)`?

**Comment by azerupi** [comment]
The elements I found that are marked as ignorant are

- **`h` and `v`**  
  What should happen if we have one or more `h` and `v` without other content on a page followed by a weak pagebreak?
  From my perspective, intuitively it would make sense to not make a new page and remove the spacing. But that might not be consistent behavior.

- **`place`**  
  `place` elements should probably always be show and a weak pagebreak should force a new page? Is it possible to place an element on each page with a show rule? If that is possible we might have someone trying to place an element on each page and having "blank" pages with weak pagebreaks.

- **`meta`**  
  `meta` isn't visible. A weak pagebreak should not create a new page. Right?

**Comment by laurmaedje** [comment]
- h and v: I'm on the fence, but tend to agree with you since they are also collapsed at the end of a page
- place: I agree that it must be retained, on a separate page.
- meta: Should not force a separate page, but must still be carefully retained for introspection to work correctly

**Comment by Beiri22** [comment]
Is there any progress on this discussion / topic? I'm just curious because setting some metadata as state at the document start introduces an empty page. I could avoid finding a workaround if this PR advances.

**Comment by azerupi** [comment]
I'm still looking into it, but haven't had much time. If anyone wants has ideas on how to implement it or help, please do.

**Comment by Beiri22** [comment]
> The elements I found that are marked as ignorant are
> 
> * **`h` and `v`**
>   What should happen if we have one or more `h` and `v` without other content on a page followed by a weak pagebreak?
>   From my perspective, intuitively it would make sense to not make a new page and remove the spacing. But that might not be consistent behavior.
> * **`place`**
>   `place` elements should probably always be show and a weak pagebreak should force a new page? Is it possible to place an element on each page with a show rule? If that is possible we might have someone trying to place an element on each page and having "blank" pages with weak pagebreaks.
> * **`meta`**
>   `meta` isn't visible. A weak pagebreak should not create a new page. Right?

h and v: i would agree as they collapse
place: could be parametrized as weak or not

**Comment by Beiri22** [comment]
> Perhaps we could have some separate behavior type for content which is not intended to be actually displayed

As it is an enum, you could just add a parameter to the Ignorant variant to get `Ignorant(bool)`. `Ignorant(true)` could be an element that does not interact at all with other elements, but beeing visible. `Ignorant(false)` would then be an element that is not even visible. Elements that are definitely invisible like the Counter and State update functions, Metadata element, ... could be set to `Ignorant(false)` without hassle. The elements you are inconclusive about, could stay at `Ignorant(true)`, and may later be changed or parametrized with some named argument to allow the user to change behaviour.

- h and v: `Ignorant(false)`
- place: would be a good candidate to allow the user to choose
- meta and metadata: should be `Ignorant(false)`

**Comment by laurmaedje** [comment]
Superseded by https://github.com/typst/typst/pull/1929 (which is merged now).

**Pull request closed without merging**
