### PR TITLE
Modify sqrt example

### LINKED ISSUE #1992: Sqrt(x^2) is not equal to x
In this example:

https://github.com/typst/typst/blob/a8d3ab3fb0f65f733695ed03a2869726a98cffd7/crates/typst-library/src/math/root.rs#L7

It is stated that `sqrt(x^2) = x` which obviously wrong. the square root of x^2 is the absolute value of x, not x.

Thank you.

### PR DESCRIPTION
**Pull request by owiecc**
Closes #1992

### CODE REVIEW

**Comment by xkevio** [comment]
I would have just added `abs(x)` instead of changing the equation. This would also show additional typesetting features without the need for a different formula.

**Comment by xkevio** [comment]
Maybe, but it's still the focus even with `abs`. One can argue that the `^2` is also distracting (ofc not really) and nested roots are really just nested function calls. But again, mostly bikeshedding on my part, I just assumed that the original issue just wanted to make the existing formula correct ^^

**Comment by laurmaedje** [comment]
Thanks!

**Comment by OpenFoam-User** [comment]
explanation: 

$\sqrt{3 - 2\sqrt{2}} = \sqrt{2 + 1 - 2\sqrt{2}} = \sqrt{(\sqrt{2})^2 -2\sqrt{2} + 1^2} = \sqrt{(\sqrt{2} - 1)^2} = \sqrt{2} - 1$

**Pull request merged**
