### PR TITLE
Added label usage restriction in documentation

### PR DESCRIPTION
**Pull request by Andrew15-5**
Fixes problem in https://github.com/typst/typst/issues/2317#issuecomment-1748538207

### CODE REVIEW

**Comment by laurmaedje** [comment]
The link to `ref` was broken and I also wanted to expand some more on labels, but couldn't push to the PR, so I fixed it on main instead and added you as a co-author: https://github.com/typst/typst/commit/cb7079711a75df0126a8e02f0d6b0620495637ec

**Comment by Andrew15-5** [comment]
> but couldn't push to the PR, so I fixed it on main instead and added you as a co-author: [cb70797](https://github.com/typst/typst/commit/cb7079711a75df0126a8e02f0d6b0620495637ec)

Sure, cool, thanks. But there is a feature called review, which allows to purpose changes. Although writing yourself is (probably) almost always better.

**Comment by Andrew15-5** [comment]
> but couldn't push to the PR, so I fixed it on main instead and added you as a co-author: [cb70797](https://github.com/typst/typst/commit/cb7079711a75df0126a8e02f0d6b0620495637ec)

Sure, cool, thanks. But there is a feature called review, which allows to purpose changes. Although writing yourself is (probably) almost always better.

**Comment by laurmaedje** [comment]
Of course, I just figured it'd be easier to just fix it quickly myself instead of bothering you with it, especially since I also wanted to add some extra text.

**Pull request closed without merging**
