### PR TITLE
Add Atkinson Hyperlegible font

### LINKED ISSUE #666: Include Atkinson Hyperlegible font
See https://brailleinstitute.org/freefont

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Fixes #666

### CODE REVIEW

**Comment by szdytom** [comment]
This will increase the typst binary size! But not everyone need that font.

**Comment by SUPERCILEX** [comment]
Yeah, this was a concern of mine too. It's only ~130kb, so not the end of the world, but I'd be happy to only include this on the website if that's possible.

**Comment by szdytom** [comment]
I think you are right, 130kb is almost nothing for computers nowadays

**Comment by laurmaedje** [comment]
Even if it's only 130kb, it contains precedent for including arbitrary fonts in the binary. The binary already includes the default fonts and a LaTeX-like font and shouldn't include more. I can add the font to the web app.

**Comment by SUPERCILEX** [comment]
Sounds good, thanks!

**Pull request closed without merging**
