### PR TITLE
Use built for build-time information for version

### LINKED ISSUE #150: Unable to build from source archive
I'm attempting to build a Homebrew formula (https://github.com/typst/typst/issues/95) but hitting a problem wherein the cli module's `build.rs` assumes that it's being run from inside a directory with git information. Looking at it, sure enough, it's trying to use `git rev-parse HEAD` to get the latest commit. I tried coding around it to get the basename of the current directory instead, but hit some Rust Result/Option safety stuff that exhausted the very limited time I have right now.

I think the better solution for getting build-time information is to use [`built`](https://docs.rs/built/latest/built/), which generates some code in a module accessible at runtime for things like hash, version, etc.

### PR DESCRIPTION
**Pull request by colindean**
Fixes #150
Closes #154

### CODE REVIEW

**Comment by CGMossa** [comment]
While I'm not really a dependency frightened person, I think adding `built` and especially `git2` to the mix for such a little feature is not really worth it.

It would be better to add something that notes down the commit-id when making tags or releases or something like that, rather than doing this. 

Sorry

**Comment by colindean** [comment]
I pretty firmly disagree. Yes, it's bringing in a bunch of stuff but virtually guaranteed all of that information is going to end up getting used. I didn't put it into the version information output more in the interest of guarding my time than anything else.

**Comment by colindean** [comment]
Nb those are build time dependencies used in build.rs, not shipped with the binary CLI itself.

**Comment by figsoda** [comment]
This PR closes #154, but not only does it not fix the issue, it breaks the workaround.

The original issue could be simply fixed with some bound checking, using `built` brings in impurities and unnecessary dependencies.

**Comment by figsoda** [comment]
> some bound checking,

#173

**Pull request closed without merging**
