### PR TITLE
Add figure separator field

### PR DESCRIPTION
**Pull request by abramchikd**
This PR add figure.separator field as discussed in https://github.com/typst/typst/issues/1303.

The separator if provided replaces colon and space between figure's number and its caption.
For example `#set figure(separator: [ --- ])` will generate em-dashed instead of colons.

This PR will conflict with https://github.com/typst/typst/pull/1704, but the conflict can be easily fixed when either of the PRs is merged

### CODE REVIEW

**Comment by abramchikd** [comment]
@PgBiel @laurmaedje Hey! There is no feedback during two weeks

**Comment by laurmaedje** [comment]
Sorry, I did not yet get to this and #1704. I think this property would make much more sense on figure.caption than on figure itself, so I'd like to wait with this until #1704 is merged.

**Comment by PgBiel** [comment]
I agree something like `#set figure.caption(separator: [---])` would probably make more sense.

**Comment by laurmaedje** [comment]
Thank you!

**Pull request merged**
