### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by RLangendam**
Updated dependencies only with nonbreaking changes.

### CODE REVIEW

**Review by CGMossa — APPROVED** [review]
Changelogs for `miniz_oxide` doesn't mention any substantial breaking change that should be auditted for.

LGTM 🤷‍♂️

**Comment by CGMossa** [comment]
Please note that I'm in no way part of the team. I'm just giving my community member review. It helps other projects, but I could be both factually wrong, and my opinions may be opposite of the typst team.

**Comment by RLangendam** [comment]
So I guess we should only keep the tiny-skia update?

**Comment by laurmaedje** [comment]
We can have the tiny-skia update although from the changelog not too much has changed.

**Pull request merged**
