### PR TITLE
Fix listitems/enumitems not being properly styled

### LINKED ISSUE #619: List item markers excluded of hiding and styling
(Possibly related to https://github.com/typst/typst/issues/520 and https://github.com/typst/typst/pull/587)

Lists (bulleted and enumerated, but not term-lists) seem to not be hiding/styling correctly. More specifically, you can't hide/style  list _items_ directly fully - styling their parent element (`list`) seems to work (which styles/hides _all_ items), but not when the listitem itself is affected (that is, attempting to style just _one_ item), as the list item marker remains unaffected. For example, typing `#hide[- b]` among other elements in the same list will produce a hidden `b`, but the marker stays there. Likewise, `#text(blue)[- b]` only makes the "b" blue, but not the marker. However, `#hide[#list[b]]` will work, as that creates a separate list. (The same applies for enumerated lists, but not for term lists.)

I believe this is due to the fact that the `list` and `enum` types handle all markers by themselves, while term lists let their items handle their own markers (the term labels). I will attempt to elaborate further in another comment below (first, I'll show a reproducible example).

Here's sample typst code to reproduce this issue:

```
ff
#repr[- a]
#repr[#list[a]]

- f
#list["a"]
#hide[#list["a"]]
- #hide[a]
#hide[- a]
- g
#text(blue)[- i]
- h

ff

#hide[+ a]
#text(blue)[+ b]
+ b
+ c
#hide[#enum[d]]
+ e

/ a: b
/ c: d
#hide[/ d: e]
/ f: g
#hide[#terms(([a],[b]))]
/ e: h
```

This will produce (on latest main (at commit 085282c138899dd5aaa06bc6ae7bd2f79d75d7e1)): (notice how markers were unaffected when they were supposed to be, when attempting to hide/style individual items)

image

### PR DESCRIPTION
**Pull request by PgBiel**
Fixes #619.

This PR allows lists and enums to have `Content` as children, such that the `ListItem`/`EnumItem` objects can carry their associated styles. This can be breaking in principle (if any code relied on the output of `repr` for `list`/`enum`), but shouldn't have much of an impact in general.

This is necessary because, otherwise, attempting to style individual items will only affect _their bodies_, but not _their markers_ (/numbers), since the markers are generated by the `list`/`enum` collecting the items at the end (which, thus, can't be otherwise aware of the individual items' styles if they do not hold them), while their bodies are currently styled directly in `ListBuilder` - with this PR, the `ListBuilder` will now simply apply the item's individual styling to its `Content`, allowing the `list` or `enum` to pick it up later using `Content::to_styled`.

With this new approach, the item styles are only applied in `ListElem`/`EnumElem`, in the children loop. Note that styles are only applied if the item is indeed styled, and is indeed a `ListItem`/`EnumItem` (constructed by the shorthand syntax, i.e. `- item` or `+ item`), as, otherwise, the item is simply a generic `Content` representing the item's _body_, and thus its style is not applied to the marker. (This check is also necessary to avoid applying the outer style twice and resulting in duplicated `show` rule executions.)

I've added several tests; feel free to add more. I'm also open to any feedback or suggestions.

### CODE REVIEW

**Comment by laurmaedje** [comment]
It feels a bit inconsistent to me that term lists are excluded from this change. I see why (they work), but maybe they should be handled the same?

**Comment by PgBiel** [comment]
> It feels a bit inconsistent to me that term lists are excluded from this change. I see why (they work), but maybe they should be handled the same?

I believe their case is different - for term lists, it makes sense to restrict children to be `TermItem`, as each term has two components: the term and its description, so it doesn't make sense to allow arbitrary content here (it would be the body, but the body of which term?). The current implementation also handles styles restricted to terms just fine.

We could still move handling of styles to the `terms` children loop, and allow `Content` children for it, though maybe that would make it possible to create a `terms` with invalid children (which would only be caught upon rendering)... Well, not sure if that's a problem or not - if it isn't, then I can do this change just fine.

For now, though, I will add tests for terms as well, as I believe that's also important for consistency.

**Comment by PgBiel** [comment]
Just to complement this, upon my tests (see https://github.com/PgBiel/typst/commit/0630afcb43f55aefbdc5096411368c1b58435e96), simply changing the children field to a vector of `Content` does not work for TermElem. It still requires a separate element type, as you can specify an Array (instead of a Content) as child, for example. So, I don't think there's any easy way to modify the TermElem to conform to the pattern observed for `ListElem` and `EnumElem`.

Unless, of course, we somehow added a `style` field for TermItem. But that's not very elegant at all. Any ideas?

**Comment by laurmaedje** [comment]
> it makes sense to restrict children to be TermItem, as each term has two components

Makes sense, sorry for the oversight on my part!

**Comment by PgBiel** [comment]
> Makes sense, sorry for the oversight on my part!

Oh, please, no worries! We're all working towards a common goal here ;)

**Comment by laurmaedje** [comment]
One more thing that might be a problem with this approach: In a show rule, you should be able to rely on the structure of the children in`#show enum: it => it.children`. With this change they sometimes are list items and sometimes styled. I'm not sure how big of a problem that is, but it's worth consideration. This would of course also be fixed by not implementing styles as a separate element. Maybe the best thing is to merge this for now and deal with that issue as part of the styling rework.

**Comment by PgBiel** [comment]
Hmmm, @laurmaedje I agree this would be a problem. I see three options here:

1. Place this PR on hold until the style rework happens (not sure if that would take too long);
2. Merge the PR anyway (which could break existing code);
3. Maybe instead change this to a feature PR, which lets each item (optionally) customize its marker (or set it to `auto`), thus adding a `marker` content field which can also optionally hold styles (even if marker is set to `auto`, in which case it can become a placeholder `Content` holding styles)? Though this could require more discussion, and thus would place this PR on hold either way.

What's your opinion here? I was leaning towards 1, or maybe 3, but not sure here.

**Comment by laurmaedje** [comment]
The style rework will take a bit of time. I'm fine with either 1 or 3, although 3 would indeed need a bit more discussion.

**Comment by PgBiel** [comment]
Alright, I think we maybe should just place this PR on hold then. Better the status quo than to break things. Eventually we can open an issue to discuss how to proceed here (if number 3 would be viable or not, and stuff like that).

For now, I think I'll just keep the PR as draft then; should make it clear that it shouldn't be merged just yet. (If we don't find a solution soon enough, we could later close it and then open another as needed.)

**Comment by laurmaedje** [comment]
I'm closing this as any solution to the fundamental problem would probably either fix the problem directly or affect so many things that the current PR is full of conflicts and making a new one would be simpler.

**Pull request closed without merging**
