### PR TITLE
Implement euclidean division and remainder

### PR DESCRIPTION
**Pull request by frozolotl**
While the issue #2677 that prompted me to implement these functions has been solved already, Euclidean division and remainder still seem like sensible additions to me.

I'm not sure if I like the documentation, but to me, it appears surprisingly hard to describe these functions in a precise and succinct manner.

### CODE REVIEW

**Comment by Enivex** [comment]
What exactly does this add over quo and rem?

**Comment by Dherse** [comment]
I think the advantage is that this is integer based? Does it make a difference knowing the cost of eval will be higher than that of the float operation(s)?

**Comment by frozolotl** [comment]
> What exactly does this add over quo and rem?

These are different operations:
- `-7 / -3 == 2.(3)`
- `calc.quo(-7, -3) == 2`
- `calc.rem(-7, -3) == -1`
- `calc.div-euclid(-7, -3) == 3`
- `calc.rem-euclid(-7, -3) == 2`

Euclidean division and remainder are used in a few algorithms.
You can see https://en.wikipedia.org/wiki/Euclidean_division for more information on Euclidean division in general.

**Comment by Enivex** [comment]
> > What exactly does this add over quo and rem?
> 
> These are different operations:
> 
>     * `-7 / -3 == 2.(3)`
> 
>     * `calc.quo(-7, -3) == 2`
> 
>     * `calc.rem(-7, -3) == -1`
> 
>     * `calc.div-euclid(-7, -3) == 3`
> 
>     * `calc.rem-euclid(-7, -3) == 2`
> 
> 
> Euclidean division and remainder are used in a few algorithms. You can see https://en.wikipedia.org/wiki/Euclidean_division for more information on Euclidean division in general.

I'm fully aware what the euclidean algorithm is, but the only difference here is that rem will return a negative representative for negative numbers. Having both seems redundant, when it's straight-forward to translate between the two.

**Comment by frozolotl** [comment]
> Having both seems redundant, when it's straight-forward to translate between the two.

While that is true, I think the extra bit of convenience for a relatively common mathematical operation is worth it. I consider it similar to to functions like `min`, `clamp`, or `gcd` in that sense.

**Comment by laurmaedje** [comment]
It's always hard to draw the line what's in and out of scope with things like this (and math text operators). Here's the relevant discussion for Rust as a reference: https://github.com/rust-lang/rfcs/pull/2169

**Comment by laurmaedje** [comment]
Whatever, I don't mind too much either way. Thanks!

**Pull request merged**
