### PR TITLE
Add datetime.from-unix and as-unix

### PR DESCRIPTION
**Pull request by bluebear94**
See #1658.

Unresolved questions:

* Should `from-unix` and `as-unix` always work with datetimes in UTC, or should they be able to specify an offset from UTC?

### CODE REVIEW

**Comment by laurmaedje** [comment]
@LaurenzV any opinion on the unresolved question?

**Comment by lvignoli** [comment]
@bluebear94 I am no expert, but [apparently](https://en.wikipedia.org/wiki/Unix_time) Unix timestamps are implied to count from 1970-01-01T00:00 UTC.
Adding localization to it—even if enabled by the Rust library—may be confusing.
Also, personal opinion, it kinda harms the "definitive" representation that Unix time is.

**Comment by LaurenzV** [comment]
So, a couple of points:

I agree that Unix timestamps probably make most sense by restricting it to just UTC.

Regarding the `as-unix()` method. Actually, displaying a datetime as a unix timestamp is in theory already supported by the `time` crate, i.e. something like `d.display("[unix_timestamp]")` would generally be supported (also see [here](https://time-rs.github.io/book/api/format-description.html) for a complete list of what's possible, I didn't include everything in the documentation because I didn't deem it to be that necessary). However, the problem is that internally we use the `PrimitiveDateTime` type which does _not_ support displaying a date time as a unix timestamp, only the `OffsetDateTime` does, which is basically just a PrimitiveDateTime + an UTCOffset. 

This is a minimal example:
```rust
fn main() {
    // Get the current Unix timestamp.
    let now = OffsetDateTime::now_utc();
    let pattern = "[unix_timestamp]";
    let f_description = format_description::parse(pattern).unwrap();
    println!("{:?}", now.format(&f_description).unwrap());
}
``` 

The reason I chose `PrimitiveDateTime` is that I didn't want to deal with timezones (basically the only place where it would have been relevant is the `today()` method since it allows specifying that you want the local date, but the way we deal with this at the moment is to just convert the local date time into a naive date time with the offset added (see [here](https://github.com/typst/typst/blob/076ef3d5f25bdb48f4f33d5bb20b3cc2b64e11a1/crates/typst-cli/src/world.rs#L137-L141))).

So I think instead of having a `as-unix` method, the best option in my opinion would probably be to switch to `OffsetDateTime` internally, although this might be a bit more work. There are two options:
1. We use `OffsetDateTime` internally, but don't expose the fact that there are timezones to the user in Typst, i.e. we don't allow specifying timezones yet in Typst. We only do this so that formatting with `[unix_timestamp]` is possible. This would be the preferred option in my opinion (it depends on how much time you're willing to invest) because it's less work, and proper support for timezones can always be introduced later on in another PR.
2. We introduce proper support for timezones in Typst as well, but this would probably require some more discussion on how this exactly should be designed.

Regarding the `from-unix()` method, in my opinion, instead of implementing this directly we should implement datetime parsing for any datetimes, which is also supported by the time crate. The reason I didn't implement this back then is that I couldn't figure out what the method should be called, but now that we have function scopes we can just have something like `datetime.parse(format, date)`. Another reason was that parsing won't work for dates that contain words in other languages, i.e. it will work for a date like `22 December 2023` but not `22 Dezember 2023`, but I think this is a limitation we can accept for now, considering that in most cases dates are written as a number anyway. Unfortunately, this is also going to be a bit of work, but in my opinion it's the better approach than introducing a `from-unix` method. Here is how it looks in the Rust code:

```rust
fn main() {
    // Get the current Unix timestamp.
    let pattern = "[year], [month repr:long], [day]";
    let f_description = format_description::parse(pattern).unwrap();
    println!("{:?}", Date::parse("2023, December, 11", &f_description));

    let pattern = "[unix_timestamp]";
    let f_description = format_description::parse(pattern).unwrap();
    println!("{:?}", OffsetDateTime::parse("1000000000", &f_description));
}
```

Result:

```
Ok(2023-12-11)
Ok(2001-09-09 1:46:40.0 +00:00:00)
```

That's just my two cents though, I guess having a `from-unix` method where you can pass the timestamp directly as a number wouldn't hurt as well, but in my opinion the above approach would be more consistent.

**Comment by laurmaedje** [comment]
Thanks for all the good points. I like the approach with `parse` method. What I'm wondering is whether it should parse smartly (e.g. TOML-like) if the format isn't given. Is that possible?

**Comment by LaurenzV** [comment]
You mean that the date format is automatically recognized? I don't think this is supported by the crate, we'd have to implement that logic on our side. I suppose we could hard Code a couple of commonly-used formats and then basically just try them one after another, but this would be pretty fragile in my opinion, so not sure how much  sense this makes. Just alone the fact that writing a date like 01-07-2023 means July 1st, 2023 in Europe while it is January 7th, 2023 in the US. I think this might complicate things.

**Comment by bluebear94** [comment]
I think it would be reasonable to require dates to be written in the ISO 8601 format. I’m not sure to require the same for datetimes, though, since separating the date and the time with a `T` might be unintuitive for less technical users.

**Comment by PgBiel** [comment]
Worth saying that being able to specify a custom epoch for the timestamp could also be useful, but that could probably be done in a separate PR if appropriate. Still, this likely implies that more generic names could be used for the methods (`to-timestamp` and `from-timestamp`, defaulting to the Unix epoch).

**Comment by lvignoli** [comment]
Is exposing the whole parsing capabilities of the crate, while defaulting to Unix let's say, a bad UX?
It looks quite flexible to me with a sound default.

But I suspect that while this make the functions parsing and displaying function very powerful and versatile, it may be too "low-level" for the average expected Typst user.

**Comment by Myriad-Dreamin** [comment]
@laurmaedje Is "time parsing/processing" another use case of wasm plugin? We can delay "from-unix/to-unix" from official support and wait for more comments.

**Comment by laurmaedje** [comment]
I think a good use case for wasm plugins is something you want to use an existing C or Rust library for instead of reimplementing it in Typst. I'm not sure how complex from-unix/to-unix would be to implement in Typst. I would imagine not that complicated and then plugins might be overkill, but I might be wrong.

Some things are so central that they should be compiler built-in, but even then a plugin might be a good way to start experimenting with a feature.

**Comment by laurmaedje** [comment]
I agree with what @LaurenzV said. We should implement this in a more generalized way with datetime format parsing. I am going to close this.

**Pull request closed without merging**
