### PR TITLE
Introduced `crop` parameter in `image` for selective display of image portions

### PR DESCRIPTION
**Pull request by varphone**
Introduced `crop` parameter in `image` for selective display of image portions

This PR introduces a new `crop` parameter in the `image` function.
This allows users to selectively display portions of an image, which can be particularly useful when working with large images or when only a specific part of an image is relevant.

- [x] Add a new `crop` parameter in the `image` and `decode` function.
- [x] Support raster images.
- [ ] Support vector images.
- [x] Support `(left, top, right, bottom)` tuple as the value for the `crop` parameter.
- [ ] Support `(left, top, width, height)` tuple as the value for the `crop` parameter.
- [x] Support ratio based cropping.
  - `crop: (left: 0.1, top: 0.1, right: 0.9, bottom: 0.9)` will crop the image to 10% from the left, 10% from the top, 10% from the right, and 10% from the bottom.
- [x] Support pixel based cropping.
  - `crop: (left: 100, top: 100, right: 200, bottom: 200)` will crop the image to 100 pixels from the left, 100 pixels from the top, 100 pixels from the right, and 100 pixels from the bottom. 
- [x] Support ratio and pixel based cropping together.
  - When the `left` or `top` `>= 1.0`, it will be considered as pixel based cropping.
  - When the `right` or `bottom` `> 1.0`, it will be considered as pixel based cropping.
  - `crop: (left: 0.1, top: 100, right: 0.9, bottom: 200)` will crop the image to 10% from the left, 100 pixels from the top, 10% from the right, and 200 pixels from the bottom.

### CODE REVIEW

**Comment by johannes-wolf** [comment]
I think ratio based cropping should use Typst ratios: `10%` instead of `0.1`.

**Comment by tingerrr** [comment]
I wonder if this should be image specific, or instead be a more general, improved clipping + place/align mechanism on containers (block/box).

It reminded me of #2709 where I attempted to change which part of an image was shown using `block(clip: true)` combined with `align` and `move`.

**Comment by laurmaedje** [comment]
I'm also not sure if having this as an image-specific thing is great. The only thing that makes only sense in the context of images is the pixel-based clipping, but how frequently is that needed? I'm also concerned about the re-encoding. It's less efficient than path-based clipping and it's also easy to lose color-space information etc.

**Comment by laurmaedje** [comment]
Since we aren't sure whether this is the best way to approach the problem, I think this first needs to go back into the design phase. I'll close this PR for now. We could discuss this more in a Discord forge thread. Thanks still!

**Pull request closed without merging**
