### PR TITLE
Adding WebP support

### PR DESCRIPTION
**Pull request by Conando025**
I like using webp and as #2673 shows I'm not the only one.
And since the implementation was basically just adding the respective feature of the image crate,
so I went ahead and made a PR. 
If there is an Issue with this PR (I've never done this before) please let me know.

### CODE REVIEW

**Comment by Enivex** [comment]
I think this introduces a c-dependence

**Comment by Conando025** [comment]
As far as I can see the c-dependence comes from the encoder feature

**Comment by Enivex** [comment]
My bad then!

**Comment by reknih** [comment]
As I see it, this feature has a few pros and cons:

**Pros:**
- Much smaller binary size increase than for JPEG XL
- [Widely used](https://w3techs.com/technologies/overview/image_format)
- Would be the only format with lossy encoding and a (usable cf. GIF) alpha mask
- Future-proofing for HTML export

**Cons:**
- Encourages use of WebP in print documents despite often quite visible compression artifacts
- [The compression advantage for print-sized images at similar quality to JPEG references is low](https://siipo.la/blog/is-webp-really-better-than-jpeg)
- PDF does not support WebP. We either have to lossily transcode to JPEG or embed a deflated pixel buffer (PNG-like, makes the file larger)
- It does proliferate image formats in Typst, which are currently limited to a standard set

What do y'all think about this?

**Comment by Enivex** [comment]
I'm leaning towards instead using the plugin system to add more image formats.

**Comment by extua** [comment]
Slightly off topic but according to https://github.com/pdf-association/pdf-issues/discussions/248#discussioncomment-4244510 the most likely format to be adopted in a future PDF standard is AVIF or JPEG-XT.

**Comment by laurmaedje** [comment]
> I'm leaning towards instead using the plugin system to add more image formats.

Since there were no further arguments in favor of having it built-in and I agree with this, I'm gonna go ahead and close this.

**Comment by laurmaedje** [comment]
One thing we can think about in the future is to make it easy to use a custom decoder with the existing image function.

**Comment by mattfbacon** [comment]
In terms of custom decoders, it would be nice to be able to convert raw `bytes` to an image based on a size and format. Like `image.from-raw` or `image.from-pixels` or something

**Comment by laurmaedje** [comment]
@mattfbacon See here: https://github.com/typst/typst/issues/2575

**Comment by LinusU** [comment]
@laurmaedje would you be open to adding this behind a non-default Cargo feature?

I'm using Typst as a Rust library (which works great, absolutely love the project 🤩) and need to add support for WebP images. Seeing how small this PR is really makes me think that this is such a clean way to add it.

Currently, I'm looking into on the fly converting the WebP to a PNG when the file is loaded from disk, but this is of course quite the hack 🙈

In my use case, I'm exporting to PNG, so PDF support is not something that would affect me right now.

**Comment by mattfbacon** [comment]
@LinusU I think the solution these days would be to write a WASM plugin that decodes the WEBP because we now have the ability to load an image from raw color data. Maybe such a package already exists.

**Comment by LinusU** [comment]
@mattfbacon I'm not sure that that would be a great fit for my use case 🤔 

I'm rendering templates with data, so when I'm writing the template I don't know if the image path passed in will be webp or some other type. My Typst code simply looks something like this (obviously very simplified 😅):

```typst
#image(sys.inputs.image)
```

On top of that, since I'm already building Typst myself, it would be preferred to have a natively compiled image decoder, instead of compiling it to WebAssembly, and then running it in a virtual machine (or JIT-compiling it, etc.).

Especially since the WebP decoder already is included in the build tree right now (via `krilla`) 😅

**Comment by laurmaedje** [comment]
The fact that krilla already includes WebP is a fair point, so a feature flag wouldn't be necessary. Because compile-time feature flags is not something we want to add to the `typst` crate. That opens up a can of worms w.r.t. to testing.

**Comment by LinusU** [comment]
I've implemented it with feature flags here: https://github.com/typst/typst/compare/main...LinusU:typst:webp

It works great in our application! 🙌 

-----

As can be seen in the Cargo.lock diff, there is no additional packages being included (since the webp decoder is already included).

@laurmaedje I would love to create a PR without the feature flag, if you are interested in merging.

It would help me immensely, as I think that the other alternative would be for me to maintain a permanent fork that just float the patch on top 😅

(since it's such a small patch, this would probably be feasible. Another approach would be to go back to my original plan to modify the file when it's being read from the disk)

**Pull request closed without merging**
