### PR TITLE
Fix clippy lints, rustfmt, etc

### PR DESCRIPTION
**Pull request by mattfbacon**
Just a general cleanup

### CODE REVIEW

**Comment by SeniorMars** [comment]
This is too much to code review at once. In addition, you introduced new dependencies. I'm glad you did this, as the first few checks seem reasonable, but this is too much for a PR.


Could you break it down with separate commit messages for modules (not files)?

**Comment by laurmaedje** [comment]
This is indeed a bit much. I like many of the changes, but dislike others and there's no way to separate them.

**Comment by laurmaedje** [comment]
Maybe you could make a list of kinds of changes you propose (like az casts, must_use, unwrap handling, trait impls, denys, etc.) and then we can discuss which of these changes to make.

**Comment by mattfbacon** [comment]
> Maybe you could make a list of kinds of changes you propose (like az casts, must_use, unwrap handling, trait impls, denys, etc.) and then we can discuss which of these changes to make.

Good idea.

Here's a list of the top of my head:

- Add a more strict "lint prelude". Here's the one for the main library:

```rust
#![deny(
    absolute_paths_not_starting_with_crate,
    future_incompatible,
    keyword_idents,
    macro_use_extern_crate,
    meta_variable_misuse,
    missing_abi,
    missing_debug_implementations,
    missing_docs,
    non_ascii_idents,
    nonstandard_style,
    noop_method_call,
    pointer_structural_match,
    private_in_public,
    rust_2018_idioms,
    unused_qualifications
)]
#![warn(clippy::pedantic, clippy::dbg_macro, clippy::print_stderr, clippy::print_stdout)]
#![allow(clippy::module_name_repetitions)]
```

- `#[must_use]`
- `#[inline]`
- Sort `Cargo.toml`s
- Make rustfmt format a bit more: grouping imports by source (standard library, external, internal) and using a standard import granularity.
- Refactoring `Lang` to remove the length field and just set `storage[2]` to NUL to indicate a two-byte language code.
- Fixing various insignificant lints (eg, moving format params into the format strings, needless borrows, unnecessary qualifications, `semicolon_if_nothing_returned`)
- Denying `rust_2018_idioms`, which includes `elided_lifetimes_in_paths`: requires adding `'_` a lot. While some may consider this ugly, I think it's necessary and goes along with the Rust convention of being explicit about important details; elided lifetimes can cause improper bounds in public APIs, for instance.
- Denying `missing_debug_implementations`: good for UX, I think
- Building off of `wildcard_imports` discussed below, splitting up big blocks of `scope.define`s in super modules into `$submodule::define`s where each submodule provides a function to define its API.
- Building off of `unnecessary_lazy_evaluations` discussed below, in `src/layout/pad.rs`, making the `args.find` call lazy as a result of unwrapping its Result return type.
- Removing the UTF-16 stuff in `typst::syntax::Source` due to being unused.
- `reversed_empty_ranges`: led to a refactor in `src/syntax/reparser.rs` to use an Option which I think aids readability.
- Fixing some typos that were more subtle than the spellchecker pass could catch.
- Undid excessive wrapping of some comments that led to awkward typographical layout such as orphans (maybe a remnant from increasing the line length in the formatter config?)
- Fixing `clippy::derived_hash_with_manual_eq` (a deny-by-default correctness lint): this is actually quite important due to the relationship between hashes and equality.

Pedantic lints:

- `cast_possible_truncation`, `cast_possible_wrap`, and `cast_precision_loss`: leads to using az for lossy casts. This can round in some cases (eg i64 to f64), or panic in others (eg i64 to u16). Either way it's the "correct" behavior and solves the issue pretty well. That said, for casts from int to float, it's identical to just using `as` so maybe it's not worth it for those type of casts. I think its main value is in float to int, because it checks bounds before converting. Maybe we could allow `cast_precision_loss` and leave the others. Note, this did actually lead to improving correctness in some cases, e.g. `src/image.rs:148`.
- needless_pass_by_value`: requires changing some signatures to take borrows instead. This actually did allow removing some clones.
- `missing_panics_doc` and `missing_errors_doc`: leads to adding the documentation, which is generally a good idea anyway. Also led to changing some panics from `unwrap`s (the type that this lint tries to avoid due to their propensity to confuse users) to `expect`s, `unreachable!()`s, etc
- `unnecessary_wraps`; requires changing some signatures to remove the Option/Result wrapper.
- `enum_glob_use`; requires either expanding the `use` to specific cases or doing `use VeryLongEnumName as E` and then writing `E::` as necessary.
- `wildcard_imports`: changes the general idiom of `$(pub use self::$modules::*;)*` and `use super::*;` to more granular re-imports and imports. Helps because a lot of times submodules relied on external items that were incidentally imported into the super module for its own private use.
- `redundant_closure_for_method_calls`. Arguably worse for readability and should maybe be left as-is.
- `similar_names`: requires expanding some abbreviations used in variable names, for readability. But also makes code a bit longer in some cases. Also led to expanding/clarifying a lot of single-letter variable names.
- `match_same_arms`: leads to merging arms in some cases. I tried to use discretion, for example in cases where it's "one arm per variant/logical grouping".
- `len_without_is_empty`: adding `is_empty`. Allowed clarifying some other code that had previously used `.len() ==/!= 0` on these types.
- `unnecessary_lazy_evaluations`: pretty much always a win for readability
- `redundant_else`: allowed in most cases where it applied, so maybe should be allowed globally? it's clearer to remove the else in some cases but not in others.
- `too_many_arguments`: allowed in most cases where it applied, but notably not in `library/src/layout/shape.rs`.
- `type_complexity`: usually leads to extracting a type alias.
- `too_many_lines`: can be a helpful indicator to refactor out logically grouped operations, but also can be wrong, for example as a result of a large `match` block or a function that is doing one very complicated thing.
- `doc_markdown`: allowed in some cases but helped eg with links in docs. probably worth having enabled for its true positive cases.
- `float_cmp`: usually allowed where it applied. I'm not sure about this one.
- `wildcard_in_or_patterns`: always allowed where it applied, I think.
- `wrong_self_convention`: leads to renaming some methods based on clippy's suggestions.
- `map_unwrap_or`: leads to replacing with `map_or{,_else}`. Generally a win for readability.
- `comparison_chain`: leads to using matches. I think that in the cases where this applied, the rewritten solutions which use cmp. Also led to `tests/src/tests:61` which I think is especially pretty.
- `struct_excessive_bools`: always allowed where it applied, I think.
- `unnecessary_unwrap`: usually (always?) done in this codebase due to lack of let-chains, leading to the pattern of `if ... && x.is_some() && ... { let x = x.unwrap(); ... }`. In those cases, I allowed the lint with an `XXX` comment to refactor once let-else is stabilized.
- `match_wildcard_for_single_variants`: arguable whether it's worthwhile.
- `ptr_as_ptr`: arguably adds clarity but not very important or impactful. Example around `src/model/content.rs:120`.

**Comment by DuhPesky** [comment]
in cases where az doesn't have to be used (e.g i64::from(bool)) shouldn't be using az preferably, and minimizing its surface area to situations where the built in rust casting (excluding as) doesn't work. Also it might be better to just separate the docs markdown changes and code changes. But from quickly glancing i dont see anything that im strongly opposed to. What specifically are people against?

**Comment by mattfbacon** [comment]
I will rebase and resolve conflicts soon.

**Comment by laurmaedje** [comment]
I'll go through your list soon.

**Comment by mattfbacon** [comment]
Thanks. The tests pass now but looks like I have to rebase again

**Comment by laurmaedje** [comment]
I went through the first part of your list. Let's start with this. We can see about clippy later.

## Yes
- Sort Cargo.tomls
- Make rustfmt format a bit more
- Refactoring Lang to remove the length field: This could also set to space instead of NUL. That's easier to input and we can just trim().
- Fixing various insignificant lints
- reversed_empty_ranges
- splitting up big blocks of scope.defines
- fixing typos
- undid excessive wrapping of some comments

## No
- `#[must_use]`: These are a _lot_ of attributes for, in my opinion, little gain
- `#[inline]`: This only helps cross-crate and with LTO it is irrelevant, afaik.
- Removing the UTF-16 stuff in `typst::syntax::Source`: It's part of the public API and used by the web app.
- Denying rust_2018_idioms, which includes elided_lifetimes_in_paths: I see the value of elided lifetime in return values, but adding it to all inputs is really too much cluter in my opinion.
- Denying missing_debug_implementations: I don't like lints that hinder development. This will often fail during development and then I have to either write a Debug impl or turn it off.
- fixing clippy::derived_hash_with_manual_eq: A PR has since been merged to allow this. The setup is not ideal, but it's required for now and it works.

**Comment by mattfbacon** [comment]
For missing_debug_implementations, would a warn instead be okay?

**Comment by laurmaedje** [comment]
Yes, I guess that would be okay.

**Comment by laurmaedje** [comment]
Closing in favor of smaller, more focused PRs. Also, as discussed on Discord, I'm considering to have clippy in CI, but first need to try it for a bit.

**Pull request closed without merging**
