### PR TITLE
Repeatable figure captions

### PR DESCRIPTION
**Pull request by PgBiel**
Closes https://github.com/typst/typst/issues/5057

In principle, I took the low-hanging fruit and just slapped grid with headers/footers onto our figure.

This also has the advantage of being fully reproducible in figure show rules.

# Discussion

This code is quite small and already usable, but there are a few design decisions that should be taken into account before merging:

1. Should repeat be enabled by default? It does add the overhead of a grid to all figures, but one workaround for that is to only add it when the figure is actually breakable (it isn't by default). And it does seem like a sensible default to me. For now, though, it's opt-in.
2. One common use case (as shown in the issue) is to have a "Continuation" marker for captions. While it is already possible in this PR using `context` and counter steps, we could want to have some built-in mechanism, e.g. provide a function to the caption to run it once for each page. Though it would be nice to be consistent with headers and footers here, so maybe that should ship as a separate package.

### CODE REVIEW

**Comment by PgBiel** [comment]
Drafting until further discussion.

**Comment by laurmaedje** [comment]
A context based design sounds nicer to me than a function.

**Comment by laurmaedje** [comment]
Let's discuss this in our next meeting.

**Comment by PgBiel** [comment]
I agree continuation handling is important - repetition by itself is already handy for certain use cases, but that can be reproduced in pure Typst fairly easily.

Do we have any new proposals regarding how it should be done? Maybe the community has further ideas as well.

**Comment by laurmaedje** [comment]
I don't have concrete proposals. But I could imagine some kind of element that you can put around stuff to wrap it and provide customized continuations.

**Comment by laurmaedje** [comment]
I'll close this for now. We can reopen it if we're more sure about how we want to go about this.

**Comment by reknih** [comment]
@SoappGuy For updates, subscribe to #5057. You can help move this feature along by sharing yet undiscussed requirements and by participating about the discussion about design and API there and on Discord. Please refrain from asking about updates without any such input. When subscribed to the issue, you'll be notified of updates when they happen.

**Pull request closed without merging**
