### PR TITLE
 feat: support float in `array.range()` for start, end, and step

### LINKED ISSUE #2908: `float` support for `range()`
### Description

Right now, `range()` needs two integers, however, it should be able to take floats.

### Use Case

Instead of having to do

```typst
// hand-offset is either 0, 0.5, or 1
for i in range(0, 6).map(x => x + hand-offset) {
```

I could just do

```typst
range(hand-offset, hand-offset + 6)
````

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Closes #2908

Untested and wrote at 1AM

### CODE REVIEW

**Comment by PgBiel** [comment]
IMHO this should return `int` when all parameters (start, stop, step) are ints for consistency with the current behavior (and I think it makes sense). But I'd like further opinions.

**Comment by laurmaedje** [comment]
It should definitely return ints in that case.

**Comment by ThatOneCalculator** [comment]
As discussed in #2908, this should maybe be extrapolated to `linspace`

**Comment by laurmaedje** [comment]
I am not really convinced that linspace belongs into the standard library tbh. Extending range felt natural, but has apparently float problems, so I would go ahead and close this for now. If we decide that linspace is worth it, that can be a new PR.

**Comment by ThatOneCalculator** [comment]
As far as I can tell, it would really only have problems if it accepted floats for start and end. I can't see any problems occuring with two int endpoints and a float step

**Comment by laurmaedje** [comment]
Doesn't the problem still exist even if the bounds are ints? Ultimately the accumulator needs to be a float and that may end up _just_ below the boundary, no matter the type of the boundary. In fact, the implementation would need to cast the int bound to a float to compare it in the first place.

**Pull request closed without merging**
