### PR TITLE
Add a simple fuzz harness for the parser

### PR DESCRIPTION
**Pull request by silvergasp**

### CODE REVIEW

**Comment by silvergasp** [comment]
I've included a few more details on the context behind this PR here https://github.com/typst/typst/discussions/2388. As a few extra notes on getting started with fuzzing on rust you'll need to run;
```
cargo install cargo-fuzz
cd crates/typst-syntax
cargo +nightly fuzz run parse
```

At this point you'll see something like;
```
    Finished release [optimized + debuginfo] target(s) in 0.01s
     Running `fuzz/target/x86_64-unknown-linux-gnu/release/parse -artifact_prefix=/home/nathaniel/projects/github.com/silvergasp/typst/crates/typst-syntax/fuzz/artifacts/parse/ /home/nathaniel/projects/github.com/silvergasp/typst/crates/typst-syntax/fuzz/corpus/parse`
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1843216232
INFO: Loaded 1 modules   (79884 inline 8-bit counters): 79884 [0x55b4cec728b0, 0x55b4cec860bc),
INFO: Loaded 1 PC tables (79884 PCs): 79884 [0x55b4cec860c0,0x55b4cedbe180),
INFO:     3300 files found in /home/nathaniel/projects/github.com/silvergasp/typst/crates/typst-syntax/fuzz/corpus/parse
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 9042 bytes
INFO: seed corpus: files: 3300 min: 1b max: 9042b total: 3800937b rss: 46Mb
#2048   pulse  cov: 4846 ft: 22906 corp: 1622/291Kb exec/s: 1024 rss: 109Mb
^C==17115== libFuzzer: run interrupted; exiting
```

The fuzzer will run indefinetely or until;
- You manually exit ctrl-C
- It finds a bug/crash
- It more than an optional user specified timeout.

I'll happily include this in the documentation somewhere, although I'm unsure where to put that :)

**Comment by laurmaedje** [comment]
I've now finally found some time to take a look. Here are my thoughts:

- I think before merging anything, we should first discuss which parts of the compiler benefit most from fuzzing (parsing, incremental parsing, fully integrated compilation, etc.) and how fuzzing can be applied to each of those.
- How does this work with running on Google's distributed cluster? Do we need to apply somewhere for this?
- If we do this, I would like to keep the maintainance overhead minimal: How autonomous would the setup be? Are there any regular manual steps involved? Would the fuzzing setup need to be continually updated (like a test suide) or is it mostly automatic?
- I'd prefer if any fuzzing related things would be in a single place, likely in a `tests/fuzz` instead of in the crates directory
- The https://openssf.org/best-practices/ link is a 404

**Comment by silvergasp** [comment]
> I think before merging anything, we should first discuss which parts of the compiler benefit most from fuzzing (parsing, incremental parsing, fully integrated compilation, etc.) and how fuzzing can be applied to each of those.

Well to start with here are a few guidelines for choosing API's that would benefit the most from fuzzing;
- Fuzzing code with any global state is hard to do correctly.
- Fuzzing code that uses random number generators can be tricky. This can be managed somewhat by using pseudorandom number generators as an alternative, while an improvement it's still tricky to get right.
- Fuzzing targets need to be fast to actually be useful (i.e. less than 1s per function call).

There is also a bit of a time/effort tradeoff in writing the fuzz harnesses. e.g. fuzzing a function that re/parses something is usually easy as there is very little transformation that needs to happen to transform generated fuzzed data into a string. Structured fuzzing i.e. converting raw data into structs is relatively straightforward. But it get's complicated if your code expects pre-validated input, as generating valid input can be tricky.

My intuition here is that most of what you have mentioned (parsing, incremental parsing, fully integrated compilation, etc.) would be pretty straightforward to do, as long as it can be done without file io. It's not a complete deal breaker if we need to track files, but it does make it a bit slower.

In an ideal scenario we could do an end to end fuzz-test which just takes a set of strings and outputs a pdf. Preferably all in-memory. This would give the best code coverage with the simplest fuzzers (although it might be too slow). If you have any thought's with where I should start with that then let me know.

> How does this work with running on Google's distributed cluster? Do we need to apply somewhere for this?

Yes the application process is described [here](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/). I'm happy to complete that application on your behalf, all I'll need from you is some contact details is a google/gmail email address and for you to comment on the PR essentially saying that you approve of it. Are you happy for me to do that?

> If we do this, I would like to keep the maintainance overhead minimal: How autonomous would the setup be? Are there any regular manual steps involved? Would the fuzzing setup need to be continually updated (like a test suide) or is it mostly automatic?

In terms of automation a complete setup will typically look like the following;
1. Every night the google/oss-fuzz will fetch the latest commit, build the project and then run the fuzzers for a few hours looking for bugs.
2. If a bug is found it'll send you an email to a link on a private bug tracker, and (optionally) open a corresponding issue on github.
3. (Optional) you can also setup a [github-action](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) that runs a stripped down version of oss-fuzz in your CI. This will ensure that PR's don't break the fuzz-tests. It'll also run the fuzzer's for a short period of time (5-10min), to catch any shallow bugs before they get merged.

In summary It's mostly automatic, although there would occasionally be some manual steps involved. e.g. if you make a breaking API change e.g. change a function signature the fuzz tests will need to be updated to match. But generally this is less time-intensive than updating unit-tests as fuzz-tests typically aren't as tightly coupled with the behaviour of a given api. 

All up once it's setup up there is pretty little effort required to maintain all this, but it isn't "zero" effort.

> I'd prefer if any fuzzing related things would be in a single place, likely in a tests/fuzz instead of in the crates directory

Not a problem that should be an easy enough change to make.

> The https://openssf.org/best-practices/ link is a 404

Hmm looks like the restructured their site recently I'll see if that content has moved.

**Comment by silvergasp** [comment]
Hmm that's new behaviour, I wasn't aware that github will close a PR if the branch is force pushed too...

**Pull request closed without merging**
