### PR TITLE
Suggest accessing field if method doesn't exist

### LINKED ISSUE #2952: error messages: suggest field/method with that name exists
### Description

When a user types uses a field instead of a method, or the other way around, the error message is not very clear:

```
error: content does not contain field "location"
```

It would be great if Typst could provide a hint with the error message. Here are some examples:

```
error: content does not contain field "location". Did you mean to use a method instead of a field?
```

```
error: content does not contain field "location". Did you mean "location()"?
```

```
error: content does not contain field "location". A method with that name exists.
```

```
error: content does not contain field "location" but has method "location()".
```

### Use Case

I often forget which fields are methods or fields. When I encounter this message, I think I either made a typo or I am performing the field lookup on the wrong variable. Debugging would be faster when hints like this are provided.

### PR DESCRIPTION
**Pull request by voidiz**
If a non-existent method is called, but a field with the same name exists, a hint suggesting to access the field instead is displayed.

Related: #2952 

~~If the called method doesn't exist, a hint suggesting to access the field with the same name is displayed. Conversely, if the accessed field doesn't exist, a hint suggesting to call the method with the same name is displayed.~~

~~The hint is showed regardless of the existence of a corresponding method/field. I suspect that it would be better to only show the hint if it exists, but I'm unsure on how to best check that.~~

### CODE REVIEW

**Comment by PgBiel** [comment]
> I suspect that it would be better to only show the hint if it exists, but I'm unsure on how to best check that.

Yeah, I think this check would be necessary, because otherwise Typst would be providing misleading hints (it'd be better to not show the hint than to point to the wrong place).

Regarding how to implement the check, I think we'd need some input from @laurmaedje first.

**Comment by laurmaedje** [comment]
Checking whether a value that doesn't have method X has field X is simple and only needed in one place: Just `target.field(X).is_ok()` in `FuncCall::eval`.

Checking whether a value that doesn't have field X has method/callable X is more complicated: It basically needs the full call logic which resolves things on symbols, functions, types, modules, etc. It would also need to be done in multiple places.

I would suggest taking small steps and first implementing just the method -> field hint. 

For the other thing, we should first consolidate the logic a bit. The code in `field_access_completions` in `typst-ide` for instance mostly does what we need, but we should not duplicate it and spread it everywhere. Ideally, there would be some function like `field` we can just call on `Value`, but I'm not sure whether it's really that simple because method dispatch is a bit complicated.

**Comment by voidiz** [comment]
I see. I'll start by looking at the simpler method -> field case, then.

**Comment by voidiz** [comment]
@laurmaedje I have now changed the PR to only cover the method -> field case.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
