### PR TITLE
path: Use close_path for closing paths

### PR DESCRIPTION
**Pull request by johannes-wolf**
With this fix:
image

Without:
image

### CODE REVIEW

**Comment by johannes-wolf** [comment]
How can I generate and update the test images?

**Comment by PgBiel** [comment]
> How can I generate and update the test images?

Run the tests to generate in the "tests/png" folder; then move the generated png to "tests/ref" to accept it as the reference png; and **(important)** run `oxipng -max the_generated_png.png` to compress the image (you may have to install oxipng separately)

**Comment by laurmaedje** [comment]
As illustrated the current way is problematic, but @SekoiaTree intentionally did not use `close_path` because it always draws a straight line instead of respecting the curves control points. I'd like to hear their take on this.

**Comment by SekoiaTree** [comment]
Hmh. That's a bit annoying.

As laur said, this PR breaks curved closing (which is the feature I wanted; if you want to simply close with a straight line, add an extra point to the end). But line caps being broken is quite annoying.

I genuinely have no idea how to fix this. Maybe redraw the first line again to close off the path nicely?

**Comment by johannes-wolf** [comment]
I can not see how it breaks anything. Since your curved closing is already moving to pt[0] we are already at the start location of the path. Drawing a straight line to pt[0] again is not visible?

Could you please provide an example?

The current implementation is unusable for closed paths with a stroke!

**Comment by johannes-wolf** [comment]
This test:
```
path(((0cm, 0cm), (2cm, 1cm)), (2cm, 2cm), closed: true)
```
Renders exactly the same in both versions!

**Comment by SekoiaTree** [comment]
> @SekoiaTree Could you please provide an example?
One of the tests:
`#path(fill: blue, closed: true, ((50%, 0%), (15%, 15%), (-10%, 0%)), ((50%, 30%), (-10%, 0%), (0%, 0%)), ((65%, 15%), (60%, -15%), (60%, 0%)))`

**Comment by johannes-wolf** [comment]
> > @SekoiaTree Could you please provide an example?
> 
> One of the tests: `#path(fill: blue, closed: true, ((50%, 0%), (15%, 15%), (-10%, 0%)), ((50%, 30%), (-10%, 0%), (0%, 0%)), ((65%, 15%), (60%, -15%), (60%, 0%)))`
> 
> This code breaks any path that starts or ends with a point with control points.

Render same in both versions.
I don't get the problem. As I had mentioned: You are already closing the path curved, I have changed nothing about that.

Could you provide screenshots? I have tried multiple things, nothing looks broken, except outlines of the current implementation.

**Comment by SekoiaTree** [comment]
Aha, my bad. I misunderstood how you were closing the path. I thought you replaced the current method, rather than adding it. In that case, this looks good to me.

**Comment by johannes-wolf** [comment]
> Aha, my bad. I misunderstood how you were closing the path. I thought you replaced the current method, rather than adding it. In that case, this looks good to me.

@laurmaedje Please merge :)

**Comment by laurmaedje** [comment]
ah okay, this changed since I last look at the diff. if it works now I'm happy.

**Pull request merged**
