### PR TITLE
Adjust table inset behavior to the same as container's (#1979)

### LINKED ISSUE #1979: Dictionary inset in tables
### Description

See title

I'd like to be able set different inset for x and y for the cells in a table. Currently, inset can only be a length, unlike for rect, box and block.

Note that this is currently not available even in tablex.

### Use Case

It's sometimes convenient to have more vertical spacing than horizontal spacing, or vice versa.

### PR DESCRIPTION
**Pull request by HydroH**
Resolves #1979 .

### CODE REVIEW

**Comment by laurmaedje** [comment]
I wonder why I didn't do this in the first place... probably an oversight.

**Comment by PgBiel** [comment]
Just for completeness, can you also add a table in your tests which uses all 4 inset configuration keys?

Also, I believe it might be a good idea to add an example to the inset parameter's documentation (the docstring above the `inset` field), with two tables: one with a simple inset parameter (e.g. `10pt`), and another the 4 inset config keys.

**Comment by laurmaedje** [comment]
@PgBiel Parameters can only have one example or at least both things would need to be part of one example. But that's one very long example.

**Comment by PgBiel** [comment]
> @PgBiel Parameters can only have one example or at least both things would need to be part of one example. But that's one very long example.

Yeah I think it's fine to have a single example with both. They can be very short tables.

For instance:

```typ
#table(inset: 10pt)[Info 1][Info 2]

#table(inset: (left: 4pt, top: 10pt, bottom: 20pt, right: 2pt)[Cell 1][Cell 2]
```

**Comment by laurmaedje** [comment]
```typst
#table(
  inset: 10pt,
  [Info 1],
  [Info 2],
)

#table(
  inset: (
    left: 4pt, 
    top: 10pt, 
    bottom: 20pt, 
    right: 2pt,
  ),
  [Cell 1], 
  [Cell 2],
)
```
will likely render more nicely because it's side by side. the left side will probably be a bit higher. whereas wide input that produces a high output will not look good.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
