### PR TITLE
[WIP] Add fit-content option for over- or underbrace-like objects

### LINKED ISSUE #3242: underbrace content below other text (optionally)
### Description

To prevent big blank spaces for example in an equation it would be great to have an option to allow the content below the bracket to go under the content written to the left of the bracket. 
So currently `$<= n + underbrace(2n ln n, "Anzahl Schnitte aller Segmente")$` looks like this: 
grafik
And I think with the option enabled (true boolean) it should look like this (I edited the image): 
grafik

### Use Case

I just think that it looks nicer and saves a little bit of space

### PR DESCRIPTION
**Pull request by kAIto47802**
## Description

This PR addresses Feature Request #3242. It introduces options to allow the text under/over the underbrace/overbrace to go under/over the left and right sides of the formula. It also includes options to make the parentheses ignore underbraces/overbraces.

### `fit-content` (default: true)
With `fit-content` set to true, it becomes like this:
```
$(2 + 3 + underbrace(1 + 2, "long annotations") + 4)$
```
Screenshot 2024-02-12 at 4 21 16

With `fit-content` set to false, it remains the same as the original, looking like this:
```
#set math.underbrace(fit-content: false)
$(2 + 3 + underbrace(1 + 2, "long annotations") + 4)$
```
Screenshot 2024-02-12 at 4 21 46

### `fit-width` (default: true, takes precedence over `fit-content`)
While `fit-content` fits both width and height, `fit-width` only fits width.
This is useful when multiple over- or underbrace-like objects close to each other within parentheses.
```
#set math.underbrace(fit-width: false)
$(2 + 3 + underbrace(1 + 2, "long annotations") + underbrace(4 + 2, "long annotations") + 3 + 1)$
```
Screenshot 2024-02-12 at 4 23 01

### `fit-height` (default: true, takes precedence over `fit-content`)
Just as `fit-width` only fits width, this only fits height.

## Notes

When `fit-height` set to true, the text under/over the underbrace/overbrace might become very close to the following/preceding lines. To resolve this, I thought it is necessary to change `lr` (left-right delimiters) and other fundamental modules. Since it involves a significant changes in area different from under/over objects, it is not included in this PR. But if it is needed, I'll also add it.

(Resolves #3242)

### CODE REVIEW

**Comment by laurmaedje** [comment]
The results definitely look nicer than what Typst produces currently! I wonder whether this should really be togglable or whether Typst should just do the right thing™ by default though. (I also think the naming is rather confusing; it turned out to be reserve to what I would have expected. That would be side-stepped if we would just make it fully automatic.)

I think the equivalent of `fit-content: true` is a reasonable default, but two adjacent annotations would then need to make space for each other. I also think the fit-height case, where lines get too close, is problematic indeed. You mentioned some changes to the fundamentals to fix this. How would you approach it?

**Comment by kAIto47802** [comment]
Thank you for replying.
Originally, I didn’t thinking about making it automatic, but I thought it is indeed a very good idea. Also, If we automate it, I also think it would be good to not only decide whether to fit or not but also to adjust the width to the right amount like this (I’m now making this by editing picture):
Untitled120_20240214021255


Automation is very nice feature, but I also thought that, from an implementation perspective, it would require some changes beyond just the underbrace function. It’s because in the current implementation, equations, curry brackets, and annotations are grouped together into a single frame, and from this object itself, it’s not possible to tell whether it is close to other object (even if it’s just about wether to fit annotation to the equation or not); It have to adjust outside the underbrace frame. To do this, I thought
1. Add some information to MathContext with underbrace frame object (which indicates that annotations are attached)
2. Prepare a function to adjust width of underbraces after `fragments: Vec<MathFragment>` in `MathContext` object has been fully populated. This function should take `ctx: &mut MathContext` in its argument and adjust the width of underbrace by examining the entire `MathContext` object.
3.  Call this function in `fn layout_inline` and `fn layout` in equation.rs (after `ctx: MathContext` has been fully populated)

I thought that the information I previously mentioned is also necessary to address the issue where lines get too close with `fit-height: true`. This is because lr (left-right delimiters) must disregard the height of annotations, whereas a line must consider the total height of the underbrace frame. Therefore, to resolve this problem, I thought
1. Add some information to MathContext with underbrace frame object (which indicates that annotations are attached) (This is same as above)
2. Ignore annotation’s height in calculation of `max_extent` in `layout_math` of `Packed<LrElem>`

What do you think?

**Comment by laurmaedje** [comment]
I think in principle it makes sense to have extra information on the `FrameFragment`, but we need to take great care to not spread the complexity across all of math layout. Most things shouldn't need to be aware of this new logic. I would also prefer to keep things fully within the math layout and not leak into `layout_inline`.

If you do take a stab a this, it would be great if you could keep me in the loop, so that we can discuss things will they are still in-flux!

**Comment by kAIto47802** [comment]
Thank you for your reply. That’s right. I was also concerned about this requiring a lot of changes (which is why I didn’t proceed with it for the first time).  So, which do you think would be better:  to continue tackling this issue with precise discussions, or to stop and keep things as they originally were?

**Comment by laurmaedje** [comment]
> So, which do you think would be better: to continue tackling this issue with precise discussions, or to stop and keep things as they originally were?

Do you mean the extra manual options with "keep things as they originally were"? If so, I'm still of the opinion that an automatic solution would be much more desirable. I understand that it's tricky to implement, but I think we should try at least.

**Comment by laurmaedje** [comment]
If you want to try implementing the automatic solution, I think that'd be great. I am also happy to help by discussing approaches/ideas. I can't promise that I would merge an automatic solution if it turns out to introduce a ton of complexity, but I feel like there ought to be some way to implement it cleanly. If it turns out to be complex when attempting it, we can reconsider what to do.

**Comment by kAIto47802** [comment]
Thank you for asking. I got busier lately and have not found the time to work on. When I get more time and want to work on it, I'll open it again.

**Pull request closed without merging**
