### PR TITLE
Add tooltips to a closure

### PR DESCRIPTION
**Pull request by Myriad-Dreamin**
This PR provides functionality to hover up some closure function in the IDE and then see which variables are captured.

For example, the following closure produces a tooltip `captures: hidden`
```typ
#let hidden = 10;
#let c(x, y) = {
  hidden + x + y
}
```

This PR is still in draft since we have a list of todo:
+ <del>Correctly get the `Scopes` context where the closure is located: The `CapturesVisitor` helps but still requires a `Scopes` that defines all external items visible to the closure. I don't know whether there is a convenient helper to get it.</del>
+ <del>Determine the message format of tooltip. It currently uses `eco_format!("captures: {names}")`.</del>
+ <del>(Optional) exclude the closure capturing itself from tooltip: for example the closure `c(x, y) = {}` captures `c` itself.</del>

### CODE REVIEW

**Comment by laurmaedje** [comment]
Nice!

> Correctly get the Scopes context where the closure is located: The CapturesVisitor helps but still requires a Scopes that defines all external items visible to the closure. I don't know whether there is a convenient helper to get it.

I think we could just modify the existing visitor to make the scopes optional. If they are none, just assume everything exists and fill the values with `Value::None`. (Maybe there's a cleaner way, but something along these lines.) We're only interested in the variable names anyway.

> Determine the message format of tooltip. It currently uses `eco_format!("captures {names}")`.

This is a bit of bike-shedding case I guess. Let's revisit it once everything else is in place.

> (Optional) exclude the closure capturing itself from tooltip: for example the closure c(x, y) = {} captures c itself.

Definitely exclude it. It's doesn't help anybody.

**Comment by Myriad-Dreamin** [comment]
> If they are none, just assume everything exists and fill the values with `Value::None`. 

Now that I have completed the first and third todo. I added a `SYNTACTICAL` to the visitor to mark whether it should analyzes node syntactically, but I don't find similar code pattern in the repository. A second implementation is final to check whether it is in "syntactical" mode at runtime.

@laurmaedje

**Comment by laurmaedje** [comment]
The implementation looks good now. I prefer less generics typically, less code bloat.

**Comment by laurmaedje** [comment]
For the text, I think a sentence would be friendly. Something like: `This closure captures x, y, and z.`

**Comment by Myriad-Dreamin** [comment]
> Something like: This closure captures x, y, and z.

Looks good! We have a typical l10n/i18n problem here, but I think we don't have to consider it in this PR.

I use a cool function `separated_list` for formatting, then we complete all the todos now.

**Comment by laurmaedje** [comment]
Thank you!

**Pull request merged**
