### PR TITLE
Render opening smart quote after another opening quote of a different type

### LINKED ISSUE #1379: Smart Quotes Break when start of the string has both Double and Single Quotes
### Description

# Smart Quotes seem to work correctly when... 
- The string is surrounded only by double quotes or only by single quotes
- When the whole string is surrounded by double quotes and a smaller section is surrounded by single quotes
# Smart Quotes don't seem to work correctly when...
- The start of the string is both double and single quotes.
# Example:
Writing `"'This is a quote from a book and it is character dialogue'" (100).` results in:
image

If only part of the quote is in single quotes like so: 
`"This is a quote from a book. 'Here is the speaking part'" (100).`
It seems correct:
image

# Hacky Workaround:

`"#sym.quote.single.l#h(-2pt) This is a quote from a book and it is character dialogue'#sym.quote.double.r (105).`
Results in:
image

### Reproduction URL

_No response_

### Operating system

macOS

### Typst version

- [x] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by bluebear94**
Fixes #1379.

### CODE REVIEW

**Comment by laurmaedje** [comment]
I think we originally implemented some common smart quote algorithm. Is the approach taken in this PR common or more of an ad-hoc fix? If it is the latter, perhaps we should survey existing algorithms first to ensure we aren't introducing new edge case bugs.

**Comment by bluebear94** [comment]
I’d say the latter – I didn’t consult any published algorithms for this fix.

**Comment by laurmaedje** [comment]
I think we should first look at existing algorithms, then.

**Comment by bluebear94** [comment]
I managed to find the following descriptions of smart quote algorithms:

* [David Dunham’s algorithm](https://www.pensee.com/dunham/smartQuotes.html) – this seems to be close to the current Typst implementation; the greatest difference is that Typst handles multiple levels of nesting.
* [Dave Jarvis’s KeenQuotes](https://github.com/DaveJarvis/KeenQuotes), described in one of his [StackOverflow answers](https://stackoverflow.com/a/73466438/3130218) – this is an *n*-pass algorithm that tries to handle ambiguous cases.

**Comment by laurmaedje** [comment]
I see that you pushed here 2 days ago. What's the latest state of this?

**Comment by bluebear94** [comment]
This is a rebase onto the latest main branch at the time. The rule implemented by the addition is attested in Dunham’s smart quote algorithm, but I’m not sure that this particular implementation is correct, even though all of the existing test cases pass.

**Comment by laurmaedje** [comment]
Okay, I'll take a closer look when I have a bit of time.

**Comment by laurmaedje** [comment]
This looks sensible, also upon reading Dunham's algorithm. Thanks!

**Pull request merged**
