### PR TITLE
Allow absolute lengths in `scale`

### PR DESCRIPTION
**Pull request by bluebear94**
See #4191.

This is a draft PR because the code is messy. In particular:

* It’s already more code than the rest of the `ScaleElem`’s `LayoutSingle` implementation, and I’m not sure if this is worth the additional complexity.
* If an absolute length is used, then we have to measure the content. This is at least done lazily.
* `scale` with `reflow: true` behaves differently if either `page.width` or `page.height` is `auto`. This problem already exists and arises from `Ratio::of` returning zero if the result would not be finite.
* It would make sense for `scale.x` and `scale.y` to default to `auto` now, but I decided not to do this because it’s a breaking change.

### CODE REVIEW

**Comment by laurmaedje** [comment]
> It’s already more code than the rest of the ScaleElem’s LayoutSingle implementation, and I’m not sure if this is worth the additional complexity.

I think the feature is cool, but we should definitely try to simplify the implementation as much as possible.

> If an absolute length is used, then we have to measure the content. This is at least done lazily.

What I'm wondering is: Do we measure twice now sometimes? Because we measure while resolving the ratio and then again in `measure_and_layout`?

> scale with reflow: true behaves differently if either page.width or page.height is auto. This problem already exists and arises from Ratio::of returning zero if the result would not be finite.

What's the exact problem here? Can we fix it independently of this?

> It would make sense for scale.x and scale.y to default to auto now, but I decided not to do this because it’s a breaking change.

We can break that at the same time where we change `reflow`'s default to `true`.

**Comment by bluebear94** [comment]
> What I'm wondering is: Do we measure twice now sometimes? Because we measure while resolving the ratio and then again in `measure_and_layout`?

Yes. We also use different values for the `regions` parameter’s size each time, so reusing the calculation might pose a problem.

> > scale with reflow: true behaves differently if either page.width or page.height is auto. This problem already exists and arises from Ratio::of returning zero if the result would not be finite.
>
> What's the exact problem here? Can we fix it independently of this?

With `reflow: true` and `page.width` or `height: auto`, the body is measured in a region with zero width or height, leading to the measured dimensions having zero width or height, even though the body might not really have these dimensions.

Here’s an example in Typst 0.11.1:

```typst
#let aaa = {
  set text(size: 28pt)
  let scaled(body) = box(stroke: 0.5pt + red, scale(
    x: 60%,
    y: 40%,
    box(stroke: 0.5pt, clip: false, body)
  ))

  set scale(reflow: false)
  [Hello #scaled[World]!\ ]

  set scale(reflow: true)
  [Hello #scaled[World]!]
}

#set page(width: 200pt, height: 100pt)
#aaa

#set page(width: 200pt, height: auto)
#aaa

#set page(width: auto, height: 100pt)
#aaa

#set page(width: auto, height: auto)
#aaa
```

which results in these four pages:

| Page size | Result |
|-|-|
| `(width: 200pt, height: 100pt)` | Page 1 |
| `page(width: 200pt, height: auto)` | Page 2 |
| `page(width: auto, height: 100pt)` | Page 3 |
| `#set page(width: auto, height: auto)` | Page 4 |

**Comment by laurmaedje** [comment]
> With reflow: true and page.width or height: auto, the body is measured in a region with zero width or height, leading to the measured dimensions having zero width or height, even though the body might not really have these dimensions.

Okay, that sounds like a problem that's fixable separately. We should probably rather measure in an infinite space?

Other than that, how should we proceed with this PR? I think the feature is desirable in principle. I agree that the code could be a bit nicer, but it's also not _that_ messy.

**Comment by bluebear94** [comment]
> Other than that, how should we proceed with this PR? I think the feature is desirable in principle. I agree that the code could be a bit nicer, but it's also not _that_ messy.

I guess I agree with that.

**Comment by laurmaedje** [comment]
I tried to merge with main, but the reference image changed. (The first scaled cylinder got smaller.) Not sure what the cause is.

**Comment by bluebear94** [comment]
> I tried to merge with main, but the reference image changed. (The first scaled cylinder got smaller.) Not sure what the cause is.

I rebased the branch onto a10e332, and the tests passed. When I rebased to 20b8d2c, I got the same test failure, so it must be caused by #4354.

**Comment by laurmaedje** [comment]
Okay, it's probably fine then. You can probably just accept the change.

**Comment by laurmaedje** [comment]
Thank you!

**Comment by istudyatuni** [comment]
I think linked issue could be closed?

**Pull request merged**
