### PR TITLE
Consider switching to `two-face` for extra syntect syntaxes

### PR DESCRIPTION
**Pull request by CosmicHorrorDev**
_Disclaimer: I'm `two-face`'s author_

Currently `typst` embeds bundled syntax definitions generated from the `bat` project. There's the crate [`two-face`](https://crates.io/crates/two-face) that does all the pre-generating and bundling for you while letting you interact with it as a normal crate instead of a weird differently versioned/generated thing. The only trick is that `two-face`'s regex implementation has to match `syntect`

I believe this PR should cover updating everything. Neat test harness btw. The only change I can see with the updated file is likely just due to different points in time where the syntax snapshot get generated. I've highlighted the only part I noticed below

image

### CODE REVIEW

**Comment by laurmaedje** [comment]
Could you say (a) which syntaxes this adds and (b) how this affects binary size?

**Comment by CosmicHorrorDev** [comment]
> (a) which syntaxes this adds

Most syntaxes should be the same, so I'm guessing you just want a brief diff. Let me know if you want a more exhaustive list instead. Here's the diff of the `syntax_ref.name` between `main` and this `PR`

```diff
31a32
>     "DMD Output",
48a50,58
>     "Git Attributes",
>     "Git Commit",
>     "Git Common",
>     "Git Config",
>     "Git Ignore",
>     "Git Link",
>     "Git Log",
>     "Git Mailmap",
>     "Git Rebase Todo",
51a62
>     "Groff/troff",
71d81
<     "JavaDoc",
73a84
>     "Javadoc",
89d99
<     "Man Page (groff/troff)",
91a102
>     "MediaWiki",
93d103
<     "Mediawiki NG",
125a136
>     "Regular Expressions (PHP)",
```

Just guessing from the names its

### Added

- git et. al
- DMD Output (D-lang related thing)
- PHP's regular expressions

### Renamed

- JavaDoc -> Javadoc
- Man Page (groff/troff) -> Groff/troff
- Mediawiki NG -> MediaWiki

### Excluded due to `fancy-regex`

It's worth noting that the syntaxes that can fail with `fancy-regex` are still being excluded

- `02_Extra/Assembly (ARM).sublime-syntax`
- `02_Extra/Elixir/Regular Expressions (Elixir).sublime-syntax`
- `02_Extra/JavaScript (Babel).sublime-syntax`
- `02_Extra/LiveScript.sublime-syntax`
- `02_Extra/PowerShell.sublime-syntax`
- `02_Extra/SCSS_Sass/Syntaxes/Sass.sublime-syntax`
- `02_Extra/SLS/SLS.sublime-syntax`
- `02_Extra/VimHelp.sublime-syntax`
- `02_Extra/cmd-help/syntaxes/cmd-help.sublime-syntax`

This exclusion happens automatically while generating the syntax set

> (b) how this affects binary size?

`two-face` relies on the same trick that `syntect` does with embedded assets where you rely on the linker to remove the unused ones. `two-face` by itself is very lightweight, so the main difference should just be from the size difference in the embedded assets. Doing a quick check of the release binary size seems to confirm that this is the case too

| What? | `main` (MiB) | This PR (MiB) | Delta (MiB) |
| :---: | :---: | :---: | :---: |
| Embedded syntax set | 0.66 | 0.79 | 0.13 |
| `cargo b -r --bin typst` | 31.16 | 31.31 | 0.15 |

**Comment by laurmaedje** [comment]
So the main benefit is not needing the syntax file here in the repository?

**Comment by CosmicHorrorDev** [comment]
Yup. The main benefit is that it's now just a regular crate to update

**Comment by laurmaedje** [comment]
I see. We're considering to have more elaborate infrastructure for lazy loading of assets (like this or also CSL styles, hyphenation patterns, etc.), which would allow us to keep the WASM size down for our web app. However, in the meantime, I agree that this is a simplification, so I'm gonna go ahead and merge. Thanks!

**Pull request merged**
