### PR TITLE
Add algebra symbols

### LINKED ISSUE #309: Symbol ⊴
This is a symbol that is commonly used in Algebra to represent normal subgroup. I think it makes sense to add it to the symbol list

### PR DESCRIPTION
**Pull request by rpitasky**
Fixes #309 with `tri.l.eq`.

I made a distinction between decorative `triangle`s and mathematical `tri`s; I feel this warrants some consideration and discussion before the final merge. Note the renaming of some symbols in `times`..

### CODE REVIEW

**Comment by laurmaedje** [comment]
How about renaming `tri` to `subgroup`? Would that make sense?

**Comment by rpitasky** [comment]
Unfortunately these symbols are used more generally throughout algebra;
most notably for ideals in ring theory.

**Comment by laurmaedje** [comment]
This was the thing where I wanted your opinion, @dccsillag.

**Comment by dccsillag** [comment]
Rule of thumb, I tend to strongly prefer more "semantic" symbol names -- using them means that the .typ source code is closer to the math that the user intends to write.

Unfortunately, I'm not that familiar with abstract algebra. From searching for where these symbols are used, the best I could find is https://math.stackexchange.com/a/148170/497795 (along with many places that indicated the lack of use of these symbols). Of course, we should support them even if they aren't commonly used.

From the best I could gather, the `tri`s seem quite similar to what `lt` or `gt` would be (which, BTW, maybe should be named `less` and `greater`? But let's worry about that later). So how about placing them inside those hierarchies instead of creating a new toplevel `tri`? E.g., `tri.l` -> `lt.tri`, `tri.r` -> `gt.tri`.

As for the ones in `times`, I think those look good (actually, I think they are a bit weird in `times`, but considering some of the other stuff that fits there like `times.triangle` along with their semantic meaning, I think it's quite fine).

**Comment by rpitasky** [comment]
Makes sense, I completely agree now.

An additional consideration: I think it's a little unpalatable to require
people to remember the order of subcategories when there are so many of
them. Perhaps we could switch to a system where `a.b.c = a.c.b` and the
subcategories function more as "tags" than a hierarchy. I imagine it's
possible to resolve any potential ambiguity problems with better naming.

**Comment by dccsillag** [comment]
> An additional consideration: I think it's a little unpalatable to require
> people to remember the order of subcategories when there are so many of
> them. Perhaps we could switch to a system where `a.b.c = a.c.b` and the
> subcategories function more as "tags" than a hierarchy. I imagine it's
> possible to resolve any potential ambiguity problems with better naming.

I quite agree (a priori), but need to think about what complications may arise by doing that.

**Comment by rpitasky** [comment]
Alright, I’m a fool; I should have checked. Laurenz pointed out that this
is already the case >.>

**Comment by laurmaedje** [comment]
> So how about placing them inside those hierarchies instead of creating a new toplevel tri?

I like it (although I can't really judge with my limited maths knowledge)

**Comment by laurmaedje** [comment]
What's the state of this?

**Comment by rpitasky** [comment]
I'm extremely busy, I'll implement the proposed changes my Friday afternoon.

**Comment by rpitasky** [comment]
This is ready @laurmaedje

**Pull request merged**
