### PR TITLE
Document integer literal parsing

### LINKED ISSUE #2284: Min integer value gets parsed as a float
### Description

According to the Typst documentation https://typst.app/docs/reference/foundations/int/ the smallest integer is `-9223372036854775808` but when using the literal for that number it gets parsed as a `float` instead of an `integer`. The value can still be obtained through arithmetic:

```typ
#let literal_min_int = -9223372036854775808  // parsed as float
#let real_min_int = -9223372036854775807 - 1

#type(literal_min_int) // float

#type(real_min_int) // integer
```

### Reproduction URL

https://typst.app/project/rb52J82NefdZ4oTOE3ODK_

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by jakobjpeters**
Closes #2284

### CODE REVIEW

**Comment by PgBiel** [comment]
To be honest, besides the documentation addition, I'd also prefer to add a warning when using a literal that is out of bounds. This behavior seems too unpredictable to me, as is.

**Comment by jakobjpeters** [comment]
It looks like it happens [here](https://github.com/typst/typst/blob/5c37a1cfea2a08b08f4af34ba867748fd90c687e/crates/typst-syntax/src/lexer.rs#L745-L756). Can you give a hint about how to implement such a warning? Or alternatively, produce an error suggesting the user to use a `float` instead.

**Comment by wrzian** [comment]
We don't yet have any real infrastructure for adding warnings to the parser (I ran into this as well in #5229). We do have error infrastructure, so we could also just start by erroring on out-of-bounds literals. If we do want warnings, then there are many ways we could do so.

One way to add parser warnings may be to add a `Warning` variant to the `SyntaxKind` enum and extend the options for `SyntaxNode::Repr` to include warnings and an interface for creating them. Warning nodes could then transparently wrap an underlying `SyntaxNode` plus the warning and any hints, and we would expose a new set of functions from `SyntaxNode` to access them.

However, I would recommend that we discuss if this is the right design before starting to implement it. Best would be to join the contributors channel on Discord, but we could also continue here (maybe in a new issue).

And if you want any help talking through the parser infrastructure, let me know!

**Comment by laurmaedje** [comment]
Thanks!

Since implementing a warning is a little more complex, let's not block this on it.

**Pull request merged**
