### PR TITLE
Disallow block comments before markers

### PR DESCRIPTION
**Pull request by frozolotl**
Correctly parsing headings, lists, enums, and terms can be difficult for both humans and computers, if a comment is placed in front.

An example that is difficult to parse for humans would be:

```typ
- foo
  - bar
    /* comment
*/- baz
```

See #762 for more examples.

However, this change is primarily motivated by the difficulty in parsing such expressions using [tree-sitter](https://github.com/frozolotl/tree-sitter-typst).
Producing useful and consistent syntax trees is quite difficult due to limitations of the tool.

I don't think this change will cause much breakage.
Comments before markers seem niche and not very useful to me.

### CODE REVIEW

**Comment by HarmoGlace** [comment]
I don't think that this is a good idea. In. my opinion, it is sometimes very useful to select a block of text and comment it when working on a project.

If you disallow this, it'll become way more painful to quickly see how a typst document outputs when removing a specific part.

**Comment by laurmaedje** [comment]
I commented on #762. I agree that things are a bit wonky, but I'm not sure whether this is the solution or whether a better solution would be to ignore comments for indent purposes (as if each character and the comment markers were whitespace). That would make some of the examples clearer to parse for humans imo. Would it help with tree-sitter?

**Comment by frozolotl** [comment]
Writing a response to @laurmaedje's comment gave me an idea on how to correctly parse markers.
That means, after many hours of trying to make it work, I was able to write a functioning parser that allows for block comments in front of headings.
Without any major drawbacks!
syntax highlighting headings

As it is right now, I know of two bugs with the implementation. One of them likely existed earlier already. Neither should be hard to fix.

> I commented on #762. I agree that things are a bit wonky, but I'm not sure whether this is the solution or whether a better solution would be to ignore comments for indent purposes (as if each character and the comment markers were whitespace). That would make some of the examples clearer to parse for humans imo. Would it help with tree-sitter?

Yes, I would suppport that change. It would make the syntax easier for humans to reason about and doesn't seem difficult to parse.

**Comment by laurmaedje** [comment]
Alright, then let's do that change.

**Pull request closed without merging**
