### PR TITLE
Caption position (#1495)

### LINKED ISSUE #1495: Control caption position in figure
### Description

`figure` should get a parameter of type `vertical alignment` taking either `top`, `bottom` or `auto` which controls the caption position.

```rust
#figure(table(...), caption-position: top)
```

#491 made figures smarter, allowing how caption supplements and numbering are chosen to depend on their content. This is why, I think, the parameter should by default be set to `auto` and infer the position based on it's content:
| element       | chosen default        |
| ------------- | --------------------- |
| `table`       | `top`               |
| `raw`/`image` | `bottom`            |
| other         | `bottom` by default |

### Use Case

Captions being at the top of a `table` but at the bottom of `raw` or `image` is fairly standard in academic papers. Changing the order should not require a `show` rule, in which the complete standard figure layout has to be recreated manually.

### PR DESCRIPTION
**Pull request by epbuennig**
Fixes #1495

---

This PR adds a `caption-pos` to `figure` which determines whether to put the caption above or below the `body`.
The parameter accepts `top` or `bottom`, defaulting to `bottom`:
- `top` - put the caption before the body
- `bottom` - put the caption after the body

Putting the caption of a table above the table is common enough that it should be easy to configure. If the caption should not be above or below the table, a show rule can be used, as this is much less common than above/below.

### CODE REVIEW

**Comment by lphoogenboom** [comment]
Personally, I would change ```auto``` to ```inherit```, as in that it will inherit from what it set in the template, or what is standard for the type, such as tables have top captions, etc.

**Comment by PgBiel** [comment]
> Putting the caption of a table above the table is common enough that it should be the default.

I think having `bottom` be the default for all kinds (and dropping the `auto` option) is more predictable and consistent w.r.t. the other figure kinds. If your style mandates captions at the top of tables, then changing the option introduced by this PR in your template should be the way to do it (and is also more explicit).

**Comment by epbuennig** [comment]
> Personally, I would change `auto` to `inherit`, as in that it will inherit from what it set in the template, or what is standard for the type, such as tables have top captions, etc.

I'm not sure if I understand this, if a template wishes to set this parameter, then it can do so by using something like thr following:
```rust
#let template(c) = {
  set figure(caption-position: top)
  c
}
```

> > Putting the caption of a table above the table is common enough that it should be the default.
> 
> I think having `bottom` be the default for all kinds (and dropping the `auto` option) is more predictable and consistent w.r.t. the other figure kinds. If your style mandates captions at the top of tables, then changing the option introduced by this PR in your template should be the way to do it (and is also more explicit).

I figured that having the most common style be the default would make sense, but I think you're right, this also reduces complexity.

I'd still like to hear your opinion on `caption-pos` vs `caption-position`.

**Comment by PgBiel** [comment]
> I'd still like to hear your opinion on `caption-pos` vs `caption-position`.

Well, I admit I am kind of torn on this one. For one, `caption-pos` does feel more "convenient" and less verbose, but also less explicit. On the other hand, `caption-position` is as explicit as it gets, but also feels quite verbose. Either way, for now, I'm leaning more towards just "pos", but Laurenz should have the final word here.

**Comment by laurmaedje** [comment]
From the available options, I prefer `caption-pos`. But perhaps it could also be `set figure.caption(position: top)`? Then we could also have `show figure.caption` to customize just that. The details of that caption element would need some thinking though. This idea was floated before. It's not something I'm sure about, but I wanted to bring it up again.

Regarding `auto` vs `top`. It's unfortunately not easy for a template to adjust the property just for tables because `show figure.where(kind: table): set figure(caption-pos: top)` doesn't work at the moment. That's a bug though and we probably shouldn't design around it here. 

More generally, I'm increasingly unsure about the whole table being in figures thing. It does deduplicate some stuff, but is confusing for beginners, complicates show rules, counters, etc.

**Comment by PgBiel** [comment]
> From the available options, I prefer `caption-pos`. But perhaps it could also be `set figure.caption(position: top)`? Then we could also have `show figure.caption` to customize just that. The details of that caption element would need some thinking though. This idea was floated before. It's not something I'm sure about, but I wanted to bring it up again.
> 
> Regarding `auto` vs `top`. It's unfortunately not easy for a template to adjust the property just for tables because `show figure.where(kind: table): set figure(caption-pos: top)` doesn't work at the moment. That's a bug though and we probably shouldn't design around it here.

Actually, the `figure.caption` idea seems pretty reasonable, and also more ergonomic, with the added bonus of enabling show rules directly on it. I like it!

> More generally, I'm increasingly unsure about the whole table being in figures thing. It does deduplicate some stuff, but is confusing for beginners, complicates show rules, counters, etc.

I think this discussion isn't very simple, unfortunately... I think it makes sense to be able to use show rules on all figures for example, including table figures or whatnot. Tables _could_ have a `caption:` option which automatically wraps them in a `figure` though, for example. But this definitely requires further discussion.

**Comment by laurmaedje** [comment]
I think I would be okay with merging `caption-pos` for now. If rework captions in the future, it's probably gonna be a breaking change anyway.

**Comment by epbuennig** [comment]
I'll address the remaining suggestions and merge conflicts today then.

**Comment by epbuennig** [comment]
Merging this into `main` (8711b5eee) locally does not produce any conflicts, not sure why github shows them. I'll resolve them manually on here then.

I opted for changing it to `caption-pos`, as well as going for `bottom` by default and no `auto`.

**Comment by laurmaedje** [comment]
Thank you!

**Pull request merged**
