### PR TITLE
Avoid spaces around ignorant and invisible elements in math

### LINKED ISSUE #4326: Unexpected space in math between invisible element and text
### Description

_(Partially) a regression on main, using 084a0614_

```typ
#let size1 = context measure($ "abc" $)
#let size2 = context measure($ #metadata(none) "abc" $)
#let size3 = context measure($ #metadata(none)"abc" $) // Note missing space
```

In 0.11.1, `size1 == size2 == size3`, but on main `size2 > size1` and `size3 == size1`. This is also visible when rendered:

image

As the metadata element isn't visible, the space between it and the text should not be kept.
The same happens for other invisible elements, such as counter or state updates. _However, with those elements, the space is also there in 0.11.1._

**Addendum:** Another instance of this issue is the fact that the following to sizes are not equivalent. This was also already the case in 0.11.1.
```typ
#let size1 = context measure($ #metadata(none) = 0 $)
#let size2 = context measure($ = 0 $)
```

Maybe related to #4234

### Reproduction URL

_No response_

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by EpicEricEE**
Fixes #4326

I don't know what the intended behaviour is, but I feel like invisible and ignorant elements should not be accounted for when the space between two elements is inserted in an equation.

I have to admit that I don't really like the growing list of fields on the `FrameFragment` struct but it seemed to be the easiest way.

### CODE REVIEW

**Comment by bluebear94** [comment]
Does this fix #3727 as well? In particular, do all three of the following lines display identically?

```typ

#let test = context math.class("relation", "--")
$ a test b $

$ a class("relation", "--") #metadata("hi") b $

$ a class("relation", "--") b $
```

**Comment by EpicEricEE** [comment]
They all look identical, but I'm not sure if it's correct as it doesn't look centered.

image

**Comment by laurmaedje** [comment]
Why another field instead of just setting `spaced` to `false` for ignorant/invisible?

**Comment by EpicEricEE** [comment]
Because then it wouldn't be truly ignorant but just like a `normal` class frame which influences the spacing between neighboring frames, e.g. `vary` class operators would become binary in the test cases
```typ
// Operator spacing
$#counter("test").update(3) + b$ \
$#place(dx: 5em)[a] + b$
```

**Comment by laurmaedje** [comment]
Okay.

> I have to admit that I don't really like the growing list of fields on the FrameFragment struct but it seemed to be the easiest way.

Me neither, but I guess one more field won't change anything.

If you could fix the conflict, I'll merge.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
