### PR TITLE
Gradient fills

### PR DESCRIPTION
**Pull request by ollelogdahl**
Related to https://github.com/typst/typst/issues/443.

### CODE REVIEW

**Comment by PgBiel** [comment]
Should probably mark this as draft if it's WIP

**Comment by saadulkh** [comment]
Will this support exponential and other kind of gradients or just linear ones?

**Comment by laurmaedje** [comment]
What's the status of this?

**Comment by laurmaedje** [comment]
Hey @ollelogdahl, do you still want to work on this in the future or should someone else pick it up?

**Comment by ollelogdahl** [comment]
@laurmaedje Still in my backlog! Been occupied with courses until now, should be able to finish it sometime in June. If it's not high priority I would like to work on it!

**Comment by laurmaedje** [comment]
Info: Significant work on gradients is currently underway by @Dherse.

**Comment by LaurenzV** [comment]
I suppose this PR can be closed then?

**Pull request closed without merging**
