### PR TITLE
Added more detail to buld process

### PR DESCRIPTION
**Pull request by KronosTheLate**
Being explicit about the need to clone the repo and change the current directory.

### CODE REVIEW

**Review by CGMossa — APPROVED** [review]

**Comment by CGMossa** [comment]
Please note that I'm in no way part of the team. I'm just giving my community member review. It helps other projects, but I could be both factually wrong, and my opinions may be opposite of the typst team.

**Comment by laurmaedje** [comment]
If you're a technical enough person to building a project from source, isn't it obvious that you first have to somehow download it?

**Comment by alerque** [comment]
It might be obvious that you need to *somehow* get the source, but it is *not so obvious* that you can't just get it anyhow, you must get it via a Git Clone. At least without extra workarounds, it will not build from the regular GitHub provided (`git archive` generated) source tarballs or zips.

This can be worked around (as for example I did in [Arch Linux packaging](https://github.com/archlinux/svntogit-community/blob/packages/typst/trunk/PKGBUILD#L19)) by modifying the `cli/build.rs` file, bit the current project layout is not robust enough to build from just a source archive, it expects to have Git history just to build.

I don't know if this explanation is necessary, I would just fix the build to be more robust in the first place (i.e. use the [vergen](https://crates.io/crates/vergen) crate which can robustly derive the version from a combination of the Cargo manifest, Git repo status, and environment variables).

**Comment by laurmaedje** [comment]
> This can be worked around (as for example I did in [Arch Linux packaging](https://github.com/archlinux/svntogit-community/blob/packages/typst/trunk/PKGBUILD#L19)) by modifying the cli/build.rs file, bit the current project layout is not robust enough to build from just a source archive, it expects to have Git history just to build.

Is that still a problem? The build script should just say "(unknown hash)" if git is not available and the `TYPST_VERSION` environment variable can be overridden. If there's still a problem anyway, please tell me so we can fix it.

**Comment by KronosTheLate** [comment]
> If you're a technical enough person to build a project from source, isn't it obvious that you first have to somehow download it?

I was able to build it, but just because I had buildt something else one or two days in advance. And **only because the other program provided such instructions**. Not providing full instructions because people are just expected to know feels a bit like gatekeeping.

**Comment by laurmaedje** [comment]
I added this to the readme.

**Pull request closed without merging**
