### PR TITLE
"Key interpolation not allowed" hint

### PR DESCRIPTION
**Pull request by mattfbacon**
This hint might be helpful in some cases. In its current state it's a bit noisy. Up to you whether this makes sense.

### CODE REVIEW

**Comment by PgBiel** [comment]
This seems innapropriate for function calls, as key interpolation is exclusive to dicts IIUC :thinking:

**Comment by laurmaedje** [comment]
> This seems innapropriate for function calls, as key interpolation is exclusive to dicts IIUC 🤔

Agreed

**Comment by mattfbacon** [comment]
Any way to determine whether we are in a context where the hint should be emitted?

**Comment by laurmaedje** [comment]
I think at this place in the code it's not possible. `#let f(1: 1)` could be recognized, but `(1: 1) => ..` and `(1: 1)` can't be distinguished there. It would probably have to be moved to the validation functions.

**Comment by laurmaedje** [comment]
@mattfbacon do you still want to finish this or should it be closed?

**Comment by mattfbacon** [comment]
I think it's too hard to properly detect whether it's valuable.

**Pull request closed without merging**
