### PR TITLE
Math layout: Don’t add frames for MetaElems

### PR DESCRIPTION
**Pull request by bluebear94**
See #3727

The tests still pass, but this is probably not the correct solution. Wondering if there’s another way to fix this.

### CODE REVIEW

**Comment by laurmaedje** [comment]
This will indeed break introspection in math, e.g.:
```typ
$ #metadata("hi") $
#context query(metadata)
```
To fix it properly, MetaElem::data probably needs to be handled in better non-frame way by the math layout.

**Comment by bluebear94** [comment]
For some reason, `$ a class("relation", "--") #metadata("hi") b $` also produces incorrect spacing in the current development version (though not in 0.11).

**Comment by bluebear94** [comment]
Also, `Content::layout_math` flattens nested sequence elements, but it can’t see through realization steps (context blocks, `Show` implementations). I wonder if a more general solution is needed, perhaps assigning a behavior to each `MathFragment`.

**Comment by bluebear94** [comment]
Fair enough; do you want to close this for now since the underlying issue would be solved by unifying math realization with the proper one?

**Comment by laurmaedje** [comment]
Yeah, let's close this for now.

**Pull request closed without merging**
