### PR TITLE
Rename existing symbols (`≽`, `⋡`, `≼`, `⋠`), add new symbols (`⪰`, `⪲`, `⪯`, `⪱`), remove all `{lt,gt}.curly*` symbols for consistency

### LINKED ISSUE #4057: Add named symbols to represent `⪰`, `⪲`, `⪯`, `⪱`
### Description

This is a feature request from https://discord.com/channels/1054443721975922748/1235249773876084778

Specifically, it requests a new named symbol (like `#sym.arrow`) to represent `⪰`, `⪲`, `⪯`, `⪱`.

We discussed their proper names here (https://discord.com/channels/1054443721975922748/1088371867913572452/1235512693532921857), and here is the core part of the proposal:
- rename some existing symbols (to follow LaTeX design)
  - `succ.eq` to `succ.curly.eq`
  - `succ.eq.not` to `succ.curly.eq.not`
  - `prec.eq` to `prec.curly.eq`
  - `prec.eq.not` to `prec.curly.eq.not`
- name `⪰`, `⪲`, `⪯`, `⪱`:
  - `succ.eq` represents `⪰`
  - `succ.neq` represents `⪲`
  - `prec.eq` represents `⪯`
  - `prec.neq` represents `⪱`

### Use Case

With this new feature, we can use something like `#sym.succ.eq`... to represent `⪰`.

*NOTE*: This feature intros breaking changes on the four existing symbols.

### PR DESCRIPTION
**Pull request by Coekjan**
This pr closes #4057. This feature could be demonstrated in the following table. Specifically, this pr renames 4 existing symbols, adds 4 new symbols and removes all `{lt,gt}.curly*` symbols for consistency:
- rename some existing symbols (to follow LaTeX design)
  - `succ.eq` to `succ.curly.eq`
  - `succ.eq.not` to `succ.curly.eq.not`
  - `prec.eq` to `prec.curly.eq`
  - `prec.eq.not` to `prec.curly.eq.not`
- name `⪰`, `⪲`, `⪯`, `⪱`:
  - `succ.eq` represents `⪰`
  - `succ.neq` represents `⪲`
  - `prec.eq` represents `⪯`
  - `prec.neq` represents `⪱`

```typ
#align(center, table(
  columns: 5,
  align: center + horizon,
  [], table.cell(colspan: 2)[In Markup Mode], table.cell(colspan: 2)[In Math Mode],
  table.cell(rowspan: 4)[Renamed],
    ```typst #sym.prec.curly.eq```, sym.prec.curly.eq, ```typst $prec.curly.eq$```, $prec.curly.eq$,
    ```typst #sym.prec.curly.eq.not```, sym.prec.curly.eq.not, ```typst $prec.curly.eq.not$```, $prec.curly.eq.not$,
    ```typst #sym.succ.curly.eq```, sym.succ.curly.eq, ```typst $succ.curly.eq$```, $succ.curly.eq$,
    ```typst #sym.succ.curly.eq.not```, sym.succ.curly.eq.not, ```typst $succ.curly.eq.not$```, $succ.curly.eq.not$,
  table.cell(rowspan: 4)[New],
    ```typst #sym.prec.eq```, sym.prec.eq, ```typst $prec.eq$```, $prec.eq$,
    ```typst #sym.prec.neq```, sym.prec.neq, ```typst $prec.neq$```, $prec.neq$,
    ```typst #sym.succ.eq```, sym.succ.eq, ```typst $succ.eq$```, $succ.eq$,
    ```typst #sym.succ.neq```, sym.succ.neq, ```typst $succ.neq$```, $succ.neq$,
))
```

image

### CODE REVIEW

**Comment by Coekjan** [comment]
The name of them need to be discussed in #4059

**Comment by Coekjan** [comment]
The fuzz failure seems to be relative to #4056

**Comment by naoppy** [comment]
I found `succ.eq` also shows ≽.
So I think to add `succ.seq` is good idea.

**Comment by naoppy** [comment]
Latex use `\succeq` as `⪰`, so `succ.seq` is good for latex users.

**Comment by Coekjan** [comment]
> Latex use `\succeq` as `⪰`, so `succ.seq` is good for latex users.

See https://discord.com/channels/1054443721975922748/1088371867913572452/1235512693532921857. I discussed their names with @Enivex and updated the pr.

**Comment by naoppy** [comment]
Symbols above are defined as "Supplemental Mathematical Operators" in Unicode. It means these symbols are quite common.
https://en.wikipedia.org/wiki/Mathematical_operators_and_symbols_in_Unicode#Supplemental%20Mathematical%20Operators%20block

**Comment by laurmaedje** [comment]
I'm not sure whether `prec.curly` makes sense because already `prec == lt.curly`, so it would be double curly?

**Comment by Coekjan** [comment]
> I just read up on the Discord discussion and there @Enivex was in favor of removing `lt.curly`. That might make sense and would fix the problem noted above.

So, if I got it correctly, we should remove those redundant names in this pr?

**Comment by Enivex** [comment]
> I just read up on the Discord discussion and there @Enivex was in favor of removing `lt.curly`. That might make sense and would fix the problem noted above.

Precisely, I think the other names should be removed. I've forgotten where I written what at this point...

**Comment by Coekjan** [comment]
I removed `lt.curly.eq` and `gt.curly.eq` just now. Should this pr further remove (and rename) all `{lt,gt}.curly.*`?

**Comment by Enivex** [comment]
> I removed `lt.curly.eq` and `gt.curly.eq` just now. Should this pr further remove (and rename) all `{lt,gt}.curly.*`?

I would say yes, for consistency. Those are all accessible with prec or succ, respectively

**Comment by Coekjan** [comment]
All done. Please review my changes :)

**Review by Enivex — COMMENTED** [review]
Looks good to me

**Comment by laurmaedje** [comment]
Thanks to both of you!

**Pull request merged**
