### PR TITLE
Fix numbering documentation

### PR DESCRIPTION
**Pull request by emilyyyylime**
Reformatted long lines, added missing mentions to circled numerals, replaced special double quotes with ascii quotes in internal docs, and a small reword

### CODE REVIEW

**Comment by laurmaedje** [comment]
While you are at it, could you wrap the lines at 80 columns?

**Comment by emilyyyylime** [comment]
Sure thing. I thought you were trying for 100 so that's where I wrapped them

**Comment by emilyyyylime** [comment]
Hm. Does 80 columns mean 80 glyphs in this case? In my setup at least many of the foreign characters appear as double-width. I'm leaning towards counting them as a single column because they could theoretically be displayed that way

**Comment by laurmaedje** [comment]
80 columns for me means whatever happens with the VS Code rewrap extension and a ruler at 80 😅

I would say probably glyphs. For me, most stuff appears single column.

**Comment by emilyyyylime** [comment]
Also it seems rustfmt formats the long arrays at 80 characters too (even though the maximum width is 100 :thinking:)

**Comment by laurmaedje** [comment]
Max width should be 90 for rustfmt

**Comment by emilyyyylime** [comment]
Ah, in that case looks like it actually does consider those characters as double-wide

**Comment by emilyyyylime** [comment]
The GitHub 'changes' view just falls back to a proportional font for those characters (at least on Firefox)

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
