### PR TITLE
Add support for Croatian quotes

### PR DESCRIPTION
**Pull request by Carbophile**
Add support for Croatian quotes to smartquote.rs pursuant to [punctuation rules](http://pravopis.hr/pravilo/pravopisni-znakovi-u-upravnome-govoru/72/)

### CODE REVIEW

**Comment by PgBiel** [comment]
Thanks, is there a source for the single quotes as well?

**Comment by Carbophile** [comment]
> Thanks, is there a source for the single quotes as well?

Oh, my bad. [Here it is](http://pravopis.hr/pravilo/polunavodnici/73/).

**Comment by Carbophile** [comment]
Small mistake with the single quote orientation, it's good now

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
