### PR TITLE
Improve alignment of text inside raw blocks

### PR DESCRIPTION
**Pull request by PgBiel**
Right now, if you try to center a raw block (for example), it will center each line inside the raw block as well, which is usually undesirable. This PR adds an `align:` option to `raw`, which specifies the alignment of text inside the raw block, which overrides the alignment of the raw block itself. By default, it is set to `align: start` (text is start-aligned even if the raw block is center- or end/left/right-aligned), but it can also be set to `align: auto` to keep the old behavior of inheriting alignment from the context.

Tests were added.
Before this PR:
image
After this PR: (the second and third raw blocks have `align: right` and `align: auto` respectively)
(**EDIT:** The `align: auto` option was removed upon discussion.)
image

### CODE REVIEW

**Comment by Julian-Wollersberger** [comment]
About the naming, wouldn't it be better to call it `align: inherit` instead of `align: auto`? To me, `auto` sounds like it would chose an option based on some heuristic or a default set elsewhere. `inherit` more clearly describes what will be done.

**Comment by Julian-Wollersberger** [comment]
Makes sense, then I misunderstood it a bit.

**Comment by PgBiel** [comment]
It's fine, don't worry. Though I'm not strictly against the addition of such `inherit` value for better clarity, but it will probably need some additional discussion elsewhere.

**Comment by laurmaedje** [comment]
Some thoughts:
- The example should motivate better when this property would be set to a non-default value. If there is no good example, perhaps raw blocks should always default to start/left alignment?
- How is this different from `show raw.where(block: true): set text(align: ...)`
- I'm wondering how code works in RTL. If raw blocks themselves are never actually RTL (even in RTL documents), the configuration makes little sense
- Does vertical alignment make sense here at all?

Overall, I'm wondering whether this configuration knob makes sense or whether raw blocks should just default to left or start align (not sure which of the two).

**Comment by PgBiel** [comment]
>  The example should motivate better when this property would be set to a non-default value. If there is no good example, perhaps raw blocks should always default to start/left alignment?

I think it should be possible to override the configuration either way, as raw blocks can be used for other purposes than code (and such alignment is overridable today, through what I believe to be some sort of hack). Though I agree start should be the default.

>  How is this different from `show raw.where(block: true): set text(align: ...)`

This didn't seem to work for me, is there a previous step here? (There doesn't seem to be an `align` property on `text`)

>  I'm wondering how code works in RTL. If raw blocks themselves are never actually RTL (even in RTL documents), the configuration makes little sense

I highly doubt raw blocks are _never_ RTL - especially in RTL documents, since raw blocks can be used for purposes other than code. One may wish to use it to format other kinds of text which would likely be in RTL (just see the many uses of raw blocks in Discord).

>  Does vertical alignment make sense here at all?

Probably not; I'll attempt to restrict it in a future commit (thanks for the suggestion!).

> Overall, I'm wondering whether this configuration knob makes sense or whether raw blocks should just default to left or start align (not sure which of the two).

I think it should be configurable somehow, even if through show-set rules (although I don't think an option on `raw` itself is that bad), but defaulting to start align to be at least somewhat consistent with what one would expect right now (though the choice here shouldn't really matter if we make it configurable).

**Comment by PgBiel** [comment]
> Sorry, I meant `show raw.where(block: true): set align(...)`.

Oh, right. I should have made this comparison explicit in the PR message, sorry. That doesn't work (and was the first thing we tried in the Discord), because the text is wrapped in a block at the end of the `raw`, so that show-set will align the whole raw block, not just its text (but including it). That's why the raw block itself has to handle the alignment of its text.

Ideally, we'd have a "text.in(raw)" kind of selector, which would fix this issue for other similar elements too (if they ever arise), but I assume that's currently blocked by the content rework. So this (using an option in `raw`) was the best compromise I could think of.

However, I think that maybe the option's naming (if it is indeed added) could be a bit more explicit. Perhaps I could change it from "align" to "text-align"?

> I'm fine with that, but if possible I'd prefer a show-set rule (less properties overall, more composability). This is again a job for `Finalize` then.

Yeah, the lack of a child selector is pretty significant here... I wonder if there is a workaround that would make the raw block itself immune to alignment from a show-set done directly on the raw? But then it could break context alignment of the block... not sure how to best implement this, other than the PR's way atm.

**Comment by laurmaedje** [comment]
That's unfortunate. Well, the option in raw seems okay then sans vertical. I'm also not sure whether `auto` is worth having here if it's not even the default.

**Comment by PgBiel** [comment]
Okay, changes made. I add that I cherry-picked my implementation for `HorizontalAlign` and `VerticalAlign` in `align.rs` (in `src`) from my other PR (#1042), since they're pretty much the exact same. I note that `VerticalAlign` is only there for completeness, so I can remove it if needed (but it might come useful in the future, I guess).

**Pull request merged**
