### PR TITLE
Fix `pow` overflow

### PR DESCRIPTION
**Pull request by HarmoGlace**
This PR fixes an overflow caused by the `pow` method. For instance, `#calc.pow(2, 2147483647)` would make the compiler crash before.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Fastest merge in town :D

**Comment by HarmoGlace** [comment]
That was really fast!

**Comment by laurmaedje** [comment]
Thanks for your work on `calc`!

**Comment by HarmoGlace** [comment]
You're welcome!

**Pull request merged**
