### PR TITLE
Introduce second variant of Ignorant Behaviour and prevent weak page breaks at basically empty pages

### LINKED ISSUE #1346: weak pagebreak after page counter update always adds pagebreak
### Description

When adding a `pagebreak(weak: true)` after an update of the page counter the pagebreak will always be inserted even if the page is empty.

**To reproduce:**
```
#counter(page).update(1)

#pagebreak(weak: true)
= Page 1

#pagebreak(weak: true)
= Page 2
```

I would expect no pagebreak to be inserted as there is no visible content on the page before the pagebreak.

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by Beiri22**
This is inspired by and in some way alternative to #1500 and also attempts to fix #1346.

Stands for discussion.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Moreover, I think a fifth Behaviour would be more fitting. The idea behind `Ignorant` is mostly that is a normal element but doesn't interact with other elements. But this is different. Perhaps `Invisible`?

**Comment by Beiri22** [comment]
ok.

**Comment by Beiri22** [comment]
Have a look.

**Comment by Beiri22** [comment]
Please consider https://github.com/typst/typst/pull/1997 to calm clippy down even more and get a test pass...

**Comment by Beiri22** [comment]
the fmt error is addressed in #1999

**Comment by Beiri22** [comment]
@laurmaedje You are deeper inside the code ... Are there any open concerns with this implementation?

**Comment by laurmaedje** [comment]
I haven't yet merged because I wanted to carefully review to check whether it works as intended. I probably won't have time to do that in the next few days (I'm travelling at the moment), but hopefully next Wednesday or so.

**Comment by laurmaedje** [comment]
I experimented a bit with it and thought a bit about it and it seems to work correctly. Thanks!

**Comment by laurmaedje** [comment]
This PR broke the following snippet:
```typ
#pagebreak(weak: true)
#bibliography("...")
```
It nows fails with "the document does not contain a bibliography" because the weak pagebreaks stops the basically empty page after it from being used and then the bibliography metadata just vanishes into the void.

Indepently of this PR, the following snippet produces a Typst document _without pages:_
```typ
#pagebreak(weak: true)
```
Unfortunately, the whole code around this is quite brittle. :/

**Comment by Beiri22** [comment]
So better revert for now and create a set of tests first that have to pass?

**Comment by laurmaedje** [comment]
I would rather not revert, as that would regress the other bug that was fixed by this, which also isn't great. I hope we can find a way to fix this / make it good enough. Medium-term this all needs a refactoring ...

**Comment by Beiri22** [comment]
Ok. What behaviour is bibliography? As the changeset was not large, it might be not too difficult to find with the debugger.

**Comment by laurmaedje** [comment]
The relevant thing is `MetaElem` because the `Bibliography` itself generates no content in the first introspection iteration. But every locatable element generates a `MetaElem` exactly for that case. So it's `Invisible`. The problem is with the `is_basically_empty` in `interrupt_page`. I'm not yet sure how a good fix would look like though.

**Comment by Beiri22** [comment]
Sure? I'm not with an ide or compiler now, but parbuilder seems at least suspicious to me: 
if content.is::<MetaElem>() {
            if !self.0.is_basically_empty() {
                self.0.push(content.clone(), styles);
                return true;
            }

**Comment by laurmaedje** [comment]
Both might be problematic, but the pagebreak is definitely more problematic because if you replace that `is_basically_empty` for it with a version that doesn't ignore Invisible elements, it works again. the same doesn't hold true for replacing the par builder one.

**Comment by laurmaedje** [comment]
That would probably break the `location.position()` method and links because suddenly a metadata element after some spacing ends up before it.

**Comment by Beiri22** [comment]
As far as I understand, the staged items are never simply deleted. Might there just be missing a final flush of the staged items?

**Comment by Beiri22** [comment]
Or can they be pushed after the page without creating a new page?

**Comment by Beiri22** [comment]
When you put another invisible element at the end of the document, let's say metadata, will that result in an empty page then?

**Pull request merged**
