### PR TITLE
Fixed #1993 counter's "Time travel" doc example

### LINKED ISSUE #1993: Incorrect counter values in `counter` documentation
https://typst.app/docs/reference/meta/counter/#time-travel:

image

image

`1`, `4` and `6` should be `0`, `3` and `5` respectively. Otherwise, instead of clearing things up, it only confuses the reader even more.

### PR DESCRIPTION
**Pull request by Andrew15-5**

### CODE REVIEW

**Comment by laurmaedje** [comment]
Thanks!

**Comment by Andrew15-5** [comment]
I have a question unrelated to the issue itself, but about the commits. There are 2 main ways of merging that I know of:
- as is, which means that the whole PR branch will be present in the commit history of the main repo;
- squash, which means that the whole PR branch will be present as (squashed to) a single commit in the commit history of the main repo.

But what I see (in some cases, including this one) is that my branch actually isn't merged (it is still dangling in my forked repo), but the commit changes are the same. The only two differences is that commiter of the commit is different: initially it was me, but now it is `GitHub <noreply@github.com>`, and that body of the commit message has now ` (#2022)` at the end. And GitHub says that @laurmaedje merged this (GitHub commiter) commit instead of mine.

So here is what I want to know:
- How did the commit message changed with the commiter? How can this be done (which buttons to press) in GitHub (I assume)?
- If I had a ` (#2002)` in the commit message, then would my branch be **really** merged or there would be a new identical commit (by GitHub) anyway?

**Comment by laurmaedje** [comment]
I click "Squash and merge" in the GitHub UI. It presents me with the option to choose a new commit message and it defaults to either the _sole commit message_ of the PR + PR number or the _PR name_ + PR number if the PR has multiple commits. I think if you add ` (#2002)` it wouldn't change anything, probably it would the number would end up showing up twice.

**Comment by Andrew15-5** [comment]
Oh, yeah, that makes sense, thanks.

> I think if you add ` (#2002)` it wouldn't change anything, probably the number would just show up twice.

But you still can change/edit the commit message, so that it wouldn't actually commit with the ` (#2002) (#2002)`.

**Comment by laurmaedje** [comment]
> But you still can change/edit the commit message, so that it wouldn't actually commit with the ` (#2002) (#2002)`.

Yeah, I would do that.

**Pull request merged**
