### PR TITLE
Support indices preceding the base symbol, revamping #699

### PR DESCRIPTION
**Pull request by Leedehai**
Hi this PR adds native support for attaching indices preceding the base symbol ("prescripts", "left index"). This is very useful in denoting isotopes, etc. and mirrors the composition capabilities offered by Latex. For a demo, please see the modified test images.

The modified function signature is `attach(base, top, bottom, topleft, bottomleft, topright, bottomright)`.

This PR fixes https://github.com/typst/typst/issues/690. This PR is the same as the most recent version of my #699, which addressed the comments there, but with a cleaner git history.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Looks good. One thing I've only just realized is that `top-left` (the usual naming convention) isn't a valid identifier in math. So we have to decide whether to change that (probably not because of e.g. `$pi-2$`), keep the current names (hmmm), or say that in math we use something shorter (e.g. `attach(base, t, b, tl, bl, tr, br)`, maybe not that bad?)

**Comment by Leedehai** [comment]
Hi - I'm okay with whatever you decide on. I would slightly prefer not to use short names, and I think the long, full names are acceptable because the backward-compatible `attach(base, top:..., bottom:...)` is enough for most usages -- but not a strong opinion.

**Comment by laurmaedje** [comment]
I don't have a problem with the long names, per se, just with their lack of hyphens as that is the standard naming convention in Typst. That's why I think the shorthands might be good: They are consistent with the idea that math does things in shorter ways.

**Comment by Enivex** [comment]
How about topl, topr, bottoml, bottomr?

**Comment by laurmaedje** [comment]
There was some discussion on Discord. The results are as follows:

- Consensus that none of the solutions is particularly great
- A few people expressed a preference for clarity instead of abbreviations
- Kebab case (`bottom-left`) would be possible, but would make the math arguments parsing even hackier
- Just one word (`bottomleft`) of course works, but is inconsistent with the usual naming conventions in Typst
- Abbreviations like `tr` have precedence with `arrow.tr`

I lean relatively strongly towards one of the following two options:

- The abbreviations. It's (a) consistent with the math symbols like `arrow.tr`, (b) doesn't conflict with the normal kebab-case convention, (c) is compact; all at the price of a little bit of clarity.
- Kebab case with a parser change. This would also be consistent, but require some smartness on the lexer side and make third-party grammars even harder to write. (They are already pretty tricky to write, so one more thing might not matter all that much.)

Regardless of all this, we concluded that top/bottom should automatically become limits if top-right/bottom-right is given (instead of being ignored).

**Comment by Leedehai** [comment]
Thanks all for putting thoughts into this.

I'll follow the conclusion and adapt the PR to (1) use abbreviations `attach(base, t, b, tl, bl, tr, br)` (note it will rename the existing params `top` and `bottom`, so it will be a breaking change -- could you confirm? @laurmaedje), and also (2) top/bottom should automatically become limits if top-right/bottom-right is given (instead of being ignored).

**Comment by rpitasky** [comment]
Make no mistake; I am almost always in favor of explicit names over abbreviations, especially ones that may be particularly opaque. We are long past the days of 80-line teletypes and extremely limited storage for text files. My opinion here should not be taken as precedent without also taking my reasoning as precedent :) 

However, I believe there are many use cases that warrant additional terseness here. Chemistry first came to mind; they love placing superscripts and subscripts all over their chemical symbols. I have also seen them in physics, and (while this is sample size n=1) I’ve had a professor that has some ungodly affinity for them in mathematical logic. For this reason I am in favor in the abbreviated argument names; more than anything, if they’re used at all they are going to be used *a lot*. I think maybe `t` and `b` could afford to be `top` and `bottom` for the sake of clarity on the two most common options, as giving at least *something* a full name provides some context hints for the others.

Have we considered special syntax here, for outside of the function? After all, `^` and `_` exist. I propose `^(a)_(b)C^(d)_(e)` as a first draft (I hope it is obvious where everything goes, or the notation is bad), but I also don’t like drowning the more important character. Using `^^` or `__` for pre-(super|sub)scripts also popped in my head. If some syntax is adopted, I would be in favor of the more explicit names for the functions.

**Comment by mattfbacon** [comment]
Wouldn't the parser change also be backwards-incompatible? I know I have documents that do stuff like `$a-b$`.

**Comment by Leedehai** [comment]
I thought this is a settled conclusion on Discord..

**Comment by rpitasky** [comment]
> Wouldn't the parser change also be backwards-incompatible? I know I have documents that do stuff like `$a-b$`.

Because typst is beta software, I don’t think we’re going to reject a change that moves the language forward solely for backwards compatibility, though it is a consideration. Though this is, of course, something I say with complete deference to the opinions of the founders.

Part of the advantage of typst over latex right now is that we can change things and do stuff *right* instead of just what was decided (no matter how right it seemed) ages ago. LaTeX moves at a glacial pace, and for good reason; there’s no situation more terrifying than “my paper doesn’t compile anymore and I need it submitted tomorrow aaAaaaAAAA”. Such situations would likely cause someone to lose faith in the maintainers of LaTeX, but because typst is firmly beta software, I imagine this is less of an issue.

> I thought this is a settled conclusion on Discord..

Yeah, me too, but new points means further discussion is warranted.

**Comment by Leedehai** [comment]
Just uploaded a new patch where users can freely position the attachments at one or more of the six positions (top-left, top, top-right, bottom-left, bottom, bottom-right).

The previous commit "[Satisfy maintainer #issuecomment-1516330763](https://github.com/typst/typst/pull/825/commits/df25c9eaaca0062db9538b53665c828057f31a31)" does satisfy the two requirements prescribed by https://github.com/typst/typst/pull/825#issuecomment-1516330763, but users are not able to achieve certain configurations, e.g. top-left + top-above.

The new commit "[one step further: put attachments freely at all 6 possible positions](https://github.com/typst/typst/pull/825/commits/e5bb19aa9a70f4444fccdbadac90fe4ca11f9fac)" addressed this problem. Users can freely put attachments at the six positions, while the special syntax `a^b_c` and `lim^b_c` are still smartly rendered as "scripts" or "limits", just like before. If this new commit is not desirable, we can go back to the previous commit.

**Comment by mattfbacon** [comment]
Well I'm just saying that out of the two proposed solutions I prefer the one that isn't a breaking change.

**Comment by laurmaedje** [comment]
> I think maybe t and b could afford to be top and bottom for the sake of clarity on the two most common options, as giving at least something a full name provides some context hints for the others.

I'd prefer to not do that in the name of consistency, especially with `$arrow.t$`.

> Have we considered special syntax here, for outside of the function?

Not yet, but that shouldn't block this PR.

> Wouldn't the parser change also be backwards-incompatible? I know I have documents that do stuff like `$a-b$`.

The parser change would have only affected named arguments in math calls, other math identifiers would have been untouched. That's why it would probably have ended up being a bit hacky. Changing `top` to `t` is of course also a breaking change (although I assume very few people use explicit `attach` in favor of the syntax.) But the bar for improvement to warrant a breaking change is still quite low for now.

All things considered, I'm confident in the abbreviations now and would conclude the discussion. :)

> Just uploaded a new patch where users can freely position the attachments at one or more of the six positions

Very nice! I've looked at the changes and the output looks great! Why did you add a new `SmartAttachElem` though? The idea was to keep just `AttachElem` and `t` and `b` behave smartly by default.

**Comment by Leedehai** [comment]
Thanks!

> Very nice! I've looked at the changes and the output looks great! Why did you add a new SmartAttachElem though? The idea was to keep just AttachElem and t and b behave smartly by default.

The snag mentioned above "users are not able to achieve certain configurations, e.g. top-left + top-above" actually lies in the original behavior "t and b behave smartly by default". Specifically, if user writes `attach(a, tl: x, t: y)` then `y` will appear at the top-right corner, not directly above the base symbol.

To address this issue, we need an `attach()` that is deliberately "not smart", i.e. it puts the attachments where it was told to (as an extra bonus, it could also reduce some user confusion). However, I think we _do_ really want the "smart behavior", especially with the special syntax `a^b_c`/`lim^b_c`, so we need to keep it. My way to keep the smart behavior is letting a `SmartAttachElem` to handle the special syntax, and the original `AttachElem` to handle the "not smart" behavior of faithfully positioning the attachments.

I also considered `attach(base, smart, ...)` where `smart` is a boolean, but that seems to be a bit confusing and unccessary.

**Comment by laurmaedje** [comment]
`attach(a, tl: x, t: y)` is indeed a special case. note though that you _can_ force the `t` to go up with `attach(limits(a), tl: x, t: y)`.

**Comment by laurmaedje** [comment]
we could also go full in and have eight arguments, `tl`, `t`, `tr`, `bl`, `b`, `br` _plus_ two smart ones whose name would again need bikeshedding.

**Comment by Leedehai** [comment]
> We could also go full in and have eight arguments, tl, t, tr, bl, b, br plus two smart ones whose name would again need bikeshedding

I'd like to mention that in addition to bikeshedding the names of the "smart" attachments, we also need to figure out what happens if any of the "smart" ones is set and any of the "non-smart" ones is set _at the same time_. Especially, people may have different opinions with the expected behaviors e.g. when (1) "smart top" and non-smart-but-conflicting `t` are set or (2) "smart top" and non-smart-and-not-conflicting `tl` are set. All of this could compound the complexity..

**Comment by laurmaedje** [comment]
I really don't want a second element. I think I'm in favor of `attach(limits(a), tl: x, t: y)`. The situation should be relatively rare.

**Comment by Leedehai** [comment]
Sure, I'll update the PR to reflect that.

**Pull request merged**
