### PR TITLE
Strip first leading line break in math mode

### PR DESCRIPTION
**Pull request by SUPERCILEX**
This was discussed on discord after the failed https://github.com/typst/typst/issues/786 attempt. I've been using this new style for a bit and I love it! All the formatting is grouped to the left and all the content is to the right. Super clean.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Do you still use this style? Is writing a backslash at the end of the line really such a big hassle?

**Comment by SUPERCILEX** [comment]
Yup! I don't think it's the end of the world if this doesn't go through, but I also don't see what harm stripping the leading line causes either. If anything it's nice and symmetric.

**Comment by SUPERCILEX** [comment]
Deciding code style is the job of a formatter. I don't think we should limit expressivity on the basis that one code style or another is better.

I agree that we shouldn't have two features that do the same thing, but I don't think this falls in that scenario since it's two separate ways of writing an equation.

**Comment by SUPERCILEX** [comment]
Good point, I'll see if I can fix that.

**Comment by laurmaedje** [comment]
How would you fix it? Isn't this simply a conceptual problem?

**Comment by SUPERCILEX** [comment]
Oh, I assumed that we could write similar code to what's in this PR to remove the first empty content block before a `\` in text mode. Not so?

Also, I'm kinda doubting myself now because removing the first `\` in text feels wrong as I don't see why you'd want that behavior. So maybe reject this PR and I can just suck it up? :)

**Comment by laurmaedje** [comment]
Thanks for your understanding. I'm also not 100% sure on this, but I'm tending towards not wanting it.

**Comment by SUPERCILEX** [comment]
Sounds good!

**Pull request closed without merging**
