### PR TITLE
Multilingual bibliography

### PR DESCRIPTION
**Pull request by nrydanov**
This PR is related to https://github.com/typst/hayagriva/pull/126 and issue #3168 and adds support for `language` parameter for each entry to allow using specific terms for entry's origin.

### CODE REVIEW

**Comment by Leedehai** [comment]
"multilingual"? :) 

(wanted to get this right because the PR title will be in the hit history)

**Comment by nrydanov** [comment]
This PR is still in draft (I need to refactor it a bit more), so I'll think for proper naming. Also, feel free to suggest yours, if you want.

**Comment by nrydanov** [comment]
Sorry, my English isn't perfect :)

Fixed)

P.S. Also allowed edits by maintainers

**Comment by laurmaedje** [comment]
I'll close this for now since it is blocked on hayagriva and the PR there also seems a little stalled. We can reopen this once it becomes relevant for Typst.

**Pull request closed without merging**
