### PR TITLE
Make `dot` be multiplication and add `dot.period` for periods

### PR DESCRIPTION
**Pull request by SUPERCILEX**
See https://en.wiktionary.org/wiki/%C2%B7

`dot` is the operator whereas `dot.c` is the middle dot. This PR moves the current `dot` to `dot.period` and moves `dot.op` to `dot`.

Fixes https://github.com/typst/typst/issues/724

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Ok, I think I've got things in a decent state. The idea is as follows: if a symbol can easily be typed with a normal character, then the default for the spelled out character should be the next most common use. So for example `dots` is currently the same as typing out `...` which is not super useful. Now `dots` will be `⋯` which I think is the next most common use.

I only did this for a limited set of symbols because I don't know what the "next most common" would be for each. We'd need to collect sample documents and compute stats.

**Comment by laurmaedje** [comment]
> if a symbol can easily be typed with a normal character, then the default for the spelled out character should be the next most common use

Not a bad idea, I could see this being a rule! We might need to concretize what "can easily be typed" means w.r.t. the multitude of keyboard layouts out there. We should also discuss options for the modifier name for the "easily typed" symbol is (which is "basic" right now).

**Comment by SUPERCILEX** [comment]
> which is "basic" right now

Yeah, this is a terrible name. I chose it because those characters were coming from the Basic Latin character set. I also considered "default", but the whole point is that they aren't the default. So maybe "simple"? Or we could repeat the name of the dictionary? So `dot.dot`. Thoughts on this last approach?

**Comment by laurmaedje** [comment]
Not a fan of "default" and also not of "dot.dot", I think the latter is confusing. But "basic" and "simple" both aren't that bad.

**Comment by SUPERCILEX** [comment]
Sounds good! So I'll leave this PR as is?

**Comment by SUPERCILEX** [comment]
🙌

**Pull request merged**
