### PR TITLE
Better asset handling

### PR DESCRIPTION
**Pull request by laurmaedje**
This implements the asset handling changes discussed in https://github.com/typst/typst/pull/3171.

Typst's CLI embeds fonts, which we (a)  don't want to keep in the repository as it gets bloated over time and (b) exceed the crates.io size limit. These assets are now instead loaded from https://gitblobs.typst.org at build time (via a proc macro). 

To this end, there are two new crates:
- `typst-assets` is responsible for providing any desired asset to a consumer. This can either be a bundled asset from `crates/typst-assets/files` or a blob that is fetched from the network.
- `typst-assets-macro` provides a convenient `include_asset!` macro that uses `typst-assets` behind the scenes. I made it a separate crate rather than adding it to `typst-macros` because not all consumers of `typst-macros` need the heavy dependencies on `ureq` and `native-tls`.

Blobs are downloaded from `TYPST_BLOB_URL/{hash}` into `TYPST_BLOB_DIR/{hash}`. The blob cache directory defaults to a directory within a Rust-provided `OUT_DIR`. However, the environment variable can also be set manually for more control. For offline building, you can run `cargo run -p typst-assets` to download all assets ahead of time. Then, the main build will not fetch anything.

New blobs can only be added by a maintainer (since it requires access to the file server). If the need for a new blob should arise in a PR, a maintainer should be asked/pinged to add it.

Currently, only `typst-cli` and the docs & test infrastructure use the on-demand fetching. The core compiler crates only depend on a few rather small data files (mostly Unicode data), which I've kept in the repository for now. This means that the compiler itself doesn't get a build-time dependency on `ureq` and `native-tls`. It also means that only the CLI crate on crates.io will fetch from the network and not the library crates.

The build process clearly indicates that it fetches things and from where as part of the build log, in style with other cargo output.

gitblobs

If anybody sees any flaws or potential improvements with this setup, please point them out!

cc: @alerque @mkroening @Enter-tainer @drupol (from the issue discussion)

### CODE REVIEW

**Comment by drupol** [comment]
Hello!

In Nix, builds are isolated from the network, so this is not going to work out of the box.
Nix forces us to "declare" all the build dependencies before building. That means that we shouls be able to download those assets individually by Nix and verify their checksums.

Therefore, my question is... Is there a way to download those assets individually and move them in a specific directory so it gets detected by Typst while building instead of being downloaded?

> Blobs are downloaded from TYPST_BLOB_URL/{hash} into TYPST_BLOB_DIR/{hash}.

I guess it's possible, right? Is `TYPST_BLOB_DIR` an arbitrary directory on the filesystem?

My next question would be to know what type of `{hash}` the file should be saved in (sha-256?, other custom hash?) and how to compute such a hash from an existing file (_a simple command line is enough_).

**Comment by Enter-tainer** [comment]
> Last question now, why did you create a specific domain name for that? Why not downloading those files directly from their source URLs ?

I think this is valid. Collecting font zip/tarball from different sites and extract them in scripts is pain.

**Comment by laurmaedje** [comment]
> In Nix, builds are isolated from the network, so this is not going to work out of the box.

How does crates.io work with Nix builds?

> Therefore, my question is... Is there a way to download those assets individually and move them in a specific directory so it gets detected by Typst while building instead of being downloaded?

Yes, you can set `TYPST_BLOB_DIR` and then run `cargo run -p typst-assets` and all the necessary blobs will be there. You can then build the CLI with the same `TYPST_BLOB_DIR` and it will load the blobs from there.

> My next question would be to know what type of {hash} the file should be saved in (sha-256?, other custom hash?) and how to compute such a hash from an existing file (a simple command line is enough).

It's SHA-256 => base64. This is the Rust code I use:
```rust

fn process(path: PathBuf) -> Result<ProcessedFile> {
    let file = File::open(&path).context("failed to open file")?;
    let mmap = unsafe { Mmap::map(&file)? };
    let size = mmap.len();
    let hash = {
        let mut hasher = Sha256::new();
        hasher.update(&mmap);
        Base64Url::encode_string(hasher.finalize().as_slice())
    };
    Ok(ProcessedFile { path, size, hash })
}
```

> Last question now, why did you create a specific domain name for that? Why not downloading those files directly from their source URLs ?

First and foremost for reproducibility. I don't want the build to randomly break because someone took down their URL. But also because not all of the assets have other source URLs. The `plugin-oob.wasm` blob, for example, isn't hosted anywhere else. It was created for Typst by a contributor.

**Comment by Myriad-Dreamin** [comment]
Should `typst-assets` verify the data integrity? The asset file may have a different content if:
+ someone interrupts the downloading process and restart it later.
+ the file on server changes for some reason.
In that cases, `typst-assets` must download the files again. If it doesn't verify files, one has to clean up the blob directory maunally to recover correct assets.

**Comment by laurmaedje** [comment]
Yeah, that sounds like a good idea. Since the filename is a SHA hash anyway, it's pretty easy to do.

**Comment by laurmaedje** [comment]
> I'm thinking typst-assets can just be the one source of truth that prevents itself as a unified frontend which abstracts away the difference between requesting local assets and requesting remote assets.

That's already the case.

> Is it possible to merge typst-assets and typst-assets-macro?

**Comment by Leedehai** [comment]
Thanks! A separate question: it seems not clear to me from the PR description that if the assets were already downloaded (either by a previous build, or because the developer pre-downloaded it with `cargo run -p typst-assets`) but are out of sync with the server, or there are files added/deleted on the server, how does the local machine know?

**Comment by laurmaedje** [comment]
Assets can't be out of sync with the server because all files on the server are immutable and served from a SHA256 hash and stored with this hash as the filename. Files will not be removed from the server. If files are added, the machinery will download those on-demand if it needs them. All known filenames + hashes are listed in the `blobs.rs` file in the source code and the compiler will only attempt to download well-known ones.

**Comment by alerque** [comment]
Per one of my [original comments](https://github.com/typst/typst/pull/3171#issuecomment-1888819421) it is important that `cargo fetch` works to do all the network operations and `cargo build` can subsequently be run with no network access. This does not appear to be the case yet. With this layout the build phase is doing the downloading.

**Comment by alerque** [comment]
Unfortunately using `cargo run -p typst-assets` requires a whole build of *builds* to run and a bunch more developer tooling than `cargo fetch` being able to take care of this as I originally suggested. At the time it was being suggested the assets just be in separate crates, not on a 3rd part site with a special crate that had to be compiled to download them. Also I don't see an easy way to programmatically even get a full list of asset files that could be used to generate a pre-fetcher (short of parsing the Rust source). This leaves some pretty rough edges out there as far as getting offline builds to actually work.

**Comment by laurmaedje** [comment]
@alerque I implemented it pretty closely to how it was discussed in the issue, but I agree that it's not ideal and I'm not super comfortable with how it works. I guess this was just a pretty big time sink ... After thinking it through again, I think I'll scrap this and instead just add a typst-cli-fonts crate with the fonts (possibly compressed to keep it <10MB and reduce  binary size) that will go on crates.io and a typst-test-assets crates that will just be a git dep and thus not limited to 10MB.

**Comment by laurmaedje** [comment]
Opened #3515 instead.

**Pull request closed without merging**
