### PR TITLE
Allow `elem` synthesized fields to take a default value

### LINKED ISSUE #2165: Empty figure.caption causes the compiler to panic
### Description

**Error:**
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/git/checkouts/typst-6808799b0d8fdaa9/360cc9b/crates/typst-library/src/meta/figure.rs:515:19
```

**Reproduction code:**
```typst
#figure.caption[]
```

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

### LINKED ISSUE #2530: Compiler panic when getting the caption of a figure
### Description

```typ
#figure(caption: [test])[].caption
```
causes the compiler to panic:
```
thread 'main' panicked at crates\typst-library\src\meta\figure.rs:548:19:
called `Option::unwrap()` on a `None` value
```

This did not produce a panic in 0.8.0. Instead, it returned the figure caption.

Note that 
```typ
#figure[].caption
```
produces the following error message:
```
error: content does not contain field "caption"
```

### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by Dherse**
Fixes #2530 and Fixes #2165.

### CODE REVIEW

**Comment by laurmaedje** [comment]
There's also https://github.com/typst/typst/issues/2328. Would you mind checking other subelements than caption as well for potential problems?

**Comment by Dherse** [comment]
Sure, I'll give it a look once I'm done with what I'm working on ;)

**Comment by Dherse** [comment]
@laurmaedje I added tests for all other subelements, I also made it such that you *cannot* construct a `footnote.entry` since I don't see a valid usecase for creating your own.

**Comment by Dherse** [comment]
After discussing on [Discord](https://discord.com/channels/1054443721975922748/1088371867913572452/1174373719267868752) with @PgBiel, we came to the conclusion that the old behaviour should still work but with an error being produced when providing it with an element whose location is missing. I also improved the error for `outline.entry` to reflect this as well, this improves error messages. (i.e an outline.entry will no longer give you the error `cannot outline heading` which was completely wrong, it will only give this error if the content being passed to it is not Outlinable and Locatable)

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
