### PR TITLE
Add `gcd` and `lcm` calculation methods

### PR DESCRIPTION
**Pull request by HarmoGlace**
This PR adds the `gcd` (Greatest Common Divisor) and `lcm` (Least Common Multiple) calculation methods, with tests.

### CODE REVIEW

**Comment by andreasKroepelin** [comment]
Is `lcm(a, b) = a * b / gcd(a, b)` really the best way to compute the lcm? Especially concerning overflow... For example, let `b = 2a`, then `lcm(a, b) = 2a = b` but we would have an intermediate result of `a * b = 2a^2` which might unnecessarily overflow.

**Comment by HarmoGlace** [comment]
Indeed, I used this algorithm "by default" because I did not find any better way to do it :/
If you have any better algorithm, you can suggest it

**Comment by andreasKroepelin** [comment]
Wikipedia says: https://en.m.wikipedia.org/wiki/Least_common_multiple#Calculation

Which is kinda obvious, thinking about it 😅 
So you would have `lcm(a, b) = (a / gcd(a, b)) * b`. The division always results in a integer per the definition of the gcd.

**Comment by HarmoGlace** [comment]
Indeed, thanks for the suggestion!

**Pull request merged**
