### PR TITLE
Handle references via a dedicated anchor node

### PR DESCRIPTION
**Pull request by gtsiam**
# Why

The idea is to remove the special-case handling for figures, equations what have you. My ideal end goal would be to be able to implement my own figure with my own layout and link targets (what I'm calling anchors)

# What

Add an anchor is an element that holds two fields:
- A `body`, which is displayed as-is in place of the anchor.
- A `ref-body` which is displayed as-is in references to the anchor.

When a label is applied to an element, A `MetaElem::active_label` style is applied to it. When a reference is created, it now looks for anchors that were created (synthesized) with a matching `active_label` style. This means that anchors can be nested inside the element that created them, or even appear in show rules. They will still work. Note that I haven't touched the way selectors work, only references.

Additionally, the pr adds an `error(msg)` function that creates an element which triggers a compile error when displayed (kinda like a lazy assert). Setting an anchor's `ref-body` to an error will cause it to be considered "invalid". When matching anchors to reference, the following checks are performed (in order):
- For a single valid anchor and zero or more invalid anchors causes the valid anchor is referenced.
- For Multiple valid anchors causes an error
- For Multiple invalid anchors causes an error

The last two cases are currently identical as far as the user is concerned, but the intent is to not show duplicate label errors when multiple valid and invalid anchors exist matching a label.

# Summary of the changes

- Added some quality-of-life code for source handling:
  -  Custom debug implementations for source & span
  - When emitting errors with detached sources, I got an error about vec out of bounds, so I added an explicit panic
- Made some of the code more readable (well; to me at least). Gotta scratch that formatting/refactoring itch.
- Implemented the anchor element & new reference handling
- Added an error element that, when it appears in the document, causes a compilation error.
- Added Greek translations

### CODE REVIEW

**Comment by laurmaedje** [comment]
I like what this is trying to achieve, but I'm not so sure about the concrete details. With the way labels work in Typst, adding a label to something does not affect its semantic structure. You can query for something with a label and still get the heading/figure whatever and not some label element. 

The anchor mechanism proposed here is different. A figure needs to actually be a / show as an anchor to be referenceable and what you reference isn't really the figure, but the synthetic anchor element. This also has consequences for e.g. HTML export. There, some show rules that are only active for the layout would be disabled, so that e.g. a figure directly becomes an HTML `<figure>` element. Having to show it to an anchor for it to be referenceable would be problematic or at least lead to duplication between layouted and HTML output. Also, if you queried for figures, you couldn't find out their supplements/ref-bodies because the show rule would not be expanded yet. 

I think the way @7sDream used the compiler's capability mechanism to implement supplements would be more in line with the semantic idea. However, this would of course restrict it to built-in elements, at least for the moment. I definitely want to add custom user-defined elements in the future though and maybe it would even make sense to expose the concept of a capability.

**Comment by gtsiam** [comment]
> You can query for something with a label and still get the heading/figure whatever and not some label element.

That is still, intentionally, the case. The anchor only appears when the element is realized, and label selectors work just as before. This only affects reference elements, not queries.

The reason I put everything in the anchor concrete type was to move the figure impl closer to what a user could write. Maybe it's worth instead exploring a type & capability system to make everything available to the user later.

For now it should be reasonably easy to port everything to a `ShowRef` trait (my initial impl used that approach, so it's mostly rewriting that code). I'll get to it once I'm home.

**Comment by laurmaedje** [comment]
I'm snot completely sure what your proposed design with `ShowRef` is and what consequences it would have for `AnchorElem`, also in comparison to 7sDream's PR. Could you explain it more before porting?

**Comment by gtsiam** [comment]
Add a ShowRef capability implemented on figure, equation, heading and anchor. It would define a single show_ref method identical to show which would create the equivelant of the ref-body element on anchor.

From what I can see of 7sDream's pr, it's a slimmer version of the ReferenceInfo info trait.

**Comment by laurmaedje** [comment]
What I'm wondering is whether it makes sense at all to have an anchor element or whether, in reality, you always want to reference a semantic element.

**Comment by teenjuna** [comment]
@laurmaedje, since the work on both this PR and #283 is now kind of on halt, can you tell which PR should proceed?

**Comment by laurmaedje** [comment]
I'm gonna close this as #491 has been merged. Figures with custom show rules could now also be used to implement arbitrary referenceable things. Long-term we'll probably want to expose the underlying capability system more so that things could be even more straight-forward.

**Pull request closed without merging**
