### PR TITLE
embed New Computer Modern into binary

### PR DESCRIPTION
**Pull request by cmoog**
This is the font which most closely resembles the default LaTeX font and thus will be the go-to for many users switching to typst. It should be embedded and supported as first-class.

Especially considering that the font is supported by default on the Web app, it is a strange experience to compile a document locally only to find that the font is different without warning...

### CODE REVIEW

**Comment by Enivex** [comment]
> the default LaTeX font 

The default for both Lualatex and Xelatex is Latin Modern.

**Comment by cmoog** [comment]
@drupol The additional `Italic` and `BoldItalic` variants were downloaded from: https://ctan.org/pkg/newcomputermodern?lang=en

**Comment by drupol** [comment]
Ok thanks.

Preparing a PR to include that font in Nix in the meantime, I'll update this comment when it's done.

**Comment by laurmaedje** [comment]
Hmm, the binary is already half fonts, half code in size. Maybe we can find another way to distribute often-used fonts, because otherwise it will just keep growing as people request other fonts.

**Comment by Enivex** [comment]
Is there a good reason to include more than one sane default set of fonts in the binary?

**Comment by cmoog** [comment]
> Hmm, the binary is already half fonts @laurmaedje 

This is a good point. From some quick testing, `zstd` was able to compress the font files down by about 50%. Then we could embed the compressed files and decompress at runtime.

> otherwise it will just keep growing as people request other fonts

The same compelling interesting that exists for this font, as the singular default LaTeX font, will not exist for future requests. I ran into this issue this while migrating my first document to Typst from a very simple LaTeX file. I think it makes sense to optimize for these kinds of migrations if Typst is to successfully gain adoption by converting LaTeX users.

> Is there a good reason to include more than one sane default set of fonts in the binary? @Enivex 

Yes. If Typst intends to convert LaTeX users, it has a strong interest in offering comparable capabilities out of the box. This includes the *one* default LaTeX text/math font.

As a separate note: I was surprised to find no compiler warning or error when the target font was missing.

**Comment by cmoog** [comment]
> Maybe we can find another way to distribute often-used fonts

I think the platform specific package managers make the most sense here– although it's worth noting that I was unable to find New Computer Modern on homebrew for macOS. The unfortunate side effect of course, is that system fonts become an implicit dependency of a project. Maybe it would make sense to have a system package à la `brew install typst-fonts` that just redistributes a large list of popular fonts, similar to mactex?

**Comment by laurmaedje** [comment]
Alright.

**Pull request merged**
