### PR TITLE
Support ..expr in math (fixes #938)

### LINKED ISSUE #938: Argument spreading should work in math function calls
```
$mat(range(2).map(_ => range(2)))$
```
This just reprs the list which is expected, though a little confusing.

```
$mat(..#range(2).map(_ => range(2)))$
```
This does the same thing, but puts `..` in the matrix.

```
$mat(#..range(2).map(_ => range(2)))$
```

**This doesn't compile, but should IMO.**

```
$mat(#(..range(2).map(_ => range(2))))$
```

**This compiles, but doesn't work even though it should.**

---

```
$#math.mat(..range(2).map(_ => range(2)))$ \
$mat(#(..range(2).map(_ => range(2))))$ \
$mat(..#range(2).map(_ => range(2)))$
```

image

### PR DESCRIPTION
**Pull request by SUPERCILEX**

### CODE REVIEW

**Comment by laurmaedje** [comment]
The idea wasn't that `..#` is an operator, but more that `..` followed by an expression works. Other valid expressions include plain variables (e.g. `pi`) and strings (although these would naturally result in an error when spreading, but not at the parser stage). You can observe how variables work in `#let var = "lim"; $op(var)$`. Similarly `#let array = ((1, 2), (3, 4)); $mat(..array)$` should work without a hashtag.

**Comment by laurmaedje** [comment]
I'm not entirely sure how to best implement this myself, but `..` shouldn't be parsed as a spread in any math_expr, only in argument lists. Similar to named arguments.

**Comment by SUPERCILEX** [comment]
Shucks. Would it make sense to still lex it as `..`, but then convert it to a text node in the parsing stage if we find that token outside of function args? Not sure how easy that'd be but it's my current thought.

**Comment by laurmaedje** [comment]
> Shucks. Would it make sense to still lex it as .., but then convert it to a text node in the parsing stage if we find that token outside of function args?

Possibly. But it should probably result in two text nodes, one for each symbol. Alternatively, the parser needs to be smarter about this instead of the lexer. In any case, it's gonna be hacky (which is the reason I didn't wanna do it in the first place).

**Pull request closed without merging**
