### PR TITLE
Comprehensive brackets

### LINKED ISSUE #240: Braket notation, set notation, and middle delimeters
There's no way to make a bar inside of brackets resize to the content, which is needed for braket and set notation. In Latex, `\middle|` is builtin, and the [braket package](https://www.ctan.org/pkg/braket) provides for braket and set notation as shown in [its documentation](http://mirrors.ctan.org/macros/latex/contrib/braket/braket.pdf), essentially:
- `\bra{x}` $\Bra x$
- `\ket{x}` $\Ket x$
- `\braket{x | y}` $\Braket{x | y}$
- `\braket{x | c | y}` $\Braket{x | c | y}$
- `\set{x | x < 3}` $\Set{x | x < 3}$ (github doesn't support this </3 )

[MathJax also provides](https://docs.mathjax.org/en/latest/input/tex/extensions/braket.html) `\ketbra`, but the Latex package maintainer prefers `\ket{x}\bra{x}`. I don't think it's necessary.
- `\ketbra{x}{y}` $\Ketbra{x}{y}$

I propose that:
- `middle` should make its content resize with the closest `lr` (or implied `lr`).
- `braket` should behave as an `lr(angle.l <content> angle.r)` which also resizes the first and last `|` directly contained. To specify an absolute value in the bra or ket, `abs` must be used, or it should be contained like `braket((|a|x) | c | y)` to render as $\Braket{(\lvert a \rvert x) | c | y}$, which should be done anyway as $\Braket{\lvert a \rvert x | c | y}$ is confusing.
- `set` does the same, but with `{}`, and resizes the first `|` encountered.
- `bra(x) = $lr(angle.l x |)$` and `ket(x) = $lr(| x angle.r)$`.

In terms of implementing, it seems like just copying the code for `LrElem` and adding the additional bits [here](https://github.com/typst/typst/blob/4428646c9997171e3aea25ad2f0c151755f072da/library/src/math/delimited.rs#L67).

Implementing `middle` would require adding the same logic as braket and set to `LrElem` in order to scan for it, I think. As well as changing whatever logic matches brackets in general, not sure where that is.

(If you play with this, note that `angle.l` and `angle.r` don't resize properly at the moment, fixed by #237)

### PR DESCRIPTION
**Pull request by samlich**
Draft fixes #240

So far, this makes the scaling done by an `LrElem` more configurable. Each gets a list of fences to scale with its opening and closing brackets. The fences may be a simple match, a preceding character (e.g. `{ ^| }` -> `{ | }`), or a replacement (e.g. `|x><y|` -> `|x⟩⟨y|`).

Commands similar to `abs` are added: `set`, `bra`, `ket`, `braket`, and `ketbra`. They provide opening and closing delimiters, and the proper settings for fences.

`lr` will choose its fence setting based on the first and last fragment contained. Or, it can be set by e.g. `lr(scale: "delim", x)`.

The parser still needs changes, without which parts of this are broken:
- `lr(scale: "delim", \{ x \})` must be used instead of `lr(scale: "delim", { x })`, as the brackets wrap automatically.
- `lr(<x | c | y>)` makes an absolute value `|c|` in the middle.

So, the parser needs awareness of the "bracket context," which is something like the `ScalingRules` enum.

Additionally, it would be cool if '|' could be matched to '⟩' and '⟨'. That will get messy, as '|' can be either an opening bracket, closing bracket, or fence.

There's some random garbage in the test.typ -> test.pdf file. It should be organized to figure out all the desired functionality.

### CODE REVIEW

**Comment by Leedehai** [comment]
Thanks for working on this! One reservation, though, is that the new rules proposed in the description sound sort of complex. In fact, I was not able to grasp it at the first glance (and I guess users may not either). Especially,
* how to write a set `{ |x| | x in X }` without resorting to `abs`?
* how to write a set `{ f|_(i=0) | f in F }` to denote a set consisting of the series of functions' values at 0?
* how to write a parallelism symbol (or any other random symbol a user want to scale up)? e.g. `{ a ∥ b }` (or, is it supported?)
* how to write an expression where I'd like to scale up multiple kinds of symbols? e.g. in `{ < x | y > }` I'd like to scale up `<`,`|`,`>` along with the open and closing braces.
* how to write `{ a < 1 | a > 2 | a in RR }` to denote a set made of a < 1, a > 2?

Alternatively, how do you think of the idea of using a special mark (a `^`, a backtick, or whatever you see fit) to denote symbols that need to be scaled up? Like
* `{ |x| ^| x in X}`
* `{ f|_(i=0) ^| f in F }`
* `{ a ^∥ b }`
* `{ ^< x ^| y ^> }`
* `{ a < 1 | a > 2 ^| a in RR }`
* Use `\` to escape the special mark if needed, like [commas and semicolons in certain contexts](https://typst.app/docs/reference/math/#:~:text=To%20write%20a%20verbatim%20comma%20or%20semicolon%20in%20a%20math%20call%2C%20escape%20it%20with%20a%20backslash)

With this alternative approach, it appears there's no need to modify the parser significantly and the most changes are in file implementing `LrElem`. Also, it's very user-friendly.

Thx again!

**Comment by laurmaedje** [comment]
I commented here: https://github.com/typst/typst/pull/641#issuecomment-1500093595

**Comment by samlich** [comment]
I've revised it to support `mid`, though its very hacky and adds temporary private unicode characters temporarily to mark the region to scale. Is there a better way to do this?

I made it so that it scales up the first `|`. Setting `scale_from_start: 0` and `scale_from_end: 1` would change it to choose the last one, as you wrote in your comment (I'm more familiar with the variable being declared from the left).

With brakets, `scale_from_start: 1`, `scale_from_end: 1`, so that it scales the first and last `|`.

Using `$lr(|x⟩⟨x|)$` gives a compile error, due to the angle brackets being treated as brackets.
 
Updated [pdf](https://github.com/samlich/typst/blob/6eb57653d306507df0726a7557999dafef32c0dd/test.pdf) from [test.typ](https://github.com/samlich/typst/blob/6eb57653d306507df0726a7557999dafef32c0dd/test.typ).

**Comment by laurmaedje** [comment]
Some good points were raised in #641, but the ideal solution isn't clear yet. That said, I agree with @Leedehai that this approach is a bit too complicated, so I am going to close this. Still, thanks for working on this!

**Pull request closed without merging**
