### PR TITLE
Allow `calc.atan2` to take lengths

### PR DESCRIPTION
**Pull request by Jollywatt**
It’s mathematically sound to allow `x` and `y` to be lengths in `calc.atan2(x, y)`, so long as they are of “compatible” units (in the sense that `y/x` is well-defined). This PR ensures that both `calc.atan(5pt/3pt)` and `calc.atan2(3pt, 5pt)` just work.
Exactly the same check as `Length::try_div` is performed before computing `atan2` on the raw lengths.

I’m not sure what the performance impact is from turning`atan2` from `(Num, Num) -> Angle` into `(Span, Num|Length, Num|Length) -> SourceResult<Angle>`.

### CODE REVIEW

**Comment by Leedehai** [comment]
What about `Rel<Length>`?

In general, I wish the `calc` module's functions are purely numeric, i.e. quantities with units shouldn't get mixed in.

**Comment by Jollywatt** [comment]
Yeah, it’s fair to say `calc` should be kept purely numerical. I’ve only bothered to do this because `atan2` comes up a lot in drawing (to find the bearing of a 2D vector).

**Comment by Enivex** [comment]
> Yeah, it’s fair to say `calc` should be kept purely numerical. I’ve only bothered to do this because `atan2` comes up a lot in drawing (to find the bearing of a 2D vector).

In drawing you would mostly use numerical coordinates and then set a length scale after no?

**Comment by Jollywatt** [comment]
> In drawing you would mostly use numerical coordinates

Sure, but tot necessarily. All drawing functions (`line`, `polygon`, `path`, plus most `cetz.draw` functions) accept points as a pair of relative lengths.

In practice, I've implemented the following:
```typ
#let vector-unitless(v) = v.map(x => if type(x) == length { x.pt() } else { x })
```
but have come to realise the only place this is actually ever used (in the `fletcher` code base) is to compute the vector angle:
```typ
#let vector-angle(v) = calc.atan2(..vector-unitless(v))
```
and hence this PR. (Which makes sense: the only time you might need to discard units is if you're doing something scale-invariant.)

Of course, this is a tiny point, but if it's a zero-cost abstraction then it seems like a win-win.

The important point is, though: does this slow down `calc.atan2`?

**Comment by laurmaedje** [comment]
We want to migrate away from calc in favor of methods on individual types (which can also be called in fully qualified form, e.g. `float.sqrt(4)`). So, in this design, the question is more whether length also will have an atan2 method.

**Comment by laurmaedje** [comment]
@Jollywatt from your reaction to my last message, it seems like you are not in favor of this change to methods. is there anything in particular that you don't like about it?

**Comment by Jollywatt** [comment]
> is there anything in particular that you don't like about it?

Nothing in particular, just a feeling 😅 I find my proposal less appealing aesthetically if it’s exposed as `length.atan2`, with all the other trig-related functions exposed elsewhere under `float`.

No concrete objections though. Maybe my Julia background (no methods, multiple dispatch) makes me like the idea of generic `calc` functions which work on different combinations of input types.

Either way, it’s probably best to hold off on this until the `calc` api settles?

**Pull request closed without merging**
