### PR TITLE
Implement scale-up marker for LrElem

### PR DESCRIPTION
**Pull request by Leedehai**
Draft fixes https://github.com/typst/typst/issues/240

This is my proposal to add the ability to scale up [MathClass::Opening|MathClass::Closing|MathClass:Fence](https://github.com/typst/unicode-math-class/blob/main/src/classes.rs) glyphs in the middle of an `LrElem`. Specifically, use a backtick to denote such a glyph.

There is no new argument introduced to the `lr()` function.

The test delimited.typ is also updated.

Demo:
```
$ { integral |x| dif x`|x|a, x in X } $  // set builder notation, where x|a means divisibility
$ { limits(A)_n`|limits(B)_n },
  lr(angle.l limits(A)_n`|limits(B)_n angle.r),
  | limits(A)_n `angle.r`angle.l limits(B)_n | $
$ { a < limits(A)_n \|\| a > limits(B)_n `| a in RR } $
$ { limits(A)_n `\u{2016} limits(B)_n "backtick:" `` `bracket.r.double } $  // verbatim backtick
```
Screenshot 2023-04-06 at 19 14 49

### CODE REVIEW

**Comment by PgBiel** [comment]
Hey, thanks for the PR! Just wanted to share some thoughts: could it perhaps be better or clearer to use a function named something like `mid` (similar to LaTeX) for this, instead of introducing this syntax?

**Comment by laurmaedje** [comment]
I would also prefer a `mid` function.

**Comment by laurmaedje** [comment]
What I would consider ideal, is that unmatched middle delimiters like `|` scale by default within `lr`, can be escaped with backslash to disable scaling or wrapped in `mid()` to force scaling. Note that `{ |x| + a/2 | a in NN }` would continue to work correctly because the first two `|` are matched. `{ a/2 | |a|^2 < 10 }` would not work correctly by default, it would need an explicit mid around the first fence or usage of abs around the, or a bit of escaping. but this case seems reasonably rare.

**Comment by Leedehai** [comment]
Thanks for the response! @PgBiel @laurmaedje in this [original proposal](https://github.com/typst/typst/issues/240#issuecomment-1496884156) I laid out some reasons why I prefer a special mark over a `mid()`.

Does that make sense? I'm not totally against `mid()`, though.

**Comment by Leedehai** [comment]
I agree, that sounds better!

**Comment by astrale-sharp** [comment]
What does mid stands for?

**Comment by peng1999** [comment]
> `{ a/2 | |a|^2 < 10 }` would not work correctly by default, it would need an explicit mid around the first fence or usage of abs around the, or a bit of escaping. but this case seems reasonably rare.

I do not think that is a rare case. The current pipe matching rule do not work on simple cases like `|| x + 1 | - 3|` and has already caused [confusion](https://github.com/typst/typst/issues/802), and the matching rule makes the result hard to predict from source.

I suggest to apply following rule:

- `|` operators always do not match and always auto scale in  `lr()` unless explicitly escaped.
- `abs()` is recommended to always used for matched `|` operators.
- Add `bra` and `ket` function, as it seems to be a common usage of  `|` operator and will likely cause matching problem.

**Comment by laurmaedje** [comment]
It's not yet clear what the best solution is here (@peng1999 makes some good points), but I think we are in agreement that we do not want the backtick syntax, so I'm going to close this. Thanks for your work!

**Pull request closed without merging**
