### PR TITLE
Add support for more characters in links

### PR DESCRIPTION
**Pull request by frozolotl**
This PR allows additional characters to be part of a link.

It excludes support for both `)` and `]` out of concern that parenthesized URLs would fail to parse.
In that case, users are recommended to make use of the `link` function.

### CODE REVIEW

**Comment by frozolotl** [comment]
Correct URL parsing is notoriously complex, which is why I only added some remaining characters found in URLs.

However, here you go: https://url.spec.whatwg.org/#infrastructure

**Comment by reknih** [comment]
This will also allow direct links to IPs, etc. We generally aim to keep automatic link recognition narrow to avoid false positives. You can always use the link function explicitly! Do you think it's worth it to keep all of these extra characters in here or should this PR be narrowed down in that respect?

**Comment by frozolotl** [comment]
Good points! I think I will tweak the behaviour to be in line with your suggestion if the "heuristic" approach isn't chosen. Regarding that, what's your opinion on it?

**Comment by Julian-Wollersberger** [comment]
The heuristic should probably be fine? 

Theory states that lexers should use regular grammars, which is good for simple regex-based syntax highlighters. Though `block_comment()` already supports nested comments, so typst's lexing is context-free instead of regular anyway.

I quickly checked, and the VS code terminal recognizes closing parens in links if there was at least one open paren, but doesn't check for proper nesting. gnome-terminal checks for proper nesting. MS Word tries to be smart with editing, and ends up being confusing, so no idea what its precise rules are.

**Comment by laurmaedje** [comment]
Checking paren nesting seems sensible to me.

**Comment by frozolotl** [comment]
I have now implemented bracket-nesting respecting behavior.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
