### PR TITLE
Remove special handling of Noto fonts

### PR DESCRIPTION
**Pull request by peng1999**
Currently Typst has special handling for Noto fonts only because version 2.007 of Noto Sans Display (The only Display family in Noto fonts) have some incorrect metadata. I think that can be changed since we can correct the metadata in exception list now.

I found Noto Sans Display version 2.007 from [GitHub](https://github.com/notofonts/noto-fonts/blob/main/unhinted/otf/NotoSerifDisplay/) and use the following command to detect if contains `Display` in FAMILY_NAME.

```sh
otfinfo --info unhinted/otf/NotoSerifDisplay/* | rg 'Family' | rg -v '\bDisplay\b'
```

And it shows:
```
NotoSerifDisplay-CondensedBold.otf:Family:              Noto Serif Condensed
NotoSerifDisplay-ExtraCondensedBold.otf:Family:              Noto Serif ExtraCondensed
NotoSerifDisplay-SemiCondensedBold.otf:Family:              Noto Serif SemiCondensed
```

So only the three fonts need to be found.

---

This PR also includes fix for two semibold noto fonts, which is detected incorrectly by Typst.

The changed output of `typst fonts --variants` when Noto fonts v2.009 installed on system:

```diff
@@ -486,9 +486,9 @@
 Noto Naskh Arabic UI
 - Style: Normal, Weight: 700, Stretch: FontStretch(1000)
 - Style: Normal, Weight: 500, Stretch: FontStretch(1000)
 - Style: Normal, Weight: 400, Stretch: FontStretch(1000)
-- Style: Normal, Weight: 700, Stretch: FontStretch(1000)
+- Style: Normal, Weight: 600, Stretch: FontStretch(1000)
 Noto Nastaliq Urdu
 - Style: Normal, Weight: 700, Stretch: FontStretch(1000)
 - Style: Normal, Weight: 400, Stretch: FontStretch(1000)
 Noto Rashi Hebrew
@@ -1709,9 +1709,9 @@
 Noto Sans Sora Sompeng
 - Style: Normal, Weight: 700, Stretch: FontStretch(1000)
 - Style: Normal, Weight: 400, Stretch: FontStretch(1000)
 - Style: Normal, Weight: 500, Stretch: FontStretch(1000)
-- Style: Normal, Weight: 700, Stretch: FontStretch(1000)
+- Style: Normal, Weight: 600, Stretch: FontStretch(1000)
 Noto Sans Soyombo
 - Style: Normal, Weight: 400, Stretch: FontStretch(1000)
 Noto Sans Sundanese
 - Style: Normal, Weight: 500, Stretch: FontStretch(1000)
```

Related discussion can be found on [discord](https://discord.com/channels/1054443721975922748/1184433451554840636/1204412060096790538).

### CODE REVIEW

**Comment by laurmaedje** [comment]
There is also Noto Sans Display, which yields this output with your command:
```
NotoSansDisplay-BlackItalic.ttf:Family:              Noto Sans Black
NotoSansDisplay-CondensedBlackItalic.ttf:Family:              Noto Sans Condensed Black
NotoSansDisplay-CondensedBold.ttf:Family:              Noto Sans Condensed
NotoSansDisplay-CondensedBoldItalic.ttf:Family:              Noto Sans Condensed
NotoSansDisplay-CondensedExtraBoldItalic.ttf:Family:              Noto Sans Condensed ExtraBold
NotoSansDisplay-CondensedExtraLightItalic.ttf:Family:              Noto Sans Condensed ExtraLight
NotoSansDisplay-CondensedItalic.ttf:Family:              Noto Sans Condensed
NotoSansDisplay-CondensedLightItalic.ttf:Family:              Noto Sans Condensed Light
NotoSansDisplay-CondensedMediumItalic.ttf:Family:              Noto Sans Condensed Medium
NotoSansDisplay-CondensedSemiBoldItalic.ttf:Family:              Noto Sans Condensed SemiBold
NotoSansDisplay-CondensedThinItalic.ttf:Family:              Noto Sans Condensed Thin
NotoSansDisplay-ExtraBoldItalic.ttf:Family:              Noto Sans ExtraBold
NotoSansDisplay-ExtraCondensedBlackItalic.ttf:Family:              Noto Sans ExtraCondensed Black
NotoSansDisplay-ExtraCondensedBold.ttf:Family:              Noto Sans ExtraCondensed
NotoSansDisplay-ExtraCondensedBoldItalic.ttf:Family:              Noto Sans ExtraCondensed
NotoSansDisplay-ExtraCondensedExtraBoldItalic.ttf:Family:              Noto Sans ExtraCondensed ExtraBold
NotoSansDisplay-ExtraCondensedExtraLightItalic.ttf:Family:              Noto Sans ExtraCondensed ExtraLight
NotoSansDisplay-ExtraCondensedItalic.ttf:Family:              Noto Sans ExtraCondensed
NotoSansDisplay-ExtraCondensedLightItalic.ttf:Family:              Noto Sans ExtraCondensed Light
NotoSansDisplay-ExtraCondensedMediumItalic.ttf:Family:              Noto Sans ExtraCondensed Medium
NotoSansDisplay-ExtraCondensedSemiBoldItalic.ttf:Family:              Noto Sans ExtraCondensed SemiBold
NotoSansDisplay-ExtraCondensedThinItalic.ttf:Family:              Noto Sans ExtraCondensed Thin
NotoSansDisplay-ExtraLightItalic.ttf:Family:              Noto Sans ExtraLight
NotoSansDisplay-LightItalic.ttf:Family:              Noto Sans Light
NotoSansDisplay-MediumItalic.ttf:Family:              Noto Sans Medium
NotoSansDisplay-SemiBoldItalic.ttf:Family:              Noto Sans SemiBold
NotoSansDisplay-SemiCondensedBlackItalic.ttf:Family:              Noto Sans SemiCondensed Black
NotoSansDisplay-SemiCondensedBold.ttf:Family:              Noto Sans SemiCondensed
NotoSansDisplay-SemiCondensedBoldItalic.ttf:Family:              Noto Sans SemiCondensed
NotoSansDisplay-SemiCondensedExtraBoldItalic.ttf:Family:              Noto Sans SemiCondensed ExtraBold
NotoSansDisplay-SemiCondensedExtraLightItalic.ttf:Family:              Noto Sans SemiCondensed ExtraLight
NotoSansDisplay-SemiCondensedItalic.ttf:Family:              Noto Sans SemiCondensed
NotoSansDisplay-SemiCondensedLightItalic.ttf:Family:              Noto Sans SemiCondensed Light
NotoSansDisplay-SemiCondensedMediumItalic.ttf:Family:              Noto Sans SemiCondensed Medium
NotoSansDisplay-SemiCondensedSemiBoldItalic.ttf:Family:              Noto Sans SemiCondensed SemiBold
NotoSansDisplay-SemiCondensedThinItalic.ttf:Family:              Noto Sans SemiCondensed Thin
NotoSansDisplay-ThinItalic.ttf:Family:              Noto Sans Thin
```

**Comment by peng1999** [comment]
I downloaded Noto Sans Display version 2.003 from Google Fonts, and it gives correct metadata.

Since the font is not pre-installed by [Windows](https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list) and [MacOS](https://support.apple.com/en-us/108939), It must be installed by user manually. Maybe we can assume that users can easily fix the issue by upgrade their local font to latest version, and do not add a exception only for legacy versions.

**Comment by laurmaedje** [comment]
To summarize:
- Noto Sans 2.003 is ok
- Noto Serif 2.003 is ok
- Noto Sans 2.007 has 37 broken variants (I don't know where to find it now, but I have it and it's in the web app.)
- Noto Serif 2.007 has 3 broken variants (same as above)
- Noto Serif 2.009 is ok
- I wasn't able to find Noto Sans 2.009 if it exists

What I still wonder is why we're adding patches for the three broken variants of Noto Serif here, but not for Noto Sans. Either both or neither. In particular, Noto Sans is "worse" if there is indeed no 2.009 since then 2.007 is the latest version. 

We should do a big update-all-the-fonts for the web app soon. But even then, I don't know where to find the most up-to-date Noto Sans Display.

**Comment by peng1999** [comment]
Related issue: notofonts/notobuilder#17.

You can find Noto Sans Display v2.007 on the now abandoned repository [notofonts/noto-fonts](https://github.com/notofonts/noto-fonts).

Sans Display and Serif Display has been removed from noto sources 2 years ago, with no explanation. (https://github.com/notofonts/latin-greek-cyrillic/commit/974d00e8e80cdbc4a41704937a9bcfc7988b5945, https://github.com/notofonts/latin-greek-cyrillic/commit/220054617844e2271c1b1a44cd0a2f282400e3c0) It seems that the Display variants are abandoned and no new versions will be released anymore. Noto Serif Display v2.009 is still on the Noto Dashboard, while Noto Sans Display v2.007 isn't.

**Comment by laurmaedje** [comment]
Okay, then I'll update Noto Serif to 2.009 in the web app (once we do the big font update) and keep Noto Sans on 2.007. Thanks for the PR!

**Comment by laurmaedje** [comment]
Let's just keep the three exceptions for Noto Serif Display. They really don't hurt and we have Noto covered consistently then, regardless of the version. If it was properly maintained, I'd be totally with you on removing them, but it's not.

**Comment by laurmaedje** [comment]
Perfect, thanks for the quick change!

**Pull request merged**
