### PR TITLE
Let cancel() rotation angle be absolute

### PR DESCRIPTION
**Pull request by Leedehai**
Hi, I'd like to propose an enhancement to the useful `cancel()` function: the custom rotation angle is better to be an "absolute angle" (the pitch angle i.e. deviation from the horizontal X-axis) , instead of an relative angle with respect to the default angle of the cancel line.

When users want to set the line's angle with the `rotation` param, they usually have an absolute angle in mind (e.g. "I'd like to draw cancel lines all at 45 deg"), rather than an angle that is relative to each content box's specific default angle.

#By default, a line extends from its content box's bottom left to top right, an angle that depends on the content's box shape (not 45 degree for non-square content boxes, a quite common situation) e.g.`cancel(l), cancel(a)`, making it not easy to draw a horizontal, vertical, or 45deg cancel line by adjusting the `rotation` param: 
Screenshot 2023-05-20 at 12 32 20

@PgBiel the original author of the `cancel()` function. WDYT? :)

Fixing #1263 (in a way)

### CODE REVIEW

**Comment by PgBiel** [comment]
Hello! Well, this is actually what I thought about doing on my first iteration of the `cancel` implementation, but I found that it wasn't exactly what I thought it would be, mainly because I expected the `rotation` parameter to produce predictable behavior in several aspects:

1. It would be nice to have some angle correspondence between e.g. 45 degrees = default cancel, 135 degrees = inverted cancel, but that's not possible, as going from bottom left to top right of the boundaries only produces an angle of 45 degrees if the bounding box is a square. This isn't exactly that much of an issue though, as the `inverted` parameter exists and could be enough, but what this means is that `rotation` could be a bit inconsistent with bounding boxes of different sizes.

We could, of course, solve this somewhat by applying some sort of transformation on the angle itself (e.g. multiply by real angle divided by 45 degrees), but this still feels like it would only look properly with the default cancel line, not with the inverted one.

2. We have to account for the `inverted` parameter, as it seems that specifying `rotation` here would simply override it, while I wished for them to be a complement to each other. That is, that specifying `inverted` would, for example, add 90 degrees to your angle. But this ends up with the same problem as above - inverting the cancel line doesn't necessarily mean adding 90 degrees, but just flipping the line in relation to the Y-axis. 

With all things considered, I settled on applying a rotation relative to what the line's current rotation is, so that it'd work nicely with the `inverted` parameter for example.

But I recognize that this isn't so simple, and that one might want to simply override the angle completely, as you mention in your use-case (of having consistently horizontal or vertical cancel lines). And, indeed, your implementation might make sense for more use-cases, though we might have to forfeit angle correspondence with `inverted` (and just flip in relation to the Y axis _after_ the rotation).

I was thinking, though, that maybe we could have kind of "both" - maybe one relative rotation parameter (in relation to the end result), and one absolute rotation parameter (in relation to the X-axis). Not sure how viable / possibly confusing this could be though. I'm open for further discussion about the best design here.

**Comment by Leedehai** [comment]
Hi thanks for your inputs! You are right that the current patch didn't consider the `inverted` param, and that setting `rotation` would simply override `inverted`. I agree it's better to let both params should complement to each other.

Yet, I'm not sure I clearly understand point 2:
> I wished for them to be a complement to each other. That is, that specifying inverted would, for example, add 90 degrees to your angle. But this ends up with the same problem as above - inverting the cancel line doesn't necessarily mean adding 90 degrees, but just flipping the line in relation to the Y-axis.

It appears to make more sense to me if `inverted` means flipping the line w.r.t. the Y-axis. I think the behavior of "adding 90 degrees" seems a bit surprising to users.

Also, wondering if you could shed more light on point 1? I feel a bit confused here given that the current patch indeed does not change the default angle (i.e. it still goes from bottom left to top right, meaning it is not 45 degree for non-square content boxes, just like the status quo), and that the current patch sets the `rotation` angle w.r.t. the X-axis, precisely to address the difficulty of producing inconsistent angles.

Thank you!

**Comment by Enivex** [comment]
I don't know how viable this is, but would it be possible to have something like
`rotation: auto` (default) 
`rotation: 30deg` (for absolute angle)
`rotation: auto + 30deg` (for angle relative to the automatic angle)
?

**Comment by Leedehai** [comment]
Hi, `#auto + #30deg` results in an error: `expected angle or none, found content`. I'd like to understand the use case of `#auto + #30deg`, though: in what situation would a user want to rotate a line w.r.t to the default?

**Comment by Enivex** [comment]
> in what situation would a user want to rotate a line w.r.t to the default?

If you're not entirely happy with the automatic angle, and would like to nudge it slightly, without having to guess an absolute angle.

**Comment by Leedehai** [comment]
(following up the previous message) Hi, I just pushed a new commit to this patch - it handles `inverted` at the presence of `rotation`. Please let me know what you think :)

**Comment by Enivex** [comment]
(The reason why I suggested it is also that it would be the best of both worlds, since you could easily specify both relative and absolute angle)

**Comment by Leedehai** [comment]
I see, yeah I agree if it's more desirable to have the best of both worlds, it just seems difficult to design a sensible API to accommodate both [1] 🤔

[1] without modifying the parser to allow `#(auto + XXdeg)`: `cannot add auto and angle`

**Comment by PgBiel** [comment]
> Yet, I'm not sure I clearly understand point 2:
> --snip--
> It appears to make more sense to me if `inverted` means flipping the line w.r.t. the Y-axis (or X-axis? no strong opinion here). I think the behavior of "adding 90 degrees" seems a bit surprising to users.

Fair. We can pinpoint it to "flip w.r.t. Y-axis".

> Also, wondering if you could shed more light on point 1? I feel a bit confused given that
> 
>     * the current patch indeed does not change the default angle (i.e. it still goes from bottom left to top right, meaning it is not 45 degree for non-square content boxes, just like the status quo before this patch),

Of course. To be clear, I wished that one would still be able to consistently achieve the default `cancel` implementation with `rotation` - currently, you do that by setting the rotation to `0deg` (which does not rotate at all), but I wanted to have something more absolute (like you're thinking of) which would have `45deg` be the default cancel and `135deg` be the inverted one, which, of course, didn't work as not all bounding boxes are squares.

Overall, though, that was mostly a design thing I thought of, and we can probably disregard it now without worrying too much about it (if one wants the default `cancel` implementation, then I guess they can just not fiddle with `rotation` at all).

>     * the current patch sets the `rotation` angle w.r.t. the X-axis, precisely to address the difficulty of producing consistent angles -- that is, with this patch, setting `rotation: #30deg` will draw cancel lines of 30deg w.r.t. the X-axis regardless of the content box's shape.

Yes, of course. That's valid.

But, as other comments have mentioned, it might be desirable to have both relative and absolute angles (see my following comment).

**Comment by PgBiel** [comment]
Here are my ideas regarding possible syntax to keep both relative and absolute angles possible:

1. Add a separate option for absolute angles, such as `angle: 30deg` (which would work like this PR proposes). However, this might be a bit confusing for the user (to have both options, that is).
2. Allow `rotation` to take a function, possibly with the signature `angle => angle`, which takes the angle of the default cancel line (w.r.t. the X-axis) and returns a new angle, which can be relative to it or not (their choice). This could be better (and even provide more possibilities than just adding or subtracting angles), or at least less confusing.

**Comment by Leedehai** [comment]
> Allow rotation to take a function...
I think that's a good idea, and there are precedents in Typst so it's not an overly surprising design. I'll update the patch so that
* without `rotation`, the line takes the default angle, which goes along the diagonal of the content box just as the status quo.
* the `rotation` param can either be an angle w.r.t. the X-axis, or a function `angle => angle` so that users can, among other things, adjust based on the default angle.
* `invert` flips the line w.r.t. the Y-axis.

**Comment by laurmaedje** [comment]
@Leedehai What's the status of this?

**Comment by Leedehai** [comment]
Hi - I'm busy these days... and I'd like someone else (or you 🙂) to take over, or put it on the back burner.

**Comment by laurmaedje** [comment]
I'm in favor of allowing:

- `auto`: The current behaviour
- `angle: absolute angle
- function: (auto angle) => absolute angle

I would also rename it from `rotation` to `angle`. It's clearer, in particular, if it's absolute. If no one else wants to implement it at the moment, I would implement it myself.

**Comment by LuxxxLucy** [comment]
I am going to take this up and update soon. After reading the discussions, I am going to follow @laurmaedje 's three option for specifying (1. auto, 2. absolute angle and 3. a function)

**Comment by laurmaedje** [comment]
Closing in favor https://github.com/typst/typst/pull/2466

**Pull request closed without merging**
