### PR TITLE
refactor: Replace once_cell to std lib

### PR DESCRIPTION
**Pull request by howjmay**

### CODE REVIEW

**Comment by PgBiel** [comment]
Worth noting that this would raise the minimum Rust version to 1.70.0, and could have a bit of a cascading effect to projects depending on Typst. Not sure if this is a bad thing or not, but worth keeping it mind

**Comment by alerque** [comment]
At this point in Typst's lifecycle I don't think depending on the latest stable Rust release should be a problem at all.

Please do add the MSRV to this PR though. It should be set in the `Cargo.toml` file ([docs](https://rust-lang.github.io/rfcs/2495-min-rust-version.html)).

**Comment by laurmaedje** [comment]
The MSRV is also duplicated in the CI yaml file (that's why CI is failing). I haven't found a way to extract it from Cargo.toml there.

**Comment by howjmay** [comment]
Thanks!

**Pull request merged**
