### PR TITLE
Add `count` method for strings

### PR DESCRIPTION
**Pull request by sitandr**
I think it can be quite useful method. Currently the best way to achieve that is `str.matches(pattern)` which is good, but creates much unused data (and is hard to find for some foolish people like me).

I think that the purpose is quite clear, but my use-case is kind of funny, so I think I could share it. I have a large project (in webapp, with several other people) with lots of polylux presentations and other docs. To get an overview of our progress I have a Typst file with tables of "completeness". To mark presentation as done, I check if there are no `todo`-s left in source files and enough of `question`-s to auditory. To do that, I parse source code as text (using states and so on will make it too heavy, since presetations are numerous, large and complex).

I'm sure there will be more "proper" uses of that method. :)

### CODE REVIEW

**Comment by frozolotl** [comment]
I think `str.matches(pattern).len()` fits the purpose pretty well already. But I wouldn't be opposed to an extra `count` method either.

**Comment by sitandr** [comment]
Thanks, I was certainly blind when reading documentation. But yes, I still think it could be a good thing to have on its own.

**Comment by laurmaedje** [comment]
I think the `str.matches(..).len()` way is better to be honest. `count()` is not clear enough by itself. Just reading the PR title, I wondered what it would do. It could also be confused with `len()`.

**Comment by sitandr** [comment]
Okay, that's fine, I'll close it. Sorry for bothering.

**Comment by sitandr** [comment]
I feeled it as very intuitive thing from `python` I used frequently. I'm quite surprised discovering there is no such method in Rust, Java or JS. So I think it is okay to avoid adding it.

**Comment by laurmaedje** [comment]
Like @frozolotl said, don't be sorry! It's no bother at all, on the contrary, I'm happy about all contributions. I hope my response didn't come across as rude.

**Pull request closed without merging**
