### PR TITLE
Color fixes

### LINKED ISSUE #2259: Regression in `#show raw: set text()`
### Description

A show-set rule on `#raw` no longer respects text colours. I believe this to be a regression, this wasn't present a month ago and came up when I updated my compiler.

```
#show raw: set text(fill: white)
#raw("hello")
```

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by Dherse**
Follow up to #2171:
 - Fixes images not using ICC profiles when the ICC profile is not contained within the image
 - Small cleanup in `raw.rs`
 - ~~Added equality between luma and rgb colors: if an rgb color is just a luma color in disguise, it will compare them as if they were luma colors~~ Convert to syntect colors early avoiding color eq issues in syntect, fixes issue when comparing colors in the internals, it happened in `raw.rs`~~, it likely occurs in some other places~~. Happens to fix #2259
 - Removed `Alternate` color spaces of the ICC profiled colors, the default is `DeviceRGB` and `DeviceGray`, this fixes the #2257 and #1927. Note that for #2257 it does not fix issues with readers that have poor support for ICC profiles, that's on poppler for not falling back to an appropriate color space on its own 🤷‍♂️ Mind you, falling back to `DeviceRGB` does fix rendering in poppler, still they have a bug that needs fixing!
 - Added regression tests for the aforementioned bug

This small PR corrects some (albeit small) mistakes, which should fix color inaccuracies that could happen. Due to relying on `DeviceRGB` and `DeviceGray`, any further color inaccuracies are solely an issue with the reader as typst is following best practices and what other PDF writers produce. It also fixes a bug that cropped up due to "naive" color comparisons. ~~I decided to modify the `PartialEq` implementation instead of anything else for the sake of guaranteeing that no other bugs like this occur again.~~ Early conversion of colors in syntect colors for `raw`-related stuff fixes the issue, note that it might appear somewhere else in the code, but as of know, it seems correct everywhere else. Another fix would be to revert some of the presets (i.e `Color::BLACK` etc.) back to RGB colors, but this would come with a filesize cost and would actually not really resolve the issue.

### CODE REVIEW

**Comment by l1mey112** [comment]
Amazing!

**Comment by laurmaedje** [comment]
@Dherse I think arguable the bug is really in the raw code, not in the color code. There is no need for it to operate with Typst colors. It should just have `let foreground` as a `synt::Color`:

```rust
let foreground = theme.settings.foreground.unwrap_or(synt::Color::BLACK);
```

Then, `styled` can also take `foreground: synt::Color` and the comparison is just `style.foreground != foreground`. Only within the if, we need to convert to Typst colors to set the text fill.

We can decide independently of that whether luma and rgb should compare equivalently. I'm not sure about that.

**Comment by Dherse** [comment]
> We can decide independently of that whether luma and rgb should compare equivalently. I'm not sure about that.

I'll change it to that the, and disable the luma == rgb comp

**Comment by laurmaedje** [comment]
Thank you for the fixes!

**Comment by Dherse** [comment]
It has been confirmed on Discord that this has mostly fixed color inaccuracy issues.

**Pull request merged**
