### PR TITLE
Add support for converting text in SVGs to paths

### PR DESCRIPTION
**Pull request by LaurenzV**

### CODE REVIEW

**Comment by LaurenzV** [comment]
Note: In the future, we could consider instead making it a parameter on text so that you can do `#set text(outlined: true)`, and it will automatically apply to SVG figures too. Once we have that, we could deprecate this parameter. But since this probably won't be added in the near future, this is probably the best option for now.

**Comment by MDLC01** [comment]
I don't really like the name `outlined`. It looks like it has something to do with the `outline` element, and other `outlined` parameters such as on figures, images, etc..

**Comment by LaurenzV** [comment]
The only alternatives I can think of are `selectable` or `embed-text`.

**Comment by MDLC01** [comment]
I like `embed-text` better.

**Comment by laurmaedje** [comment]
Do we really want to expose this? I don't really see why people would want this _except_ for the use case of creating unselectable text in Typst generally, for which this is merely a bad workaround.

**Comment by LaurenzV** [comment]
I mean, five people upvoted the comment in #1239, so I guess there is some demand at least? But I'm fine with either.

**Comment by laurmaedje** [comment]
I wonder whether the use case in the upvoted comment could be solved in some way via PDF tagging. Maybe not.

**Comment by LaurenzV** [comment]
> I wonder whether the use case in the upvoted comment could be solved in some way via PDF tagging. Maybe not.

If it does, it probably would only work in Acrobat anyway. 😄

**Comment by laurmaedje** [comment]
I'm okay with this, but don't like the name `embed-text`. I think it's not fully clear what false vs true means with this name (embed could just as well mean to "embed" it as _real_ text). How about `flatten-text`?

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
