### PR TITLE
Make behavior of calculation functions consistent

### PR DESCRIPTION
**Pull request by HarmoGlace**
This PR makes consistent the behavior of calculation functions by returning an error if a value is mathematically undefined or if the return value is a non-real number

### CODE REVIEW

**Comment by laurmaedje** [comment]
Not sure about this one. In general, I think keeping `NaN` out of the calculations is nicer. For example `0/0` originally produced `NaN`, but after community input was changed to produce an error instead.

**Comment by HarmoGlace** [comment]
> Not sure about this one. In general, I think keeping `NaN` out of the calculations is nicer. For example `0/0` originally produced `NaN`, but after community input was changed to produce an error instead.

I don't understand your point. With this PR, `0/0` and `0^0` will still produce an error.

The issue is when computations produces non-real numbers, like with negative square root/logarithm, the behavior is not the same for both, althought both returns complex numbers. Both should have the same behavior : either return an error or just `NaN`. Maybe that you would prefer that both return an error?

**Comment by HarmoGlace** [comment]
This PR also fixes the following inconsistency : calling `math.sqrt(-1)` returns an error whereas `math.pow(-1, 0.5)` returns `NaN`, but both are equivalent.

**Comment by laurmaedje** [comment]
Yes, my point was that I'd rather have errors than NaNs.

**Comment by laurmaedje** [comment]
Not sure about having a dedicated type for complex numbers in a typesetting system in general, but I'm open to discussing that.

**Comment by HarmoGlace** [comment]
> Yes, my point was that I'd rather have errors than NaNs.

It should be good now

**Pull request merged**
