### PR TITLE
Remove restrictions to chroma and improve clamping

### PR DESCRIPTION
**Pull request by frozolotl**
This PR does a few small things:
- Oklab's a\*/b\* and Oklch's chroma components can be as large as desired.
- In PDF, when encoding Oklab, the range is widened from [-0.4,0.4] to [-0.5,0.5].
- In PDF, clamping is now performed on Oklch's chroma instead of a\* and b\*.
  This causes hue not to be distorted when clamping.

SVG and PNG export remain unchanged:
- SVG itself never had any restrictions on chroma.
  We directly use the `oklab` and `oklch` CSS colors, which should work fine for the most part.
  In the future, embedded ICC profiles might be nice. Further research is likely necessary.
- While PNG does not support color spaces like Oklab or Oklch, certain useful features exist.
  One can define gamma (gAMA) and chromacities&whitepoint (cHRM) chunks and even embed ICC profiles.
  While the `image` crate does not support these features for encoding, its backend crate `png` does support gAMA and cHRM.
  It does not allow embedding ICC profiles yet, though.

As it stands, to fully support wide gamuts and more accurate colors, more work is necessary.
This PR should help a bit though.

### CODE REVIEW

**Comment by frozolotl** [comment]
I noticed a bug where the chroma is unnecessarily restricted. I will fix it later today.

**Comment by frozolotl** [comment]
> You didn't change the PostScript code!

I think I did. Maybe GitHub has hidden it as a binary file?

**Comment by Dherse** [comment]
> > You didn't change the PostScript code!
> 
> I think I did. Maybe GitHub has hidden it in the diff as a binary file?

You're right sorry 👍

**Comment by frozolotl** [comment]
> I noticed a bug where the chroma is unnecessarily restricted. I will fix it later today.

Actually, everything is fine. My mistake.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
