### PR TITLE
Adjust for-loop's pattern matching rules

### PR DESCRIPTION
**Pull request by Leedehai**
Fixing #3275.

### CODE REVIEW

**Comment by Leedehai** [comment]
Beside addressing the issue about destructuring patterns as mentioned in #3275, this patch also make Typst allow `#for _ in "foo" {}`, which originally results in an error of `cannot destructure values of string`.

**Comment by PgBiel** [comment]
> Beside addressing the issue about destructuring patterns as mentioned in #3275, this patch also make Typst allow `#for _ in "foo" {}`, which originally results in an error of `cannot destructure values of string`.

I think that could potentially be ambiguous, since you could iterate over codepoints or graphemes. It seems you opted for graphemes.

Though I guess throwing an error isn't very useful either, so perhaps we should just make sure the choice is explicit in the docs and note that one should use explicit methods to opt for codepoints.

**Comment by laurmaedje** [comment]
> I think that could potentially be ambiguous, since you could iterate over codepoints or graphemes. It seems you opted for graphemes.

Iterating over a string's graphemes was already possible before. This PR just fixes that the placeholder pattern didn't work.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
