### PR TITLE
Don't let the build script overwrite TYPST_VERSION

### PR DESCRIPTION
**Pull request by figsoda**

### CODE REVIEW

**Comment by CGMossa** [comment]
Why is this useful? It is only set in the `build.rs` for the `cli` project, and nowhere else.

**Comment by figsoda** [comment]
I am trying to package typst for nixpkgs, and `.git` is not available by default, so this is what I ended up doing: https://github.com/nixos/nixpkgs/blob/f8cee53499c6caf3ec07d0e607121474d9f191ed/pkgs/tools/typesetting/typst/default.nix#L39-L47

**Review by CGMossa — CHANGES_REQUESTED** [review]
I would suggest to write this in a way, that makes the version stuff and this one unified "unit". Build scripts tend to build up fast, and having things in succinct units does help.

**Comment by CGMossa** [comment]
Suggested edit:
```diff
diff --git a/cli/build.rs b/cli/build.rs
index 1b37602f..515349ad 100644
--- a/cli/build.rs
+++ b/cli/build.rs
@@ -2,16 +2,17 @@ use std::process::Command;
 
 fn main() {
     println!("cargo:rerun-if-env-changed=TYPST_VERSION");
-    if option_env!("TYPST_VERSION").is_some() {
-        return;
-    }
+    let version = if let Some(version) = option_env!("TYPST_VERSION") {
+        version.into()
+    } else {
+        Command::new("git")
+            .args(&["rev-parse", "HEAD"])
+            .output()
+            .ok()
+            .and_then(|output| output.status.success().then(|| output))
+            .and_then(|output| String::from_utf8(output.stdout[..8].into()).ok())
+            .unwrap_or_else(|| "(unknown version)".into())
+    };
 
-    let version = Command::new("git")
-        .args(&["rev-parse", "HEAD"])
-        .output()
-        .ok()
-        .and_then(|output| output.status.success().then(|| output))
-        .and_then(|output| String::from_utf8(output.stdout[..8].into()).ok())
-        .unwrap_or_else(|| "(unknown version)".into());
     println!("cargo:rustc-env=TYPST_VERSION={version}");
 }

```

**Comment by CGMossa** [comment]
Damn.. I'm not sure this is strictly better... But it is a suggestion atleast 🤷‍♂️

**Comment by figsoda** [comment]
Either way is fine with me, applied some clippy suggestions since we are touching that part of the code

**Comment by laurmaedje** [comment]
I think the original version with `return` was fine and more readable. Regarding the clean up: The better version is probably:
```
.filter(|output| output.status.success())
```
Otherwise, this looks good to merge.

**Pull request merged**
