### PR TITLE
Strip trailing line breaks in math equations

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Fixes https://github.com/typst/typst/issues/693

### CODE REVIEW

**Comment by laurmaedje** [comment]
I think for consistency with text mode, this should strip only one trailing line break and not all.

**Comment by SUPERCILEX** [comment]
Why does text mode work that way? I'm not sure I see the value of having blank lines before nothing. Also, wouldn't you not be able to see the difference until you had so many they spilled onto a new page?

**Comment by laurmaedje** [comment]
Sometimes you just want blank lines with the normal line height, not necessarily before nothing but just before something that isn't part of the paragraph. I just see no reason to forbid it. In math, there is not really a reason to have it except for consistency.

**Comment by SUPERCILEX** [comment]
Gotya, seems reasonable.

**Pull request merged**
