### PR TITLE
Resolve #1141: Add hint for missing numbering, improve hint format consistency

### LINKED ISSUE #1141: Show how to add numbering if referencing unnumbered headings
### Description

The error message `only numbered headings can be referenced` should be supplemented by a hint on how to add the numbering. Submitted via user feedback.

### Use Case

Make the error message more actionable for novice users.

### PR DESCRIPTION
**Pull request by Mafii**
I kept the recommendation really short, as [codespan reporting](https://docs.rs/codespan-reporting/0.11.1/codespan_reporting/diagnostic/struct.Diagnostic.html) recommends:

> Message:  These should not include line breaks, and in order support the ‘short’ diagnostic display mod, the message should be specific enough to make sense on its own, without additional context provided by labels and notes.

I think it would make sense to have a way to report additional recommendations/fixes internally, so that the message can contain multiple parts while adhering to the codespan reporting recommendations. Maybe using codespan reporting's `notes`?

How to reproduce:

Create a `.typ` file with the following content:

```
= Introduction <intro>
In @intro, we see how to turn
Sections into Chapters. And
in @intro[Part], it is done
manually.
```

The content is straight out of the example for headings, with the `#set heading(numbering: "1.")` removed.

The user get's shown the following message now:

image

Is a test for this needed? If so, I'll happily write one.

This is my first contribution here, so if there is anything I can do better, no matter what, feel free to tell me!

### CODE REVIEW

**Comment by laurmaedje** [comment]
I want to have better infrastructure for tips like this, but for now this is fine. One change I'd like to see is to have everything lowercase. 

Regarding the separator between message and hint: We currently have two such "did you" hints. One is separate with a period and one with a colon and en-dash. Already inconsistent... I do not have a strong preference either way, so .

**Comment by Mafii** [comment]
>  One change I'd like to see is to have everything lowercase.

Done

> Regarding the separator between message and hint: We currently have two such "did you" hints. One is separate with a period and one with a colon and en-dash.

I've decided to streamline all to use a normal - character. I think it's reasonable to use the ascii character here, not the en-dash.
Hope that's okay! I'm happy to change it to any other variant if you want.

> I want to have better infrastructure for tips like this, but for now this is fine.

If I find the time, would you be happy to accept a PR for that? I'll happily experiment if there's a convenient way of doing this.

**Comment by laurmaedje** [comment]
I'm with you on using normal ASCII instead of en-dashes. Feel free to go ahead and replace that, too.

**Comment by Mafii** [comment]
I did a full text search for en- and em-dashes, the one in [3d6f63e](https://github.com/typst/typst/pull/1456/commits/3d6f63ef9873d5627db39ae47d56f0512189fe78) seems to be the last one that was not the ASCII character already.

**Comment by laurmaedje** [comment]
> If I find the time, would you be happy to accept a PR for that? I'll happily experiment if there's a convenient way of doing this.

I would be.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
