### PR TITLE
Custom outline indenting

### PR DESCRIPTION
**Pull request by PgBiel**
Right now, outline indenting necessarily uses a heuristic based on numbering, which can be harmful in some situations (see #421 and #711). This PR will allow more fine-grained customization of outline indenting, which can prove to be a nice workaround for these issues (and also to ensure consistency of the outline in some documents - probably needed to port from LaTeX in some cases).

## The new indenting options

- `outline(indent: none)`: the default, doesn't indent at all. (Equivalent to `false`, but deprecated.)
- `outline(indent: auto)`:  indents based on parent's numbering. (Equivalent to the current `true`, which would still be supported, but deprecated.)
- `outline(indent: 2em)`: indents by `n * 2em`, where `n` is the current element's depth (starting at 0 for top-level).
- `outline(indent: n => ...)`: indents by calling the given function with `n` for every line (where `n` is the line's depth starting at 0), and applying the returned indent content (e.g. `[----]` => place `[----]` at the start of the line).
   - **Note:** The function is also called for top-level headings/elements (it is then given `0` for `n`), so I added a comment about this to the documentation to avoid confusion.

See added tests for some samples.

### CODE REVIEW

**Comment by PgBiel** [comment]
Makes sense, though would the bool options remain available, or should we deprecate them? (At least keep them for one more release maybe, if we plan to remove them?)

**Comment by PgBiel** [comment]
Alright, so:

1. Added support for `none` and `auto`, while keeping support for `true` and `false` in a non-breaking way: while `none` and `false` are equally considered in the logic (just like `auto` and `true`), I made sure the boolean values would be preserved, in order to not break current code (which might use stuff like `it.indent` or `.where(indent: true)` or something, even though I think that's very rare for `outline` as there's usually just one).
<br/>However, I recognize that, ideally, we would have used just `none` and `auto` from the start. We can either deprecate this reflective usage of bool  (and thus have `true` actually map to `auto` later), which _could_ feel somewhat inconsistent with the rest of typst (where you can usually get the original value that was passed as a parameter), or deprecate the usage of boolean for `indent` altogether (probably makes more sense? Though it might be a scarily breaking change :ghost:).

2. Added support for arrays, but I'm not 100% sure on their design yet (or if they should indeed stay). Currently, I made indent arrays work with indents absolutely, i.e. each element in the array is the final value of the indent (like the function option does), not something multiplied by "depth" (like other indent option types do). That is, if you give `(4em, 4em)`, both your first and second depths will be indented by 4em in the end (they will look like they are at the same level), _not_ by 4em followed by 8em, as I thought this made sense (given that you already know the depth in advance, since it's the array index). The array can also take content (which is displayed without any changes for each corresponding depth). Worth saying that I also  made it error when given an empty array (would be redundant with `none`, I guess). While I am particularly satisfied by this design (as I think it simplifies usage when all you want is to customize a few indent values), there are two things to ponder about:<br/>
a. Right now, if the outline has more entry depths than the indent array has specified indents for, I simply repeat the last indent value in the array instead of raising an error. I think this should be fine, right?
b. I was kinda afraid that this could be thought as redundant with the function indent param, but, honestly, I guess you'd have to do something like `n => (h(1em), h(2em), h(3em)).at(n)` to achieve the same effect, so it seems valid to me for array to be a separate thing.

Either way, feel free to voice any concerns here, as I'm willing to change the current design if it is not optimal.

**Comment by laurmaedje** [comment]
I'm much less worried about breaking changes than you are. We can keep the booleans for a bit, but I would definitely remove them after a while. Would be ideal if we could have a warning system for deprecations, but oh well.

**Comment by PgBiel** [comment]
> I'm much less worried about breaking changes than you are.

That's fair, I may be going a bit too far here. Although I guess it's nice to maintain some sort of balance between breaking too much and too little, haha.

> We can keep the booleans for a bit, but I would definitely remove them after a while.

Yeah sure, sounds fair to me. We can probably keep them for like a release or so and then get rid of them.

> Would be ideal if we could have a warning system for deprecations, but oh well.

Yep... but that's okay, at least a changelog mention (and perhaps some short grace period) is much better than nothing, haha.

**Comment by PgBiel** [comment]
Alright, updated docs to reflect the new array option and made general improvements to it, such as indicating that `true`/`false` are deprecated. Also made it so the indent function can return spacing lengths or `none` (besides content).

I'm just not 100% sure regarding the documentation example, as I showed one possible usage of each possible option type (just some samples all around to make things easier to understand), which might make the preview a bit large (since it's several outlines), but I reduced the amount of headings in an attempt to mitigate that problem. Feel free to change that example though as you see fit.

**Comment by PgBiel** [comment]
Also, I didn't add support for arrays containing (or functions returning) `auto` yet, but I'm not sure if that's worth it. Tell me if you think this is enough.

**Comment by PgBiel** [comment]
Thank you for the constructive feedback! Your concerns are totally understandable, and I will work on the needed improvements. In particular, I think the idea that we should have less options to reduce complexity is valid.

I'd just like to mention that my reasoning for the array option in specific was mostly similar to that presented in https://github.com/typst/typst/issues/1087 - users usually don't want to resort to such things in common usage. Given the table precedent, I considered that it might be inevitable that a feature request for this would eventually appear as well. Either way, I'll remove them as suggested, but feel free to share any further considerations you might have regarding this. 

Regarding this:
> Last but not least, we should consider how these changes interact with future outline customization based on function scopes (e.g. #show outline.item: ..) (...) it would still be good to be forwards compatible here.

That's indeed very important to consider! At first, related to that, I thought that the indentation function could take each outline item as parameters (which could give us not just the depth level but more). However, upon further thought, I considered, instead, that the current implementation in this PR could be kept (for common use cases) and have indentation always apply to outline items (regardless of what they're replaced by), while, if full customization is needed, one could simply disable indentation and manually add it in a possible show rule for the outline.item. I think that should work, and thus we wouldn't have many concerns regarding this, but feel free to share any further ideas here. Thank you again! I'll get to work.

**Comment by laurmaedje** [comment]
> Given the table precedent, I considered that it might be inevitable that a feature request for this would eventually appear as well.

I see your point, but I think differing table alignments are _much_ more common than differing outline indents.

> I think that should work, and thus we wouldn't have many concerns regarding this, but feel free to share any further ideas here.

I tend to agree. Overall, better show rule selectors are just more flexible than callback functions.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
