### PR TITLE
Add 'layout' function to obtain the size of the outer container

### PR DESCRIPTION
**Pull request by PgBiel**
Hello!
We discussed in Discord the possibility of adding an easier means of obtaining the outer container's (or page's) dimensions from within any element/content.

This PR should make it possible with the syntax of `layout(size => {... element using size.width and size.height ...})`, which always returns the dimensions of the outer container, or of the page (excluding margin).

From my tests, all seems to be working; just one thing seems off: when working with certain very tight dimensions, at some point the incredible height of `infpt` was produced (try, for example, removing the line `#set page(height: 120pt)` from the `block-sizing` test).  I will try to later investigate if fixing this is possible, or the cause of this in the first place, but I appreciate any help in this regard from other contributors.

Also, feel free to say if this function is better suited for another category, or if the tests should be changed / more tests should be added. (Do not worry, I made sure the PNGs were optimized, haha.)

### CODE REVIEW

**Comment by laurmaedje** [comment]
infpt happens when the page size is `auto`.

**Comment by PgBiel** [comment]
> infpt happens when the page size is `auto`.

Well, that explains it; I'm guessing (from the fact that `measure` doesn't check for this, though I don't know if it can be affected) that this (infpt) should be the expected output for the end user then? Or should we maybe return some other value instead, such as 0pt, or `auto` itself (which could be slightly undesirable in terms of units, but could also be an acceptable alternative to the others)?

**Comment by laurmaedje** [comment]
I think infinity is fine.

**Comment by PgBiel** [comment]
> I think infinity is fine.

Alright! I've added this to the proposed documentation then, just in case (to avoid possible questions regarding this :p).

**Pull request merged**
