### PR TITLE
Add `quo`, `trunc` and `fract` calculation methods and rename `mod` to `rem`

### PR DESCRIPTION
**Pull request by HarmoGlace**
This PR adds the `quotient`, `truncate` and `fractional` methods. This is a small PR but theses methods are convenient.

~Note that the `mod` method is called `mod`, but should instead be called `rem` for remainder to be consistent. Is it worth the rename? (It would be a breaking change)~ The `mod` function is renamed to `rem`, which is a breaking change.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Changing to `rem` seems sensible. Not sure about the name `quo`, does it have any precedent?

**Comment by HarmoGlace** [comment]
> Maple uses `quo` apparently.
> 
> Isn't the more common approach here to have a single `div` (name is not important) function that returns both the quotient and remainder?

Why not, maybe that we could name it `euclidian_div` or something like that? Should we replace both `mod` and `quo` with this function would be a breaking change too unfortunately

**Comment by HarmoGlace** [comment]
> Changing to `rem` seems sensible. Not sure about the name `quo`, does it have any precedent?

It is commonly named like that, I see that on several calculators and others librairies.

The issue with the `mod` naming is that, for instance `a modulus b` is `a +kb`, where k is a relative integer. Whereas `rem` really means the reminder in the euclidian division of `a` and `b`, it is a specific modulus.

**Comment by HarmoGlace** [comment]
> > > Maple uses `quo` apparently.
> > > Isn't the more common approach here to have a single `div` (name is not important) function that returns both the quotient and remainder?
> > 
> > Why not, maybe that we could name it `euclidian_div` or something like that (shorter)? If we replace both `mod` and `quo` with this function would be a breaking change too unfortunately
> 
> I think mod is used often enough to warrant a separate function.
> 
> I'm just imagining that if you want the quotient you probably want both of them. And if you don't, it's very easy to compute with floor.

I understand the need of a separate function which reunites both. But in some cases, the `quo` function is needed, without the `mod` (`rem`) function. Of course it is way easier to replicate its behavior with `mod`, but if there was a `quo` function in the first place but no `rem` function, it would also be trivial to replicate the `rem` function. I think that for clarity/readability we should have both functions.

For another `euclidian_div` function, this is a good idea. I'm going to implement it.

**Comment by laurmaedje** [comment]
I'm against an extra euclid_div function. You can just call the two functions, separately. I'm in favor of renaming "mod" to "rem" though. About "quo", I'm still unsure.

**Comment by HarmoGlace** [comment]
> I'm against an extra `euclid_div` function. You can just call the two functions separately.

This would allow something like `#let (rem, quo) = calc.euclid_div(x, y)` in only one call, but I understand that it makes an extra function which might not be really useful.

> I'm in favor of renaming `mod` to `rem` though. About `quo`, I'm still unsure.
I'm going to rename it then. For `quo`, in the tools that I use it is always called `quo`, I don't have any better naming.

**Comment by laurmaedje** [comment]
okay, then let's remove euclid_div and let quo be as is

**Pull request merged**
