### PR TITLE
Adds `arguments.len()` (#1135)

### PR DESCRIPTION
**Pull request by jassler**
Adds feature request in #1135

### CODE REVIEW

**Comment by jassler** [comment]
Added `is_empty()`

**Comment by PgBiel** [comment]
Shouldn't this be the sum of the lengths of positional and named arguments?

**Comment by jassler** [comment]
I think `.items()` fetches all items. In [`to_posed()`](https://github.com/typst/typst/pull/1136/files#diff-09d753556b3111fb2c852bb8ed0eecb93793a2e8a31e9ceb740f080db410ba3cR182) and [`to_named()`](https://github.com/typst/typst/pull/1136/files#diff-09d753556b3111fb2c852bb8ed0eecb93793a2e8a31e9ceb740f080db410ba3cR191) they filter out the "undesirable" arguments.

**Comment by jassler** [comment]
This just made me realize that I also didn't quite understand `named()` and `pos()`. I thought both of them would just fetch all arguments and not filter out anything.

**Comment by jassler** [comment]
I made some more notes in the [issue](https://github.com/typst/typst/issues/1135#issuecomment-1539156440) that the change might lead to some confusion.

**Comment by laurmaedje** [comment]
I think there is no clear way forward here, right?

**Comment by jassler** [comment]
No, especially if the use of `arguments` might change in the future.

**Pull request closed without merging**
