### PR TITLE
large operators have limits in displays; relations have limits always

### LINKED ISSUE #1720: Change equal sign attachment to limits
### Description

Currently attachments to the equal sign and all the other "equal related" symbols are placed as sub/superscripts. I think they should all instead be rendered as limits. 

### Use Case

I think most people use attachments with equal signs to state why an equality/inequality/thingy holds. Those things usually get written on top of the symbol. For example when you want to denote that you're using the induction hypothesis:

`$ =^"IH", quad limits(=)^"IH" $`
image

 I can't actually think of any usecase where you would want an attachement to be placed as a sub/superscript and writing `limits(=)` so often is exhausting.

### PR DESCRIPTION
**Pull request by damaxwell**
Closes #1720

This PR implements the following default policy limit vs. scripts attachments:
- `MathClass::Large` operators that are not a species of integral sign have limit attachments at display sizes.
- `MathClass::Large` operators that are also integral signs have scripts attachments at all sizes
- `MathClass::Relation` characters have limit attachments at all sizes

These defaults can be overridden, of course, with `limits` and `scripts`.

## Notes

There are 68 different unicode math class Large characters listed in the official [data file](https://www.unicode.org/Public/math/revision-14/MathClass-14.txt). Of these, the LaTeX package `unicode-math` only categorizes 62 of these as type `\mathop` -- see its [categorization table](https://github.com/wspr/unicode-math/blob/master/unicode-math-table.tex).  The outliers are 
- U+0606 and U+0607 (arabic script cube and fourth root)
- U+221A -- U+221C (square root, cube root, fourth root)
- U+27CC (long division, a cousin of the square root glyph)

The first two of these are not included in the `unicode-math` table, and I suspect this is because they have Unicode script property `Arab` rather than `Zyyy`, undetermined, which seems to be what all the other symbols are.  The remaining four are all given class `\mathopen`, corresponding to `MathClass::Open`, which seems more reasonable than the official classification.  Regardless, I did nothing to make an exception in any of these six cases.  If you're putting attachments on the long division glyph, no default seems reasonable and best of luck with that. ;-)

The `unicode-math` [PDF list of symbols](https://mirror.las.iastate.edu/tex-archive/macros/unicodetex/latex/unicode-math/unimath-symbols.pdf) clearly shows which large operators default to limits and which to scripts.  It's exactly the list of integral-like glyphs and agrees with this PR.

For `MathClass::Relation`, I chose a limits policy of `Always` so that inlined text `$a =^"def" b$` would typeset with limits.  If showing limits at `Display` and `Text` sizes only had been an option, I would have gone with that.

### CODE REVIEW

**Comment by Enivex** [comment]
For MathClass::Relation, I chose a limits policy of Always so that inlined text $a =^"def" b$ would typeset with limits

I don't think this is a good idea. They should only default from limits for display math, for the same reasons as for operators. One may quickly run into issues with interference between lines, or inconsistent line distance.

**Comment by Enivex** [comment]
> For MathClass::Relation, I chose a limits policy of Always so that inlined text $a =^"def" b$ would typeset with limits

I don't think this is a good idea. They should only default from limits for display math, for the same reasons as for operators. One may quickly run into issues with interference between lines, or inconsistent line distance.

**Comment by damaxwell** [comment]
Yup, there's a judgement to be made here, which is why I included this choice explicitly in the notes.  The poster of the original issue seemed to be of a different opinion: 

> I can't actually think of any usecase where you would want an attachement to be placed as a sub/superscript and writing limits(=) so often is exhausting.

At any rate, relations are, by and large, smaller glyphs than the large operators, and issues with bleeding into the interline space are less serious. Compare:
image
There's a good reason to not put that 30 on top of the sum.  Doing the same, by default, for the relations seems less compelling, especially given the alternative layout as a script doesn't lead to a ton of space savings and is probably not a desired layout.  But it's for sure a judgement, and reasonable people can differ.  It's easy enough to go with `Display` if that's what is decided in the end.  And whatever default is set, it can be easily overridden.

**Comment by Enivex** [comment]
It's _possibly_ defensible for some relations that aren't too tall, but it would be highly dependent on too many factors. Even in your example you can see that the def is placed slightly higher than the 30 on the sum. The f would almost touch a descender on the line above. Not to mention if the line above had another relation with a limit below it. They would definitely collide.

Don't get me wrong, I'm all for making limits the default for relations in display math. But I don't see any reasonable alternative to making script the default in inline math.

**Comment by damaxwell** [comment]
My understanding of the motivation for the issue (and hence the PR) is the perception that the usual use case for decorating a relation with an attachment is something  like what `\stackrel` does, and that the alternative of typesetting with a script is usually not what is wanted.  If this is the case, then a reasonable choice for the default would be to do as `\stackrel` does: inline or display, the decoration goes above/below the decor-ee.  If done in inline mode, the price you pay is that sometimes this results in a bit of extra interline space to prevent collisions.  I think the possible disagreement here is simply over which tradeoff is worse for the default.  One perspective is that trying to keep interline variations to a minimum is more important, the other is that extra interline space is ok (if needed) if the alternative is a layout that is typically not what's wanted.  Both are positions that have their merits.

I'd be curious to see real-world use cases of `$ relation^decoration $` or `$ relation_decoration $` where for the same relation/decoration pair, if limits are set in display style and if scripts are set in text/inline style, then in both cases the same author is likely to go "yeah, looks good enough, that's my intent".  This is what happens with the large operators; it's not clear to me that the same thing happens when decorating relations.

Regarding interline collisions, Typst should be responsible for automatically ensuring (possibly after certain settings are chosen) that they just don't occur.  It already makes an attempt, but it seems this could be improved, even for the basic case of  inline math large operators with scripts:
image
TeX's triple of `\baselineskip`, `\lineskiplimit` and `\lineskip` can be set so that they do prevent collisions, but Typst uses a somewhat different model for interline spacing.

**Comment by laurmaedje** [comment]
The collisions will definitely be prevented in the future, the current implementation is just bad. Regarding the topic of limits vs scripts: I'm not a mathematician but from my limited understanding limits vs scripts on large operators is mostly a matter of style whereas "def" as a subscript seems different enough from "def" as a top attachment for it not to differ just based on display vs inline.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
