### PR TITLE
Add alpha component to luma

### PR DESCRIPTION
**Pull request by frozolotl**
I think luma deserves to have an alpha component. This PR adds one.

### CODE REVIEW

**Comment by istudyatuni** [comment]
Probably it's better to make it 1 by default

**Comment by frozolotl** [comment]
> Probably it's better to make it 1 by default

It is one by default though? Or am I miswing something?

**Comment by istudyatuni** [comment]
From tests I thought that you should always pass second argument, but i missed one line, where it's not passed, sorry

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
