### PR TITLE
Refactor sub- and superscript substitution

### LINKED ISSUE #5112: Typographic superscript / subscript spaces are too large
### Description

In fact, with `typographic: true`, spaces are kept as regular spaces. I'm unsure this is desirable.

```typ
#super(typographic: true)[1 2 3] \
#super(typographic: false)[1 2 3]
```

The spaces in the first line are very large.

### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by MDLC01**
The first commit contains some minor code quality improvements.

The second commit fixes #5112.

### CODE REVIEW

**Comment by laurmaedje** [comment]
If I understand correctly, this will disable typographic superscripts completely if there's a space, right? That's kind of unfortunate considering the space doesn't really need a separate glyph to be shrinkable.

**Comment by MDLC01** [comment]
Indeed. There was [more discussion on Discord](https://discord.com/channels/1054443721975922748/1277628305142452306/1291732983774052353) on whether the typographic script feature even makes sense. I can revert the second commit and keep only the code quality improvements if you want (or close the PR completely).

**Comment by laurmaedje** [comment]
We can keep the code quality improvements and discuss the rest for 0.13.

**Comment by MDLC01** [comment]
Done

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
