### PR TITLE
Make under/overlines behave the same as accents in attach base

### LINKED ISSUE #4692: Overline shifts subscripts
### Description

```typst
$
  y_i macron(y)_i overline(y)_i
$
```
renders as
image

### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by mkorje**
This PR makes it so that the content's `italics_corrections` and `is_text_like` are passed onto the finished frame fragment with an under/overline. When an under/overline element is the base of an attachment, this brings it more in line with the behaviour of accents.

Whether this is the 'best' thing to do, I don't know. I guess it depends on which of the two people prefer most. Or, if this just shouldn't be the approach taken to this at all. I find that with the underline, the bl and br attachments seem to high, despite it being more 'consistent'.

Example 4 shows the br attachment colliding with the underline. So it seems passing `italics_corrections` all the time isn't ideal either...

<details>
<summary>Example 1</summary>

```typst
#set page(width: 1.5cm, height: 1.2cm)

$ attach(y, t: i, b: i, tl: i, bl: i, tr: i, br: i)
  attach(macron(y), t: i, b: i, tl: i, bl: i, tr: i, br: i)
  attach(overline(y), t: i, b: i, tl: i, bl: i, tr: i, br: i) $
```
Using the above typst code:
<details>
<summary>Before</summary>

overunderline_old
</details>

<details>
<summary>After</summary>

overunderline_new
</details>

<details>
<summary>Diff</summary>

overunderline_old
</details>

And another comparison https://www.textcompare.org/image/?id=66b24dbd116d31c8d023e3a7.
</details>

<details>
<summary>Example 2</summary>

```typst
#set page(width: 2cm, height: 1.2cm)

$ attach(overline(underline(y)), t: i, b: i, tl: i, bl: i, tr: i, br: i)
  attach(underline(y), t: i, b: i, tl: i, bl: i, tr: i, br: i)
  attach(overline(y), t: i, b: i, tl: i, bl: i, tr: i, br: i)
  attach(underline(overline(y)), t: i, b: i, tl: i, bl: i, tr: i, br: i) $
```
Using the above typst code:
<details>
<summary>Before</summary>

overunderline_old
</details>

<details>
<summary>After</summary>

overunderline_new
</details>

<details>
<summary>Diff</summary>

overunderline_old
</details>

And another comparison https://www.textcompare.org/image/?id=66b25137116d31c8d023e3b9.
</details>

<details>
<summary>Example 3</summary>

overunderline_old
</details>

<details>
<summary>Example 4 (Collision with subscript!)</summary>

overunderline_old
</details>

<details>
<summary>Example 4 (Again, but not passing italics_corrections)</summary>

overunderline_old
</details>

Closes #4692.

## TODO
- [x] Add tests
- [x] Improve the logic around passing/using `italics_corrections`

### CODE REVIEW

**Comment by Enivex** [comment]
It seems to me that with italics correction the underline should be shortened? It looks way too long

**Comment by Enivex** [comment]
These pictures, and the fact that we haven't made the overlines shorter, is making me wonder:

Why isn't the top-left attachment affected by italic correction? It looks weird when the left hand-side attachments are vertically aligned, but the right-hand side ones aren't.

**Comment by laurmaedje** [comment]
The changes look good to me. Is this ready to merge from your end or are we still discussing what's best?

**Comment by Enivex** [comment]
I think the overline stuff can wait, so it should be alright now.

Maybe we can get New Computer Modern Math to include the data at some point. (Though attachments on the left are less common.)

@mkorje

**Comment by laurmaedje** [comment]
Okay, thanks!

**Pull request merged**
