### PR TITLE
Add `outline.entry`

### PR DESCRIPTION
**Pull request by PgBiel**
This element should allow for further outline customization through show rules.
Closes https://github.com/typst/typst/issues/731 (see example below).

# Highlights
- Each line in an outline is wrapped in an `outline.entry` element now; this includes not just the heading titles (the outlined elements in general), but also the fill content and their page numbers.
- The current design is `#outline.entry(level: 1, element: the-referred-heading-or-something, outline: [1. Heading title with rendered number], fill: repeat[-])`. The `#outline` creates an entry with all that information on `Show` for each element it finds, and the entry is responsible for displaying it all in its own `Show`, including fetching the page number.
- This makes it possible to do something like `#show outline.entry.where(level: 1): strong` to make top-level entries bold, or `#show outline.entry.where(level: 2): set text(red)` to set text color in single-nested entries to red (including page number and fill content on those last two cases).
- The `outline` property is mostly useful for more advanced customization, where you use `it => ...` rules (see the tests and docs for examples).
  - I concede, though, that it could be better to just add some sort of `.outline()` (or similar) method to Outlinable content instead of depending on the entry for this information. This is debatable, though. For now, the current design works, but I can make such a change / refactor if needed.
  - Regarding user-constructed entries, what do you think about being able to specify `auto` for the `outline: ` parameter to have it read the element's outline automatically (and also for `level:`)? It might break show rules, however, which kinda sucks...
    - Exposing `OutlineEntry::from_outlinable` as a function under entry's function scope could also work (to generate an entry from an outlinable element), but I think I'd just prefer adding something to Outlinable elements themselves to be able to fetch their outlines at that point.
- Note that I made `outline.entry` not check _on `Show`_ if its element is Outlinable, since that check is already performed when it is constructed by an `outline` (in the `OutlineEntry::from_outlinable` function). It only checks if the element is locatable, as that's necessary to add a link to it (the element's outline is already provided by - and can be customized through - the `outline` property). Still, I can add another full Outlinable check there if that's preferred (as users can construct arbitrary entries, theoretically).
- Added tests and a good amount of docs (feel free to ask about or request anything here).

### CODE REVIEW

**Comment by azerupi** [comment]
Is it possible to access the page number somehow and format it the same way as it is on the page?

I'm modifying the level 1 headings to make them bold and remove the fill as show by the code snippet below. But doing this means I'm losing the page number formatting.

```typ
show outline.entry.where(level: 1): it => {
    set text(font: sans-font)
    
    let heading_page = counter(page).at(it.element.location()).first()
    
    strong({
        it.body
        h(1fr)
        [#heading_page]
    })
}
```


**Before**
image

**After**
image

**Comment by laurmaedje** [comment]
You can get it via `it.element.location().page-numbering()` and apply it to the page counter with the `numbering` function. It is a bit complicated currently, but this PR was intentionally kept minimal as a starting point.

**Comment by azerupi** [comment]
Excellent, that worked. Thanks!

Would it make sense to expose the already formatted page number in the outline.entry to avoid this complication?

**Comment by laurmaedje** [comment]
> Would it make sense to expose the already formatted page number in the outline.entry to avoid this complication?

Perhaps yes.

**Pull request merged**
