### PR TITLE
Add scaling of inner fences in lr

### PR DESCRIPTION
**Pull request by maxtremblay**
:bangbang: __Breaking change__

### Description

This modifies the lr function such that inner fences `|` scale with the outer delimiters. I also updated the visual tests file accordingly.

Here are two examples of the new behavior

```
$ ((x / 4) / 2 | y) $
$ lr(brace.l x in CC | (norm(x) / 2)^2 = 1 brace.r) $
```

20230326_21h15m56s_grim

### Missing feature

It would be nice if there was a simple way to turn that behavior off. I was hoping that using something like `bar.v` instead of `|` could prevent the scaling, but I didn't figure out how to do it. Another solution is to add a boolean argument to `lr` to turn the fence scaling on or off. I can implement that, but I would prefer to have some feedback before.

### Tests 

Looking at the CI outcome, I understand I need to update the reference PNG figures. I have no idea how to do this. I also fix the spacing around different tests to make everything more uniform.

### CODE REVIEW

**Comment by laurmaedje** [comment]
This seems sensible, but the fact that the scaling isn't easily prevented by escaping or symbol notation is indeed problematic. This would break the user's expection. As you have noted, its not easily fixed and I believe that's also the reason why I didn't do this. This would somehow need to be handled at the parser level so that the distinction can be made. I can take a closer look when I find the time.

**Comment by maxtremblay** [comment]
@laurmaedje Let me know if I can help with anything. I really want this feature in typst. This is quite useful for dirac notation.

**Comment by Leedehai** [comment]
(I'd like to add a note that this PR is an attempt at FR https://github.com/typst/typst/issues/240)

**Comment by laurmaedje** [comment]
Unfortunately, this will require a more involved approach, [along these lines](https://github.com/typst/typst/pull/641#issuecomment-1500093595).

**Pull request closed without merging**
