### PR TITLE
Add rounded corners and strokes to highlight

### PR DESCRIPTION
**Pull request by frozolotl**
The title should be rather self-explanatory.
An image showcasing the implemented features

Implements some of the changes requested in #2934.

### CODE REVIEW

**Comment by frozolotl** [comment]
Actually, I have one question: the previous version used the `width` parameter to calculate the size of the box, while this one doesn't.
Could this cause any problems?

**Comment by laurmaedje** [comment]
The `width` parameter seems to be completely redundant with the `item` parameter. However, you did indeed spot a problem. The `frame` might contain more text items if font fallback of y-offsets from shaping are involved and then `fill_and_stroke` won't work (my bad).

**Comment by frozolotl** [comment]
> The `width` parameter seems to be completely redundant with the `item` parameter. However, you did indeed spot a problem. The `frame` might contain more text items if font fallback of y-offsets from shaping are involved and then `fill_and_stroke` won't work (my bad).

Good thing that I still had the previous version saved then. It's pushed. (Though it appears before your message even if I pushed it after the message, which is interesting.)

**Comment by MDLC01** [comment]
Doesn't this make `highlight` become redundant with `box`?

I think a difference is that a box cannot be broken into multiple lines, but I assume this is a behavior that will change in the future?

**Comment by frozolotl** [comment]
> Doesn't this make `highlight` become redundant with `box`?
> 
> I think a difference is that a box cannot be broken into multiple lines, but I assume this is a behavior that will change in the future?

`highlight` will not become redundant. In fact, it will just become more useful.
 
The non-breaking behavior of `box` is very useful when you want words explicitly to not break. For instance, `#box[isn't]` shouldn't break at the `'` boundary.
Additionally, you can `#set highlight(fill: red.transparentize(50%), stroke: 1pt)` and every time you call `#highlight[Lorem ipsum.]`, the relevant settings will be used.
This isn't really possible with `box`, unless one manually adds a `#let highlight(…) = box(…)` definition. But then you will simply have a less powerful version of `highlight`.

**Comment by PgBiel** [comment]
> Doesn't this make `highlight` become redundant with `box`?
> 
> I think a difference is that a box cannot be broken into multiple lines, but I assume this is a behavior that will change in the future?

That reasoning doesn't really apply, because it would also have applied to the creation of `highlight` itself :sweat_smile: 

I see no reason why that would change in the future. Highlight and box are just serving very different purposes here, as I see it. And, as frozolotl mentions, there are lots of use cases for unbreakable/non-wrapping stuff in text.

**Comment by Mc-Zen** [comment]
Oh, I forgot about this but had a related issue with highlight some time ago already:

```typ
#highlight(fill: gradient.linear(red, blue))[asd *as* d]
```
unfortunately produces:
image

**Comment by PgBiel** [comment]
As I see it, that example shows it's already a problem, so I'd say this PR could be considered independently of it (although it would be nice to fix it of course, but doesn't sound too simple).

**Comment by laurmaedje** [comment]
> As I see it, that example shows it's already a problem, so I'd say this PR could be considered independently of it (although it would be nice to fix it of course, but doesn't sound too simple).

Okay, that's fair enough.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
