### PR TITLE
Check actions with dependabot

### PR DESCRIPTION
**Pull request by danieleades**
adds a dependabot config file for keeping github actions up to date

### CODE REVIEW

**Comment by danieleades** [comment]
I'm actually not 100% sure how dependabot will handle the rust toolchain action. If it starts spitting out PRs to update the MSRV then it will need to be suppressed for this action

**Comment by laurmaedje** [comment]
I don't really like dependabot, I feel like it spits out too many PRs. I'd rather update everything manually at once every once in a while.

**Comment by danieleades** [comment]
> I don't really like dependabot, I feel like it spits out too many PRs. I'd rather update everything manually at once every once in a while.

that really depends on the nature of your project and the way you're using dependabot. For a library, dependabot PRs are very sparse- they are only created for major versions. For a binary (like this project) the PRs can be very noisy, but there is config for clamping how often they are created, how many can be alive at once, etc.

I've only added dependabot config for github actions, so PRs are very few and far between. They also tend to be high-value and related to upstream security issues.

**Comment by laurmaedje** [comment]
Can it be configured to only happen for security issues in actions?

**Comment by danieleades** [comment]
> Can it be configured to only happen for security issues in actions?

You *could*... but what would be the motivation? And that will only work if the author's log a vulnerability in a security registry, by no means guaranteed.

There are only a handful of actions used in this repo, which have only had a couple of major updates each. You could count the total number of dependabot PRs you would have had to date on your fingers if you'd had it enabled from the moment it became publicly available a few years ago.

*Had it been enabled*, you'd currently be using V4 of the checkout action, the major release of which otherwise flies under the radar. that's the functional benefit.

**Comment by laurmaedje** [comment]
I guess it doesn't have much of a downside. I just don't like adding new tooling and config files to solve things that didn't ever cause problems. I have never in my life had a problem because of an outdated GitHub action.

I'm okay with merging this one with a reduced schedule (1/day is just unnecessary). But I wanted to elaborate a bit on why I have an internal resistance.

**Comment by laurmaedje** [comment]
(1) debouncing if they release with issues
(2) it jus t_feels_ pointless to have this rather unimportant thing be checked every day

but it doesn't really matter and I don't have the energy to continue arguing here

**Pull request merged**
