### PR TITLE
Better errors for array/dictionary method calls that return mutable

### PR DESCRIPTION
**Pull request by Leedehai**
Fixing #3154.

These `.._mut()` methods are called when the value was evaluated from an expression that is the lhs operand of a `BinOp::*Assign` expression.

### CODE REVIEW

**Comment by laurmaedje** [comment]
I'm not a big fan of the "so cannot get a mutably entry from it" messages. I think having `array.first() = 1` yield `array is empty` is pretty reasonable. The problem in #3145 is imho more the "no default specified" part. Specifically, I think `array.at(1) = 4` should just yield `array index out of bounds (index: 1, len: 1)` without the default part. For dictionaries, we could also add a hint that `insert` should be used when the key doesn't exist yet, e.g. error `dictionary does not contain key "b"` with hint ``use `insert` to add a new pair instead``.

**Comment by Leedehai** [comment]
> The problem in #3145 is imho more the "no default specified" part.

Hi, this PR _is_ addressing the "no default specified" part - the error message for `.at(i) = ..` and `.at(i, default:..) = ..` is trying to say "I know you may have provided the default value, but this assignment requires an entry from within the array/dict, and I can't retrieve such an entry because the index/key doesn't exist".

But what you said above also sounds good to me. Please advise.

**Comment by Leedehai** [comment]
Sure, updated the PR. However, I did not add the hint of `use `insert` to add a new pair instead` because the method requires a return type of `StrResult<..>` not a `HintedStrResult<..>`.

**Comment by laurmaedje** [comment]
If you add a new impl `IntoResult for HintedStrResult` in `cast.rs` it should work. It's missing that.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
