### PR TITLE
font: upgrade New Computer Modern fonts to 5.1

### PR DESCRIPTION
**Pull request by mkroening**
Version 5.1 was released today: https://download.gnu.org.ua/release/newcm/

### CODE REVIEW

**Comment by laurmaedje** [comment]
Keeping this font up to date will really bloat the repository over time... Not sure what to do about that, but at least I would wait until the next release before merging in case there's another update.

**Comment by Enter-tainer** [comment]
you may spilt fonts into a new repo and use submodule. or use git lfs

**Comment by laurmaedje** [comment]
While Git LFS sounds nice in theory, GitHub's pricing is just ridiculous. They provide a small amount of bandwidth and every clone by any user is counted against that. I'm not really familiar with using submodules, so can't yet comment on whether that would be a good solution.

**Comment by alerque** [comment]
Neither Git submodules nor LFS are good options for this. If embeding fonts into the release binary is going to be a thing, I do agree it is going to bloat the source repository over time which will cause problems down the road. It's easy to say "oh it's just a couple megabytes" now, but that's not the end of the story.

I suggest removing them from the tracked sources entirely and making them a build time dependency. Then either an external system can provide them or an internal build script can fetch them and bake them into the build without the binaries being part of the version-tracked source tree. For consistency the exact expected version can be specified and a hash used to verify that the correct asset is being embeded.

**Comment by laurmaedje** [comment]
Based on this, the current plan is to create a custom https://blobs.typst.org storage with a small CLI utility that pushes files there under hash paths. Then, we just list file names and hashes for files we need here in this repo and use Rust's build.rs to download the relevant assets when they are needed. The storage would be append-only to keep reproducibility for older builds. This would also fix our issue with uploading typst-cli to crates.io because of size limitations (which Git LFS wouldn't give us).

Through the nature of the permissions to this storage, contributors couldn't add new files there and thus things like updating fonts would need to be done by a maintainer. However, I'm already checking whether the binary files in a PR such as this one match with what I can download from CTAN because there is no other way to "review" a binary blob. So it's not much more work.

**Comment by alerque** [comment]
Sounds good. Just be sure the build can be run in offline mode. Whether that means downloading and placing the blobs somewhere locally or having them wrapped in another crate that can be retrieved with `cargo fetch`, the actual build step needs to work offline (as in `cargo build --frozen`).

**Comment by laurmaedje** [comment]
I was thinking of caching them in a local dir within the repository and checking that before downloading anything. Either a gitignored top-level directory or somewhere within Rust's `target` dir.

**Comment by alerque** [comment]
Sure, that sounds fine. Just make sure if you are writing a download function in, say, `build.rs`, that the code there checks and respects the value of `cargo build`'s `--offline` flag. It's okay to panic if you a) can't find the needed resources and b) are not allowed to fetch them, but it's not okay to try to fetch anyway if offline mode has been requested.

**Comment by drupol** [comment]
> Keeping this font up to date will really bloat the repository over time... Not sure what to do about that, but at least I would wait until the next release before merging in case there's another update.

How about downloading them during the build?
Technically those fonts should be considered as optional dependencies, they should not live in this repo but being downloaded during the build, don't you think ?

**Comment by laurmaedje** [comment]
> How about downloading them during the build?

See the discussion above.

I will implement the plan laid out above before the next release and also bump New CM myself then.

**Pull request closed without merging**
