### PR TITLE
Add optional chaining operator (?.)

### PR DESCRIPTION
**Pull request by bluebear94**
See #1394.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Although the tests pass, the implementation is broken. You can change the assertion to something else (e.g., `#assert.eq(a?.len(), 10)`) and the test still passes. I don't know exactly what happens, but the optional field access is never evaluated because `<Expr as AstNode>::from_untyped` is lacking the cast from `SyntaxKind::OptionalFieldAccess`.

Aside from this, I am not completely convinced of this operator. 
In #1394, the example for this operator is `return structure?.at("footnotes", default: none)?.at(0, default: none)?.body`, which doesn't read all that well to me. Perhaps it is an improvement over the status quo, but I don't think that this is the _best_ solution we can come up with. 

In TypeScript, I always felt that the `?` operator is quite inflexible. It only works with field access. As soon as you want to do something else, e.g. add 2 to x unless it is none, you are back to the ternary: `x != none ? x + 2 : none`. _If_ we add some construct to improve dealing with `none`, I would wish for it to be a bit more expressive.

**Comment by bluebear94** [comment]
I’ve fixed the implementation bugs, but I agree that this feature needs more thinking about design before it’s ready to be merged.

**Comment by laurmaedje** [comment]
I'll mark it as draft then.

**Comment by bluebear94** [comment]
How about the following design?

Add a postfix `?` operator (so we don’t need to implment `.?` separately for field accesses and method calls). `try { expr }` would evaluate `expr`, except that using `?` on a `none` value would exit the block and return the `none`. Then `try { expr1 } else { expr2 }` could be syntactic sugar for `{ let val = try { expr1 }; if expr1 == none { expr2 } else { expr1 }}`.

The two examples you gave would then be

```typst
return try { structure?.at("footnotes", default: none)?.at(0, default: none)?.body }
try { x? + 2 }
```

**Comment by laurmaedje** [comment]
What I still don't like about this is the `.at("footnotes", default: none)`. It feels very noisy to me to use a at + string instead of a field access just for the none handling.

**Comment by bluebear94** [comment]
There could be a dedicated syntax for `at`, such as `.@footnotes` for the `default: none` case, but I can’t think of a syntax for when you need a different default value. Perhaps this role could be filled by a dedicated `none`-coalescing operator, akin to JavaScript’s [`??`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) or Raku’s [`//`](https://docs.raku.org/routine/%2F%2F#___top), but this wouldn’t let you access a field with a custom default value while still getting `none`s from an explicitly set field.

**Comment by laurmaedje** [comment]
I'll close this for now as it's unclear if we want to have such an operator and if so, how it will look. If we have a concrete design, we can reopen or have a new PR.

**Comment by tingerrr** [comment]
I'll use C# as an example, as it is the only language I've used with such an operator. The semantics are as follows:
- `obj?.field`: if `obj` is not null, access `field` (getter or field) and return it, else return null
  - sugar for `obj is not null ? obj.field : null`
- `obj?.func(args)`: if `ident1` is not null, call `func` with `args` and return its result, else return null
  - sugar for `obj is not null ? obj.func(args) : null`
  - therefore, `args` will only be evaluated if `obj?` is not `null`

This makes sense for C# because the existence of fields and getters is checked at compile time. We want to access a field which may not exist at all because `dict.field` is just sugar for `dict.at("field")`. So, for us, this is more of a try-mechanism than a null-chaining-mechanism.

So let's ignore field access and only consider its desugared version, `#let res = obj.field` becomes `#let res = dict.at("field")`. Fundamentally, we want this function to return `none` if it fails, instead without providing `default: none` every time.

So let's consider these calls equivalent in their result:
```typst
#let res = obj.field?
#let res = obj.at("field")?
#let res = obj.at("field", default: none)
#let res = type(obj).at(obj, "field", default: none)
```

Not every type has a `type(obj).at(obj, arg, default: none)` function, but the field access works like this under the hood, if I recall correctly. But this would then only limit it to functions which are done for field access. I propose for this to not be sugar for simply passing `default: none` to `at`, but for it to be a `try` mechanism of some sorts, where the field access is desugered first to only mean its usual function call before `?` is desugared.

The desugaring would then almost match the above example:
```typst
#let res = obj.field?
#let res = obj.at("field")?
#let res = try obj.at("field")
#let res = try type(obj).at(obj, "field")
```
Here, `try <expr>` would mean evaluate `<expr>` and return it or return `none` on failure of evaluation. Consider `try <expt>` an implementation detail, not actual syntax for users for now.

The benefits I see with this, is that this fixes a fundamental issue typst has in my opinion; `none` is not an optional, we cannot use `map` on it, any access will fail as it's a unit type with no methods or fields.

The previously provided example would be `#strucutre.footnotes?.at(0)?.body?` and roughly desugar to this:
```typst
#{
  try
    (try
      (try
        strucutre.at("footnotes")
      ).at(0)
    ).at("body")  
}
```

In current typst this is:
```typst
#let x = {
  let footnotes = structure.get("footnotes", default: none)
  if footnotes != none {
    let first = footnotes.at(0, default: none)
    if first != none {
      first.get("body", default: none)
    }
  }
}
```

One could also argue that the annotation of "trying" to do something behind the actual expression makes it harder to read, we could also prefix the access instead; `#strucutre.?footnotes.?at(0).?body`.

While we're at syntax sugar, I notice the parallel here for `.at()`; perhaps we can extend the syntax sugar `obj.at(0)` as `obj.0` and by extension of this `obj.0?`/`obj.?0`.

**Comment by lzm0** [comment]
Optional chaining is extremely useful when combined with data loading. There are people who use Typst to generate reports based on structured data such as JSON. For this use case, it's very helpful to have an expression to short-circuit to `none` instead of throwing a compile error.
We can also tackle this issue with a more functional approach, such as introducing a Functor map method `fmap` like the one in Haskell.

**Pull request closed without merging**
