### PR TITLE
Improve test-helper

### PR DESCRIPTION
**Pull request by Leedehai**
Hi, I humbly suggest these improvements to the test helper:

* Put the test name in the title of the tab. This helps with multiple tabs -- originally they were all confusingly named "Test Output".

* Visually indicate the "Rerun test" command is running, instead of having developers idly waiting (especially if a rebuild is underway) before the extension's web view flashes. This status bar item only appears when the command is running.

* Confirm before updating the reference. The buttons "Rerun test" and "Update reference image" are very close so it's easy to misclick, and a VSCode's built-in dialogue box can help to add a bit "friction" to this. But I don't have a strong opinion if maintainers decided it's better to not add this feature.

* Ability to rerun the test from within the web view panel. Often times, it is more ergonomic to trigger a rerun from the tab after editing code in some *.rs file, without having to navigate to the corresponding *.typ file (especially when there are mutiple) and click the "Rerun test" button there.

* The extension's refreshing button should reveal the hidden-but-already-opened web view panel.

* After closing the web view panel, the `panel` variable should be set to `null` so that buttons that need it (e.g. refresh) would not cause exceptions -- though the exception is invisible to the user.

### CODE REVIEW

**Comment by Leedehai** [comment]
I'll do it later.

**Comment by laurmaedje** [comment]
Nice improvements! I'd like to request two changes:
- Could the rerun button in the web view be in the menu bar? As is, it looks a bit ugly.
- I'd prefer to not have the confirmation dialogue when updating the reference image. I think it adds an unnecessary step. For the rare case of a misclick, it is easy to revert via git.

**Comment by Leedehai** [comment]
> Could the rerun button in the web view be in the menu bar? As is, it looks a bit ugly.

Aha that was my thought as well but it turned out while VSCode does allow adding menu buttons to the editor of the WebView (and I managed to do that), the menu button could not relate back to which WebView panel that click took place (the active editor property of vscode.window is falsy, since the WebView editor is not a "real" editor), and the click event object only contains an opaque URI of that WebView, and that URI can't relate back the WebView instances either: the createWebViewPanel() function doesn't report the URI of the panel it creates, and there's no state that stores the correspondence between the URIs and WebView panels.

I saw some issues opened in VSCode's repo asking specifically about this and the answer confirmed there's no good way to accomplish it, though someone suggested keeping track of all WebView instances and find the "active" one in a round-robin fashion and somehow read out info encoded in that WebView's html.

**Comment by Leedehai** [comment]
> I'd prefer to not have the confirmation dialogue

SG, I'll make the update.

> Could the rerun button in the web view be in the menu bar?

Aha that was my thought as well but it turned out while VSCode does allow adding menu buttons to the editor of the WebView and I managed to do that, the menu button could not relate back to which WebView panel that click took place on (`vscode.window.activeTextEditor`is falsy, since the editor containing the WebView panel is not a "real" editor), and the click event object only contains an opaque URI of that WebView panel, and that URI can't relate back the WebView instances either: the `createWebviewPanel()` function doesn't report the URI of the panel it creates, and there's no state that stores the correspondence between the URIs and WebView panels. 

Also, you may notice there's a thing called `activeWebviewPanelId` in VSCode extension authoring doc but IMHO it's a misnomer because it is used to ensure the button appears on WebView panels created by the test-helper extension (instead of having the button appear on every editor), but it is not used to identify WebView panel instances.

I saw some questions in VSCode's repo asking specifically about this and the answer confirmed there's no good way to accomplish it e.g. https://github.com/microsoft/vscode/issues/174905#issuecomment-1813017583 .
Though someone suggested keeping track of all WebView instances and finding the "active" one in a round-robin fashion and somehow reading out info encoded in that WebView's html. It sounds hacky & hard to maintain, but with your permission I can make a try?

**Comment by Leedehai** [comment]
Update:

> Could the rerun button in the web view be in the menu bar?

Despite what I said in the previous comment (😅), I managed to add the "Rerun test" button to the panel, thanks to the suggestion I found in https://github.com/microsoft/vscode/issues/93608:

> Option 2 or 3 are the recommended approaches
I used Option 2.

**Comment by laurmaedje** [comment]
Very nice! As a final question: Is there any reason to not have the other two buttons also in the preview window? Especially the one for updating reference images might be useful.

**Comment by Leedehai** [comment]
> Is there any reason to not have the other two buttons also in the preview window? Especially the one for updating reference images might be useful.
No particular reason; so I just added them, too.

**Comment by Leedehai** [comment]
> Is there any reason to not have the other two buttons also in the preview window? Especially the one for updating reference images might be useful.

No particular reason; so I added them, too 😃

**Comment by laurmaedje** [comment]
Thank you for the very nice improvements!

**Pull request merged**
