### PR TITLE
Add base 16, 8 and 2 for numbering 

### PR DESCRIPTION
**Pull request by 3nt3**

### CODE REVIEW

**Comment by lucifer1004** [comment]
Why not add bin and oct as well?

**Comment by LaurenzV** [comment]
Honestly, I've never seen anyone using a hexadecimal numbering pattern for lists, not sure if it's really worth it to add this to the library. I guess there's no harm in adding it, but still.

**Comment by 3nt3** [comment]
@LaurenzV: I've mostly seen it done in kind of nerdy/techy publications as a sort of gimmick and wanted to replicate that

@lucifer1004: done

**Comment by laurmaedje** [comment]
I first want to figure out the numbering story before having more patterns.

**Comment by laurmaedje** [comment]
Numbering patterns need a general rework to handle the collision problem. Perhaps there will be base 2, 8, and 16 as part of that, but I think it will be easier to integrate that with this rework later than rebasing this, so I'm going to close this.

**Pull request closed without merging**
