### PR TITLE
Fix the test image of numbering.png

### PR DESCRIPTION
**Pull request by k-84mo10**
What I create pull request "add current numbering way of hiragana and katakana" can cause error in test.
Therefore, I fix the test image of numbering.png.

I think it will solve the test error.

### CODE REVIEW

**Comment by Leedehai** [comment]
Hi - I wonder was this because the error-ing image file was created by clicking the "Update" button in the test-helper extension? If so, could you please provide the `oxipng` version installed on your PATH? I wonder if it's because the `oxipng` on the PATH is different from the `oxipng` in Typst's dependency tree.

Even if it's the case, it's still bewildering why the CI was not able to flag this issue when #3012 was being merged...

**Comment by k-84mo10** [comment]
Hi,  thank you for providing me with various information. However, this may be a more straightforward issue.

Due to my testing across multiple environments, I accidentally requested a branch that still has images not yet updated. In fact, e970cfd is what I requested and CI test caused error, so I had to update the figure to pass the CI test. However, for some reason, though the error is still persisted , it was got merged into the main branch.

By the way, my oxipng version is 9.00 and it is the same as the one in the root Cargo.toml.

**Comment by laurmaedje** [comment]
@reknih most likely just missed the failing CI. regarding this PR: why does it show a diff on the code and not just on the reference image?

**Comment by reknih** [comment]
I have rebased the PR upon `main`. The diff now only contains the changed test image and two whitespace changes in the test case. Excuse me for not catching the test failure yesterday.

**Comment by PgBiel** [comment]
I believe it could be worthwhile for this repo to adopt a [merge queue](https://github.blog/2023-07-12-github-merge-queue-is-generally-available/) so as to avoid this problem in the future: it runs CI again on the PR (or on each PR in the queue) before merging, and only merges if CI passes, otherwise merging is cancelled.

**Pull request merged**
