### PR TITLE
Clarify the way to access functions from dictionaries

### PR DESCRIPTION
**Pull request by Leedehai**
Hi - while writing a package I found this hint needs a bit further clarification, hence this PR. Otherwise, users could interpret field access as `#dict(.fun)(...)`, `dict(.fun)(...)`, or `(#dict.fun)(...)` like I did.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Perhaps this should show the concrete field? Unfortunately, there's no way to show the concrete dictionary, too, though.

**Comment by Leedehai** [comment]
Sorry, could you clarify what it means by "concrete"? Is it in the sense that the made-up names like `dict` and `fun` are not "concrete" since there are made up?

**Comment by laurmaedje** [comment]
Yes, that. Since the concrete field name is known, we could use it.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
