### PR TITLE
Allow math as a followup argument to functions.

### PR DESCRIPTION
**Pull request by damaxwell**
Typst has a convenient notation for providing a content block as an argument to a function: `#foo[ stuff ]`.  This PR is a change to the parser that allows something similar for math, so that expressions like
```
#splitlines$
<STUFF>
$
```
become legal.  This mechanism could also be an interim measure for turning on/of equation numbering until/unless a better shorthand to do this is decided upon.

Dollar signs are trickier than parentheses, so the feature for math is more restrictive than for content.
1) The notation isn't allowed  in math mode itself; otherwise it's hard to know if a dollar sign is supposed to end the math mode or is supposed to be an extra argument to a function call.  Thanks, test suite, for pointing out this interaction.
2) Although it's possible to write things like `#foo("hi")[content 1][content 2]` for functions, <del>you can only pass one equation to a function with the new notation, and only if it's the only "follow up" argument. So `#foo("howdy")$x=y$`passes two arguments to `foo`, but `#foo["howdy"]$x=y$` passes just the string, `#foo$x=y$["howdy"]` passes just the equation, and `#foo$x=y$$a=b$`, which nobody should write anyway, passes just `$x=y$`.  </del>

As I write this, I think that I'm just being chicken about rule 2), and it could probably be relaxed.  Parser changes make me nervous.  Rule 1) is essential, though.

## Notes
* If this PR is accepted in some form, user-facing documentation needs to be updated.
* The parser supports `#set foo[bar]` but I wasn't able to figure out a combination of `foo` and `bar` that actually triggered this path and didn't result in error.  It would be good to know a combination so that I can add a test for `#set foo$x=y$` if that's a meaningful thing to do.

### CODE REVIEW

**Comment by damaxwell** [comment]
I'm feeling brave.  Rule 1 is the only restriction: this notation isn't available in math. Easy to explain, and I think it's safe.

**Comment by PgBiel** [comment]
So, being honest (and not at all trying to disregard your awesome work overall), I'd like to point out that I'm not sure this particular change would be beneficial. `#func[...]` indicates pretty clearly where the argument starts and ends, while
```
#func$
...
$
```

can be pretty confusing to look at, especially if more dollar sign usage comes before `#func`, which would make code harder to read in a first glance (and e.g. harder to tell where math starts and ends, or if `#func` is just something inserted into a math context instead of a function being called). Of course, syntax highlighting could be useful here and all that, but I think having to write `#func($ ... $)` is entirely fine, not very ugly (compared to `#func([...])`, which just looks 'excessive'), and less ambiguous. I'd like to hear other opinions, however.

**Comment by PgBiel** [comment]
Of course, my perspective would be pretty different if we instead just changed Typst to behave like typical functional languages and begin accepting `#func argument1 argument2` everywhere, regardless of the type of each argument. But I believe that's not a direction that Typst is currently heading to.

**Comment by damaxwell** [comment]
Thanks for the kind words about the work overall. I'll try to explain better the use case.

One of the great things about Typst is that it doesn't have a lot of ceremony.  I'm a mathematician and my documents are going to be full of things like
```
#theorem[
Suppose $a$, $b in RR$,....
...
...]

```
A paragraph long, say.  And if I decide to change to a lemma, great. Just change the `#theorem` to `#lemma`.  The `\begin{theorem} .... \end{theorem}` ceremony has been shortened, and changes happen only at the beginning.

I can see my documents as being filled with tagged content blocks like the above.

Now for displayed equations. Again, little ceremony:
```
$
line 1\
line 2\
line 3
$
```
But now there is perhaps too little ceremony. That single dollar sign can't carry much for semantics.  For the most part, it's just a delimiter, admittedly a suboptimal delimiter, but we've inherited it.  As a consequence of its deficiencies, in practice you'll use whitespace to make displayed equations stand out, which you do in Tex flavors anyway.

It's currently a bit of a hassle to style one-off displayed equations.  You can make a function that applies the styles, but then to apply it, you need to decorate the beginning and the end of the display. Maybe with a round bracket. Probably with a square one so that if I take away the function name at the beginning, what is left behind is legal Typst.  Equations will, with luck, soon allow a choice of numbering styles (equation 5,6,7 vs equation 5.a, 5.b, 5.c for the block). Sometimes you just want the sub numbering for a single display. The aim of this PR is to make styling displayed equations easy (and parallel to how text blocks are styled):
```
#subnumber$
line 1
line 2
line 3
$
Carry on.
```
Visually, it's a tagged block like theorems and lemmas. Not as strong, because `$`, but still a tagged block. And you change something at the start of the block and don't need to jump to the end.  Admittedly, one can do
```
#subnumber[$
line 1
line 2
line 3
$]
Carry on.
```
But this has the paper cut analogous to the LaTeX dance of going to the beginning and the end of the display to add `*` to turn off the numbering.

There aren't a lot of knobs on `math.equation` yet.  But they are going to grow, as will the possibilities for wrapping the body of an equation with a function to affect layout.  If so, I think there's going to be a need for being able to conveniently style a displayed equation.

**Comment by sitandr** [comment]
I either don't think it is a good idea. I understand well why do you want it, but it just looks bad and ambiguous. Imagine, for example,

```
#subnumber$
 line 1
 line 2
$
line 3
$
line 4
$

```

Yes, you can add spacing and comments, but still it is much harder to read than

```
#subnumber($
 line 1
 line 2
$)
line 3
$
line 4
$
```

I think adding there extra parentheses is worth of it.

**Comment by Enivex** [comment]
I tend to agree with @damaxwell here, as someone who writes a lot of mathematics. I've often wondered why this wasn't already a thing, considering the syntax for content. With syntax highlighting this really isn't as ambiguous as you make it out to be.

The presence of the parentheses themselves isn't necessarily the problem. It's dealing with the one that is _after_ the equation. This introduces extra friction. Keep in mind that someone might have hundreds of equations in their document that they may want to change the behavior of regularly.

If not _this_ syntax, it's at least worth discussing mechanisms for manipulating equations in typst.

**Comment by PgBiel** [comment]
I appreciate the explanation and the discussion. I see the main purpose of this PR now, and understand what it's meant to solve.
I was thinking, however, that this might just not be the ideal way to solve it, although it is one of the possibilities, for sure.
Mostly because I think this particular syntax can be a bit of an annoyance to work with, in the sense that
```js
#func$
a
b
$
```

Can be easily confused with (and, depending on `func`, barely be visually different from)
```js
#func $
a
b
$
```

I think that, more generally, what we might need is some more convenient notation for "large content wrappers" in text. Not just for equations, but for content in general, because I believe this change would be too restrictive. Something like (note: prone to bikeshedding)

```
/ #function:
  $ equation $

/ #theorem:
  1 + 1 = 2

/ #proof:
  Trivial.
```

A.k.a. something like term lists, but which applies a function to any content indented under it. That'd reduce the need for the closing delimiters, as proposed. I think that might be a better solution overall in terms of syntax, but further discussion is definitely needed.

**Comment by sitandr** [comment]
I guess one of main concerns there is wrapping multi-line equations. The proposal of @PgBiel needs indentation at least, and relying on indentation has lots of its own drawbacks. I guess Typst wants to avoid it as much as possible outside of "markdown" mode, and I like it.

Also that thing visually mixes markdown and code modes, and I have no idea how much of parser work that could require.

I don't say it is not feasible, just that there is much to discuss. :)

**Comment by damaxwell** [comment]
Ha! And I had thought that #1855 was going to be the controversial one...

Thanks for the thoughtful conversation, everyone.  

Here's Typst in the trenches.  This is a translation of part of a paper I posted recently on the arXiv.  It's a screenshot so that there is syntax highlighting .

A)
image

The first thing that strikes me is how dang readable this is compared to the original LaTeX, which I'll put at the bottom of the post.  The problem I'd like to address is how to introduce a mechanism to conveniently style the displayed equations.  Let's suppose that I've decided that the two equations in the list should have function `#foo` applied to them.  Here's what it looks like with this PR:

B)
image

I'll agree that it's not perfect notation.  But it's not that bad, and it's parallel to the notation for `#proposition`. Alternatives?

@PgBiel 's proposal is interesting generally. Here it is:

C)
image

It has visual clarity: there's no doubt here that `#foo` is being applied to those displays.   But it's not a quick adjustment.  To add the decoration, the display needs indentation, which means highlighting the display and getting the editor to indent. The other alternative raised above is just wrap the displays in functions.  If that's the case, content wrapping is the way to go.  Here it is.

D)
image

Visually, it's more compact than C), and I appreciate that.  It's just as clear in C) and D) that `#foo` is being applied, but frankly I think the same thing can be said for B).  I think that D) also has a mild edge over B) visually.  But it comes at a cost: I have to go to the end of the display to add the dang `]`.  If I change my mind, I'll delete the `#foo` and leave the square brackets.  They do no harm, and they'll make it easy if I come back and want to add a different tag.  But as I scroll back among the options above, given the general noise that comes with markup, they all feel pretty similar.  And I know which one I'd rather type. 😉

Here's the source, in case you want to try your hand at an alternative:
```
#proposition(<rescale-int>)[
Suppose $1<p<oo$, $m in ZZ$ and that $chi$ is a Schwartz function on $RR^n$.
There exists a constant $alpha in RR$ such that for all $0<r <= 1$ and all 
$u in H^(m,p)(RR^n)$,
$
    ||chi u_rscr||_(H^(m,p)(RR^n)) lsim  r^alpha||u||_(H^(m,p)(RR^n))
$ <eq:Hsp-scale>
Specifically:
+ Inequality @eq:Hsp-scale holds with    
    $
        alpha = min(m-n/p,0)
    $
    unless $m-n\/p=0$, in which case it holds for any choice of $alpha<0$, with 
    implicit constant depending on $alpha$.
+ If $m>n/p$ (in which case functions in $H^(m,p)(RR^n)$ are Hölder continuous)
    and if $u(0)=0$, then inequality @eq:Hsp-scale holds with
    $
        alpha = min(m-n/p,1)
    $
    unless $m-n\/p=1$, in which case it holds for any choice of $alpha<1$, with 
    implicit constant depending on $alpha$.
] 
```

Here's the original LaTeX, BTW:
image

**Comment by laurmaedje** [comment]
I am not sure about this syntax. I think if we do it, then only if we allow trailing code blocks too because then all three kinds of blocks work. Although one might consider raw blocks a fourth kind. (Which is supported by both raw and math working in code environments as opposed to any other kind of markup.)

**Comment by PgBiel** [comment]
> B) --snip--
> 
> I'll agree that it's not perfect notation. But it's not that bad, and it's parallel to the notation for `#proposition`. Alternatives?

I think your image made me understand better what I feel uneasy with regarding this proposal. This seems to be oddly reminiscent to how LaTeX has commands which consume their parameters from things right after them, such as `\kern0.25em` or something, and that in particular has always seemed a bit odd to me, because it can be hard (even impossible syntactically) to tell apart from a command which doesn't take parameters at all and is just followed by some normal text. In the same spirit, when I look at your image at first, I think of something like `#foo$...$` just looking like we're inserting the contents of a variable `foo`, and then adding a math environment after it. And the main reason for this issue is that `$...$` is valid syntax in both markup and code, so it would make perfect sense (both semantically and syntactically) for it to be equal to `#foo $...$`, while `#foo[...]` is clearly one big thing, as `#foo [...]` would just display the `[...]` part outright, hence why it feels more consistent. In general, I think it just didn't kinda resonate with the rest of Typst for me. (A similar point would be made regarding the ````#foo```...``` ```` proposal as well.)

> @PgBiel 's proposal is interesting generally. Here it is:
> 
> C)  ---snip---
> 
> (...) But it's not a quick adjustment. To add the decoration, the display needs indentation, which means highlighting the display and getting the editor to indent. (...)
> 
> D) ---snip---
> 
> Visually, it's more compact than C), and I appreciate that. It's just as clear in C) and D) that `#foo` is being applied, but frankly I think the same thing can be said for B). I think that D) also has a mild edge over B) visually. But it comes at a cost: I have to go to the end of the display to add the dang `]`.

I forgot to mention this as part of my proposal, but the indentation could very well be optional when your stuff inside the content requires only one line to begin(/end). Thus, something like

```js
/ #function: $
  ...
$

/ #theorem: 1 + 2 = 3.
/ #proof: Trivial.
```
Could also work, and would probably be closer to what you're looking for here. (Just a thought, however.)

**Comment by damaxwell** [comment]
I see! I like it!

I'd be even happier if
```
/  #foo:
$
    alpha = min(m-n/p,0)
$
```
and especially if
```
#foo:
$
    alpha = min(m-n/p,0)
$
```
with the trailing colon on the function name indicating "eat the next thing".   A nice win for either of these is that removing the decoration is a line deletion, and the beginning of the display remains as prominent as the end. But even the @PgBiel 's original
```
/ foo: $
    alpha = min(m-n/p,0)
$
```
would be cleaner to read than the syntax proposed in this PR.

**Comment by damaxwell** [comment]
I'm going to close this and will post a feature request in its stead.

**Pull request closed without merging**
