### PR TITLE
Use U+2212 MINUS SIGN instead of U+002D HYPHEN MINUS when displaying an `integer` or a `float`

### LINKED ISSUE #1762: Minus sign rendered differently when using numbers from variables in math mode
### Description

When rendering a negative number in math mode using Typst 0.6.0

```
$-2.5$
```
**Output:**
direct

the minus sign looks different to the same code when using a variable:
```
#let x = -2.5
$#x$
```
**Output:**
varibale

### Reproduction URL

_No response_

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by MDLC01**
Fixes #1762

This simply changes the implementation of `Value::display` to use a `−` instead of `-` as the minus sign for `integer`s and `float`s.

## Open questions

1. Should I change the [`str` function](https://typst.app/docs/reference/construct/str/) to use a `−` instead of a `-` too?

2. I'm not sure if I added the tests at the right place.

### CODE REVIEW

**Comment by MDLC01** [comment]
I'm not sure I understand everything, but displaying an `integer` or a `float` should always result in U+2212 MINUS SIGN being used instead of U+002D HYPHEN MINUS, no matter the context.

> But I worry that with this change, maybe now `-34` (i.e. ordinary text) and `#let x=-34;#x` will look different from each other.

You are right: `-34` (with a U+002D HYPHEN MINUS) will look different from `#let x = -34; #x`. But I guess this is a slightly different issue (although I recognize I did not think of it before).

I can think of two solutions:
1. Keep it that way, and the user can make them look the same by using a U+2212 MINUS SIGN instead of a U+002D HYPHEN MINUS in the source code or using the `#let x = -34; #x` trick; or
2. Detect when a U+002D HYPHEN MINUS is used before a digit and replace it with a U+2212 MINUS SIGN.

Solution 1 is easier to implement (as we don't have to do anything), but not satisfying at all. Solution 2 is far better from a user experience point of view in my opinion, but harder to implement (it has to work for all numbering systems, without triggering false positives).

I guess a third solution would be to revert this change, but then #1762 would stay open, and I feel like using an ugly U+002D HYPHEN MINUS in place of a pretty U+2212 MINUS SIGN is not what I expect from Typst.

**Comment by damaxwell** [comment]
Option 2 seems pretty reasonable to me. It's a modest change to the lexer and a cousin of shorthand/smart quotes though isn't exactly shorthand. In the spirit of those two transformations, I'd keep the rule simple: hyphen-minus followed by digit or by dot digit becomes minus. In LaTeX, you learn that for best results you always put numbers in math mode, and one benefit is you get a large minus sign. This gets that behavior by default. In the seemingly rare cases this is the wrong thing to do, the consequence is mild: a slightly longer straight line. And the fix is easy: escape the hyphen.

**Comment by damaxwell** [comment]
Oh, but regex. `show "-34": ...` would no longer match on text `-34`. But come to think of it, this is already broken in math as it stands. So this would be just another helping of the same broken.

**Comment by MDLC01** [comment]
> hyphen-minus followed by digit or by dot digit becomes minus

I think this is a good enough solution indeed. U+002D now becomes U+2212 when before a numeric character (according to [`char::is_numeric`](https://doc.rust-lang.org/std/primitive.char.html#method.is_numeric)) in text mode. It does not when before a period, though, as other languages may use a different decimal (or _whatever_-ary) separator, and the "−.5" notation is not that common in most contexts I think (+ it would likely have triggered false positives).

I tried to add international tests.

Also, in `2023-2023`, the U+002D is not converted to a U+2212. This is what I would expect, but I'm not sure I understand _why_ it works, because I never tried to make it work in the first place.

**Comment by damaxwell** [comment]
> Also, in `2023-2023`, the U+002D is not converted to a U+2212. This is what I would expect, but I'm not sure I understand _why_ it works, because I never tried to make it work in the first place.

It works because `Lexer::text` is stingy about returning.  Once a text run has begun, there is a table of characters that stop the run.  But then there are then exceptions. A `-` stops the run, but only if it is followed by `-` or `?`, (in which case it is about to become shorthand).  Because you didn't add the new shorthand to this list of exceptions, a `-` followed by numeric in the middle of a text run doesn't trigger the shorthand and gets gobbled into the text.

I didn't see a spot in Typst's documentation where there is a list of shorthands.  It's mentioned in the Syntax section, which sends you over to Symbols for more info, where there seems to be no such info.  Had there been a spot, it seems like this is a subtle enough transformation that it deserves user documentation.

**Comment by MDLC01** [comment]
Thanks for the explanation!

In our case, I think it is safe to keep the current implementation, as there is no instance of a U+002D following text that we want to convert to a U+2212.

**Comment by bluebear94** [comment]
> Also, in `2023-2023`, the U+002D is not converted to a U+2212. This is what I would expect, but I'm not sure I understand _why_ it works, because I never tried to make it work in the first place.

The intended character in this case could be either U+2013 or U+2212 (though for the former case, you can already use `2023--2023`).

**Comment by MDLC01** [comment]
I think it is better to leave it as it is currently (that is, keep the U+002D HYPHEN MINUS). You can force a U+2013 EN DASH by writing `2022--2023`, and a U+2212 MINUS SIGN does not make much sense in this context.

**Comment by laurmaedje** [comment]
I think it is problematic that the `str` function behaves differently now. I would expect that `[#x]` and `[#str(x)]` always behaves the same way if `x` is an integer or a float.

**Comment by MDLC01** [comment]
The `str` function now uses a U+2212 MINUS SIGN for negative numbers, for both `integer`s and `float`s.

The current solution does not ensure the implementations of `[#x]` and `#str(x)` for `integer`s and `float`s stays equivalent in the future.

**Comment by laurmaedje** [comment]
I am okay with making this change, but then we need to make it across the board. In particular:

- The `int` and `float` functions must be able to parse U+2212 in addition the normal hyphen
- The parser should also allow U+2212 as an alternative to the normal hyphen
- `repr` should behave like `str`
- `repr` for all other numeric types should follow the same convention

Implementing all this nicely without much duplication and few allocations is challenging. E.g., `format!("{}", v).replace('-', "\u{2212}").into()` allocates two intermediate `String`s even though all we want in the end is an `EcoString`. We might also need to introduce a separate `Repr` trait which is distinct from `Debug` to generalize this for i64 and f64. Such a trait is in fact long overdue.

I understand if this is too complicated for this PR and in that case I would implement it myself.

**Comment by MDLC01** [comment]
Feel free to add the `Repr` trait yourself.

I will send a message here when I start working on this PR again, so that we do not end up doing the same work twice.

**Comment by MDLC01** [comment]
Just to keep you updated, I haven't forgotten about this PR, and I should be able to work on it soon.

**Comment by MDLC01** [comment]
I'm finally able to work on this PR again!

About the `Repr` trait, do you want me to add it in a separate PR or this one? Also, I'm not sure where to add it within the file structure. I was thinking maybe somewhere within `typst::eval`...

**Comment by laurmaedje** [comment]
> About the Repr trait, do you want me to add it in a separate PR or this one? Also, I'm not sure where to add it within the file structure. I was thinking maybe somewhere within typst::eval...

Sorry, I completely forgot to answer! I think a separate PR would make sense. You could add it to `value.rs` or in a new `repr.rs` file. The question also remains how it would look. I think `trait Repr { fn repr(&self) -> EcoString { .. } }` would be simplest, rather than a Display-like interface with a mutable buffer.

**Comment by MDLC01** [comment]
I'm closing this PR in favor of #2318, which branches from a version of `main` that  contains the `Repr` trait.

**Pull request closed without merging**
