### PR TITLE
Wait for command to fix compile + open not opening a PDF-reader

### LINKED ISSUE #2725: --open does not work with compile one Windows
From the Windows command line (cmd.exe), this watches the documend and opens the PDF viewer:

    typst.exe watch --open c:\bin\SumatraPDF\SumatraPDF.exe test.typ

This compiles the document, but does not open the PDF viewer:

    typst.exe compile --open c:\bin\SumatraPDF\SumatraPDF.exe test.typ

I don't get any output either.

As far as I can tell, it works fine on Linux.

Typst 0.9.0 (7bb4f6df) on Windows 10 22H2

### PR DESCRIPTION
**Pull request by TheJosefOlsson**
This will close #2725. Will wait for the command to properly launch before exiting the application to avoid the reader not opening.

### CODE REVIEW

**Comment by laurmaedje** [comment]
`that_in_background` + `join` seems to be pretty much equivalent to just `that` from my reading of `open`'s code, except that it spawns an extra thread.

I'm not sure what `that_detached` does as opposed to the other two. Did you try that one?

**Comment by TheJosefOlsson** [comment]
Using `with`  and `that` seems to work. My once concern to changing is that I think it could be desirable to start the processes in the background when watching the file which would not happen with `with`  and `that`. Is that a priority?

**Comment by TheJosefOlsson** [comment]
It turns out that since .take() is used on the command, the code in question will only ever be run once, not once per compilation. Therefore I thought that the added complexity of adding another argument and if statements was not a good trade-off for the small time it could potentially save when compiling for the first time. That is why I changed it to always use `that` and `with`.

@laurmaedje is this a good tradeoff? You can see the difference when considering watching in my commits

**Comment by laurmaedje** [comment]
I agree with you. Thanks!

**Comment by laurmaedje** [comment]
Right after merging I found https://github.com/typst/typst/pull/706, so the in-background opening was a bug fix! This means we unfortunately need to reconsider what to do here. 

I have reverted the change by removing this merged commit from main. :/

**Comment by Joffjoff5000** [comment]
Using chrome I have never been able to get it to automatically update the PDF when watching, neither before or after this commit so either way #706 did not truly solve that for all instances. I just assumed it was a limitation of the PDF reader and not a bug. Perhaps #2842 should be used then since it solved the issue?

**Comment by laurmaedje** [comment]
#706 is not about the PDF viewer hot reloading. That's just a feature not all PDF readers have. (Chrome doesn't, but Skim and SumatraPDF for instance do). The issue in #706 was that Typst stopped doing anything because the `open` call never returned.

**Pull request merged**
